### ISSUE TITLE
The experiment codebook has has no value for "extras"

### ISSUE THREAD

**Issue by rojinsafavi** [spacetx/starfish#1015]
Hello again!

```
{ 'codebook': 'codebook.json',
  'extras': {},
  'images': {'nuclei': 'nuclei.json', 'primary': 'primary_images.json'},
  'version': '5.0.0'}
```

and : 
```
<xarray.Codebook (target: 1, c: 1, r: 1)>
array([[[1]]], dtype=uint8)
Coordinates:
  * target   (target) object 'PLEASE_REPLACE_ME'
  * c        (c) int64 0
  * r        (r) int64 0
```

I reinstalled starfish by downloading the repo and using pip install -e .[napari] command.

I downloaded merfish data from the Amazon s3 bucket, and reformated the data using format_merfish_U2OS_data.py  

Thanks :-)

**Comment by ttung** [comment]
I'm not sure where it is expected that the codebook have an extras field.  Can you explain what error you are seeing?

**Comment by ttung** [comment]
Can you clarify this and assign it back to me?  Thanks!

**Comment by neuromusic** [comment]
Closing this issue. Feel free to reopen if you are still having issues, @rojinsafavi!
