### ISSUE TITLE
Provide fast access to SpaceTx format metadata (e.g. Coordinates) via the API

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1016]
Currently, one is required to load the data to access the metadata. For example, the below call to extract coordinates requires first loading primary images, which in this case is a 45s operation. 

```
experiment = Experiment.from_json("experiment.json")
f1 = experiment["fov_001"]
f1[FieldOfView.PRIMARY_IMAGES]._coordinates.values
```

We should expose a rapid way to access the metadata from SpaceTx-format without requiring users to go through heavyweight compute operations.

**Comment by ambrosejcarr** [comment]
May be fixed as a side effect of #1003

**Comment by ambrosejcarr** [comment]
Example use case for needing coordinates before image data: 
> [for] affine transformations, you can transform the bounding box and use the resulting info to decide if you need to load a given FOV to fill an arbitrary bounding box.

**Comment by ttung** [comment]
Since #1003 isn't going to be resolved anytime soon, we probably need a better solution this.  I think we have to lazy-load the array data...  The path to doing so seems pretty straightforward.

**Comment by ttung** [comment]
#1456 probably solves this.
