### ISSUE TITLE
Should codebook be a JSON object or a netCDF/Zarr file? 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1029]
See https://github.com/spacetx/starfish/pull/892, 

Recording a conversation between @ambrosejcarr (quotes) and @joshmoore (unquoted)

> If we're comfortable with (for now) netcdf as a cross-platform standard, we could go this route.

You're _less_ comfortable with the support for codebook compared to say the intensity table because the codebook is more core, e.g. an input rather than an output? Might need to think that through... but I imagine if we're looking at _any_ use of netcdf then the cross-platformness issue will need to be dealt with regardless. (I currently assume it will be fine)

My motivation was largely coming from a mixture of the fact that `Codebook` is-a `DataArray` and the sizes that are possible.

> In the future, I imagine we'd dump them as Zarr?

There's likely a question here of whether or not to support the more general xarray io methods or to restrict to a subset. In the former case, you'd get json, netcdf, and eventually zarr directly.

> Could you flesh out how you'd suggest we approach this @joshmoore ?

Really, for any of the classes that are-a `xarray` type, having a single format (essentially, `DataArray` and `Dataset`) feels safe enough.

In my case, having installed the netcdf libraries, using `c.to_netcdf("codebook.nc")` and reading it back in with `xr.open_dataset("codebook.nc")` produced something I could immediately relate to:

```
Out[9]:
<xarray.Dataset>
Dimensions:                        (c: 2, r: 8, target: 140)
Coordinates:
  * target                         (target) object 'Blank-1' 'Blank-10' ...
  * c                              (c) int64 0 1
  * r                              (r) int64 0 1 2 3 4 5 6 7
Data variables:
    __xarray_dataarray_variable__  (target, c, r) uint8 ...
```

Other than the somewhat unfortunate `__xarray_dataarray_variable__` this actually seems quite portable, even outside the starfish library.

That being said, during that investigation, `json.store(c.to_json(), open("codebook.json"))` proved to be reasonably fast as well and products the same results without the opaque `nc` file, which is what made me wonder if codebooks "schema" should essentially be just the xarray json serialization.

_Originally posted by @joshmoore in https://github.com/spacetx/starfish/pull/892#issuecomment-451955286_

**Comment by berl** [comment]
please json! so the input data format is human readable and we don't have to add dependencies for someone to write a compatible dataset to disk.

**Comment by joshmoore** [comment]
Fair point. I was definitely only considering the read use case. Can you give your opinion on the json output format for netcdf (`c.to_json()`):
```
{
  "coords": {
    "target": {
      "dims": [
        "target"
      ]
      "data": [
        "Cers1",
        "Cers2",
        "Cers3"
      ],
    },
    "r": {
      "dims": [
        "r"
      ],
      "data": [
        0,
        1,
        2,
        3,
        4
      ]
    }
  },
  "dims": {
    "r": 5,
    "target": 1
  },
  "data_vars": {
    "0": {
      "dims": [
        "target",
        "r"
      ],
      "data": [
        [
          0,
          0,
          0,
          0,
          0
        ]
      ]
    },
    "1": {
      "data": [
        [
          0,
          1,
          0,
          0,
          0
        ]
      ],
...
```
