### ISSUE TITLE
Codebook docstrings need to be updated

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#1033]
The docstrings in `codebook.py` need to be updated. I didn't make an exhaustive search, but a few things I noticed:
* the round dimensions are still listed as "h" instead of "r"
* the input arguments are wrong in the class docstring example (should be `n_channel` instead of `n_ch`)

**Comment by neuromusic** [comment]
@ttung says "this is easy, I'll do it"

stay tuned...
