### ISSUE TITLE
Pass image tiles as xarrays to function in ImageStack.apply()

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#1034]
As @ambrosejcarr and I discussed in #987 , I think it would be helpful if the image tiles passed to the function being applied to the ImageStack in ImageStack.apply() were passes as an xarray DataArray instead of numpy ndarray. There are many cases where we can use the labeled axes to guarantee the operation is performed correctly (e.g., applying corrections). I don't think we loose any functionality because all current filters can just use `DataArray.values`. However, I am not sure how this would interact with multiprocessing. Thoughts @shanaxel42 and @ttung?

**Comment by ambrosejcarr** [comment]
Closed by #1035
