### ISSUE TITLE
SpaceTx output format for decoded spots

### ISSUE THREAD

**Issue by berl** [spacetx/starfish#1076]
The `IntensityTable` has great features as an internal `starfish` data structure and the corresponding `.netcdf` file is the natural representation of that on disk.  For users to work on downstream processing such as segmentation based on spots and spatial maps of decoded mRNA counts, we really only need a format that contains the following information for every mRNA spot after decoding:
x,y,z coordinates in physical units
target name
optional: quality score (e.g. from decoding)  

I think a delimited text format would work fine for this- let's keep it simple. 
This could be written to disk directly from the `IntensityTable` but I would also appreciate having access to it as a data structure...

**Comment by berl** [comment]
@ambrosejcarr ^^^

**Comment by ambrosejcarr** [comment]
does the `IntensityTable.to_features_dataframe` method satisfy your requirements?
