### ISSUE TITLE
Feature request: display() should be able to add images to an existing viewer

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#1086]
I think it would be useful if `display()` had the option to add the image as a new layer to an existing Napari `viewer`. This is super useful for comparing the image before/after a processing step (e.g., filtering).

Thoughts, @kne42 and @ambrosejcarr ?

**Comment by kevinyamauchi** [comment]
I am happy to take a stab at this if you all agree that it's useful.

**Comment by ambrosejcarr** [comment]
> This is super useful for comparing the image before/after a processing step (e.g., filtering).

Could you help me understand what advantage there is to having the images be on the same processing step vs just tabbing back and forth between the images? Are you using transparency somehow?

**Comment by kevinyamauchi** [comment]
I think the main reason including multiple `ImageStack` in the same viewer is useful is that it keeps them aligned. That way as you pan and zoom between different features, you can immediately compare how they are changed between different processing steps.

In terms of how to compare, I sometimes use opacity as you mentioned, but I mostly hide/show specific layers (the eyeball on the right hand side tool bar).

**Comment by ambrosejcarr** [comment]
> I think the main reason including multiple ImageStack in the same viewer is useful is that it keeps them aligned. That way as you pan and zoom between different features, you can immediately compare how they are changed between different processing steps.

Got it, makes sense to me! It'd be great if you would take a stab at this. How do you imagine changing the interface to support a persistent viewer?

**Comment by kevinyamauchi** [comment]
I propose to add an optional input argument that takes a napari `Viewer` object. If a `Viewer` object is provided, `display()` would append the image/spots as new layers in the provided `Viewer`. 

The `display()` returns the `Viewer` object, so the usage pattern would be:
```python
# Look at the unprocessed image
viewer = display(stack=unprocessed_stack)

# Do some filtering
ghp = Filter.GaussianHighPass(sigma=3)
high_passed = ghp.run(primary_image, verbose=True, in_place=False)

# Admire your results
display(stack=high_passed, viewer=viewer)
```

A question I have: my understanding is that the `Viewer` object would be passed by reference `display()`. When the user passes in a `Viewer` to append to, should `display()` return the reference to the `Viewer` object or nothing?

**Comment by kne42** [comment]
Sounds like a great API to me. It should return the same viewer as passed in :)
