### ISSUE TITLE
Fix Target Assignment for CLI

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1088]
- Target Assignment CLI returns `NotImplementedError`
- Target Assignment `run()` contract requests regional, which is not consistent with `Label`, our only target assignment algorithm. 
- Regional is listed as a dependency but is not used by `starfish`.

**Comment by ttung** [comment]
Is this a 0.1.0 requirement?

**Comment by ambrosejcarr** [comment]
In my opinion this depends on whether we want our users to be able to use the CLI at the hackathon, and on whether we want feedback on the CLI at the hackathon. I could see it being 0.1.0 or 0.2.0.

**Comment by shanaxel42** [comment]
no more cli!
