### ISSUE TITLE
How to structure physical coords on ImageStack.

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1136]
Our Imagestack model has 5 dimensions {round, ch, zplane, x and y}. Currently you can label the round/ch and zplane dimensions with offset values to handle a scenario in which a user is processing offset dimensions, say zplanes {4, 6, 8}. We do this by creating xarray labels on the dimensions r/ch/zplane. We also have information about the physical coordinates of the x/y and z dimensions. Currently we store these values as separate coordinate arrays on the underlying xarray with their own names xc/yc/zc. They are associated with their corresponding dimension (meaning for every pixel value of x there is a corresponding physical value of x) but they are not official xarray labels of the dimension.  I'll use the same Imagestack as an example throughout this issue...

Lets say we are dealing with FOV with 3 rounds {4, 3, 6}, 3 channels {2, 3, 4}, 3 zplanes {5, 6, 8} and 10x10 pixel images for each where x spans physical space from 1.0 to 2.0 mm, y spans physical space from 4.0mm to 6mm, and z spans physical space from 2.2 to 4.5 mm. Apologies if this isn't a realistic scenario, but anyway our current data model would represent this ImageStack like this:
```
<xarray.DataArray (r: 3, c: 2, z: 3, y: 10, x: 10)>
array([[[[[1., ..., 1.],
         ...,
          [1., ..., 1.]]]]], dtype=float32)
Coordinates:
  * r        (r) int64 4, 3, 6
  * c        (c) int64 2, 3, 4
  * z        (z) int64 5 6 8
    xc       (x) float64 1.0 1.111 1.222 1.333 1.444 1.556 1.667 1.778 1.889 2.0
    yc       (y) float64 4.0 4.222 4.444 4.667 4.889 5.111 5.333 5.556 5.778 6.0
    zc       (z) float64 2.2  3.1  4.5
```
### Scenario 1
We maintain this data structure and then there are two options for indexing by physical coordinates.

**Option 1:**
Create a separate `sel_by_physcial_coords` method that handles indexing by physical coordinates.
If a user wanted to select on this xarray round: 4, ch: 3, zplane: 5, and x in 4.2 to 5 physical space they would do so with two commands like this:

`stack.sel({Axes.ROUND: 4, Axes.CH: 3, Axes.ZPLANE:5})`
`stack.sel_by_physical_coords({Coordinates.X: (4.2, 5)})`

If a user wants to crop the image to 5x5 pixels they would still use sel:
`stack.sel({Axes.X: (0, 5), Axes.Y: (0, 5)})`

If a user wanted to sel on physical Z coords they would use the new method:
`stack.sel_by_physical_coords({Coordinates.Z: (2.2)})`

**Option 2:**
We modify the sel method to accept both physical coords and axes. 
If a user wanted to select on this xarray round: 4, ch: 3, zplane: 5, and x in 4.2 to 5 physical space they would do so  like this:
`stack.sel({Axes.ROUND: 4, Axes.CH: 3, Axes.ZPLANE:5, Coordinates.X: (4.2, 5)})`

In this option if a user provides entries for both Axes.X and Coordinates.X we throw an error. 

If a user wants to crop the image to 5x5 pixels they would still use sel but with the Axes names:
`stack.sel({Axes.X: (0, 5), Axes.Y: (0, 5)})`

If a user wanted to sel on physical Z coords they would still use sel but with Coodinates.Z as the indexer name:
`stack.sel({Coordinates.Z: (2.2)})`

With either of these options we can also expose the helper method that converts physical coordinates to their corresponding pixel values.  

### Scenario 2
Because x and y are currently unlabeled dimensions on our xarray object we have an opportunity to refactor their physical coordinates to be the labels. This does not work with z however because we currently store the name of each zplane as the label of the z dimension. If we wanted to do this refactor we have two options for handling z. 

**Option 1**: Maintain the zc namespace but refactor x and y physical coordinates. If we do this our previous xarray would now look like this:

```
<xarray.DataArray (r: 3, c: 2, z: 3, y: 10, x: 10)>
array([[[[[1., ..., 1.],
         ...,
          [1., ..., 1.]]]]], dtype=float32)
Coordinates:
  * r        (r) int64 4, 3, 6
  * c        (c) int64 2, 3, 4
  * z        (z) int64 5 6 8
  * x       (x) float64 1.0 1.111 1.222 1.333 1.444 1.556 1.667 1.778 1.889 2.0
  * y       (y) float64 4.0 4.222 4.444 4.667 4.889 5.111 5.333 5.556 5.778 6.0
    zc       (z) float64 2.2  3.1  4.5
```
If a user wanted to select on this xarray round: 4, ch: 3, zplane: 5, and x in 4.2 to 5 physical space they would do so like this:
`stack.sel({Axes.ROUND: 4, Axes.CH: 3, Axes.ZPLANE:5, Axes.X: (4.2, 5)})`

If a user wants to crop the image to 5x5 pixels they would use isel (xarray's positional indexing method):
`stack.isel({Axes.X: (0, 5), Axes.Y: (0, 5)})`

If a user wanted to sel on physical Z coords we would have to create a special method to do so:
`stack.sel_by_z_coords({Coordinates.Z: (2.2)})`

**Option 2**: Get rid of label information about zplanes and replace with physical coordinate information.  If we do this our previous xarray would now look like this:
```
<xarray.DataArray (r: 3, c: 2, z: 3, y: 10, x: 10)>
array([[[[[1., ..., 1.],
         ...,
          [1., ..., 1.]]]]], dtype=float32)
Coordinates:
  * r        (r) int64 4, 3, 6
  * c        (c) int64 2, 3, 4
  * z        (z) int64 2.2  3.1  4.5
  * x       (x) float64 1.0 1.111 1.222 1.333 1.444 1.556 1.667 1.778 1.889 2.0
  * y       (y) float64 4.0 4.222 4.444 4.667 4.889 5.111 5.333 5.556 5.778 6.0
```
If a user wanted to select on this xarray round: 4, ch: 3, zplane: 5, and x in 4.2 to 5 physical space they would first have to do some calculating to find out what physical coordinate corresponds to zplane 5 and then sel on that value like this: 
`stack.sel({Axes.ROUND: 4, Axes.CH: 3, Axes.ZPLANE: CALULATED_PHYSICAL_VAL, Axes.X: (4.2, 5)})`

If a user wants to crop the image to 5x5 pixels they would use isel:
`stack.isel({Axes.X: (0, 5), Axes.Y: (0, 5)})`

I think both scenarios have their pros and cons so curious for feedback.

Another thing to note is that the physical coords in the IntesityTable are named xc/yc/zc and there are no plans on changing that.

**Comment by joshmoore** [comment]
My overly simplistic understanding of the background here was that this works around an issue with xarray. Is there anything on the xarray roadmap that would either suggest one of the options above or alleviate the root problem?

**Comment by shanaxel42** [comment]
> My overly simplistic understanding of the background here was that this works around an issue with xarray. Is there anything on the xarray roadmap that would either suggest one of the options above or alleviate the root problem?

Things would be slightly easier if xarray allowed you to have multiple multi-index labels per one dimension, but it still wouldn't solve all out problems. We'd still have to decide between keeping xc/yc/zc, or refactoring to just x/y lables and then what to do about z. Right now I think this issue is mostly around how we want to structure our data.

**Comment by njmei** [comment]
http://xarray.pydata.org/en/stable/data-structures.html#multiindex-coordinates

Naive question, doesn't xarray support multi-indexing though? Or is this referring to something else?

**Comment by njmei** [comment]
This is my naive opinion and I would defer to @berl regarding this but I think:

```
<xarray.DataArray (r: 3, c: 2, z: 3, y: 10, x: 10)>
Coordinates:
  * r        (r) int64 4, 3, 6
  * c        (c) int64 2, 3, 4
  * x        (x) int64 0, 1, 2, ... 9
  * y        (y) int64 0, 1, 2, ... 9
  * z        (z) int64 5 6 8
    xc       (x) float64 1.0 1.111 1.222 1.333 1.444 1.556 1.667 1.778 1.889 2.0
    yc       (y) float64 4.0 4.222 4.444 4.667 4.889 5.111 5.333 5.556 5.778 6.0
    zc       (z) float64 2.2  3.1  4.5
Data variables:
  intensity    (r, c, x, y, z) float32 1.0, ...
```

To make things straightforward, I think that indexing should *only* be possible with logical coordinates. But you should provide functions/methods that would allow people to convert from real physical coordinates to logical coordinates (and possibly vice-versa).

**Comment by ambrosejcarr** [comment]
Huh, you know, I think @njmei could be right about multiindices...

```python
In [20]: x = pd.Index(list('abc'))
In [21]: y = pd.Index(list('def'))
In [22]: mi = pd.MultiIndex.from_arrays([x, y])
In [23]: xr.DataArray([9, 8, 7], coords={'test': mi}, dims=['test'])                                                              
Out[23]: 
<xarray.DataArray (test: 3)>
array([9, 8, 7])
Coordinates:
  * test          (test) MultiIndex
  - test_level_0  (test) object 'a' 'b' 'c'
  - test_level_1  (test) object 'd' 'e' 'f'

In [24]: test = xr.DataArray([9, 8, 7], coords={'test': mi}, dims=['test'])                                                       

In [25]: test.sel(test_level_0='a')                                                                                               
Out[25]: 
<xarray.DataArray (test_level_1: 1)>
array([9])
Coordinates:
  * test_level_1  (test_level_1) object 'd'
```

**Comment by njmei** [comment]
cool! Then x, y, and z could be `MultiIndex` types then with logical coordinates as the first level and physical coordinates as the second level?

**Comment by ambrosejcarr** [comment]
On the surface, this seems like it should be possible. @shanaxel42 may want to dig in a bit more before committing to anything.

**Comment by shanaxel42** [comment]
ok @njmei is definitely right about being able to set coords as a pd.MulitIndex! But after trying this out there's a few issues. It appears that MultiIndicies don't work well with floats
```
>>> x = pd.Index(np.random.rand(3))
>>> y = pd.Index(list('def'))
>>> mi = pd.MultiIndex.from_arrays([x, y], names=('x', 'y'))
>>> mi
MultiIndex(levels=[[0.08879851684435991, 0.32765777001795915, 0.5679359917955789], ['d', 'e', 'f']],
           codes=[[1, 0, 2], [0, 1, 2]],
           names=['x', 'y'])
>>> test = xr.DataArray([9, 8, 7], coords={'test': mi}, dims=['test'])
>>> test
<xarray.DataArray (test: 3)>
array([9, 8, 7])
Coordinates:
  * test     (test) MultiIndex
  - x        (test) float64 0.3277 0.0888 0.5679
  - y        (test) object 'd' 'e' 'f'
>>> test.sel(y='d')
<xarray.DataArray (x: 1)>
array([9])
Coordinates:
  * x        (x) float64 0.3277
>>> test.sel(x=0.3277)
Traceback (most recent call last):
  File "/Users/shannonaxelrod/dev/starfish/.venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2656, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 382, in pandas._libs.hashtable.Float64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 388, in pandas._libs.hashtable.Float64HashTable.get_item
KeyError: 0.3277
```

Also if we were to set each dimension's coords to a MulitIndex they become 'virtual coords' and we lose some of the xarray coord functionality 
```
For convenience multi-index levels are directly accessible as “virtual” or “derived” coordinates (marked by - when printing a dataset or data array):

Unlike other coordinates, “virtual” level coordinates are not stored in the coords attribute of DataArray and Dataset objects (although they are shown when printing the coords attribute). Consequently, most of the coordinates related methods don’t apply for them. It also can’t be used to replace one particular level.
```

But then the biggest issue this has uncovered for me is that xarray's sel method only allows you to use the `method='nearest'` flag on single values and not slices. So our use case of wanting to sel on a range of physical coords that might not match exactly the labels of the dimension doesn't work to well. So in this case I think it makes the most sense to not have the physical coords be labels of their own dimension but instead to keep them as these separate xc/zc/yz arrays where the process of indexing by them is `first look up the closest positional index to the physical value or range, then sel on that positional index` This is Scenario 1, Option 1: branch here https://github.com/spacetx/starfish/compare/saxelrod-multiple-sel?expand=1
