### ISSUE TITLE
Reduce size of STARmap test data and run example in CI

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1154]
Currently the example is too large to run on travis. 
* Reduce the data size
* Add assertions about the output
* Re-enable the travis test

**Comment by njmei** [comment]
It might be worthwhile to have a separate set of tests that use a full data set to ensure that starfish will be able to handle 'real' workloads and not accidentally get overoptimized to only work 'well' with smaller test cases.

**Comment by ambrosejcarr** [comment]
I think we're hoping to take the opposite tactic whereby we increase the ability to chunk, parallelize, and execute on larger and larger datasets while the "unit of processing" stays about laptop-sized (@ttung can correct me if I'm wrong). 

However, separately, I think we will probably end up doing what you request in this instance because it's the pattern we've been following -- the existing data will be available under `use_test_data=False`, and will come with a warning like "Hey, this data is big, hope you've got a workstation..."
