### ISSUE TITLE
Automatic generation of documentation

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1162]
Starfish documentation needs to accomplish a few things: 

1. It needs to demonstrate to users clearly and succinctly how and why to use starfish, and users need to be able to take those examples and run and adjust them to help them bootstrap their use of starfish. 
2. Starfish is solving a visual problem, so to communicate its value, the documentation must contain rendered outputs (both print statements and plots)
3. Code example need to be tested, to make sure that when users download the examples, they run
4. Examples in the documentation should be easy to track and refactor so that they don't make it difficult to add new features or change existing ones. 
5. It's important that users be able to interact with our examples using Jupyter notebooks, since the community expects that. 

At minimum, the existing notebooks should be available, with rendered outputs, by the hackathon. If the long term solution can't be delivered by the hackathon, we should come up with a short term one that is deliverable quickly. 

What should our solution look like to accomplish this?

cc @ttung @kne42 @shanaxel42 @dganguli

**Comment by dganguli** [comment]
i completely agree. to add a bit more color, i see two main users of the docs: 1. spacejam attendees and 2. non-spacejam attendees who are evaluating whether or not starfish suits them. i think we prioritize each user type in that order. below, for each user type, i further offer a prioritization of how to write the docs.

**spacejam users**

1. notebooks that work. why? we expect attendees to run these notebooks to verify that they are working for them as expected. we also expect them to tweak the parameters of these notebooks to on their own data to start producing pipeline recipes.

2. clean api docs. why? if users want to swap out a pipeline component in their pipeline for another one, they need to know what their options are and how to use them.

**non-spacejam attendees that are evaluating whether spacejam is for them.**

1. rendered notebooks that are linked to in the readme, preferably in the starfish repo. these notebooks should also run. why? when evaluating an image processing library, it's very valuable to see, visually, what it can do! especially if it works for many different assay types! see scVI, a popular single cell repo (https://github.com/YosefLab/scVI), that i think does this perfectly.

2. sphinx gallery documentation that shows, visually, how to use filters, spot detection algorithms, decoding, etc. essentially following the strategy outlined here: https://github.com/spacetx/starfish/issues/858

for the purposes of spacejam, if we don't get to the latter two, that's OK! in fact, i think it's worth not even attempting the latter two.

**Comment by neuromusic** [comment]
for spacejam attendees, I would also add:

3. clear descriptions of output formats. why? so that WG4 & WG5 can load starfish outputs into their analyses.
