### ISSUE TITLE
max_proj does weird things to physical coordinates

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1214]
Reproduce: run the ISS.ipynb file, but really you just need to max proj the starfish.data.ISS() nuclei image. 

![image](https://user-images.githubusercontent.com/5239152/56335809-0503ad00-616c-11e9-9666-bdb80cc5781e.png)

**Comment by ttung** [comment]
@ambrosejcarr @shanaxel42 -- what's the state of this?
