### ISSUE TITLE
Clip does weird things to seqfish data

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1261]
![image](https://user-images.githubusercontent.com/5239152/56699749-ada19780-66ab-11e9-80d3-8fb1b147ce3b.png)

**Comment by shanaxel42** [comment]
@ambrosejcarr this is just a warning, the actual clipping still successfully returns. Still want me to investigate?

**Comment by ambrosejcarr** [comment]
Yeah, it makes all the values Nan. Sorry for the lack of detail in the issue.
