### ISSUE TITLE
Blob Decoding Breaks with zero spots

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1262]
Can reproduce on ISS first fov of iss data here https://d2nhj9g34unfro.cloudfront.net/xiaoyan_qian/ISS_human_HCA_07_MultiFOV/main_files/experiment.json

**Comment by ambrosejcarr** [comment]
Decoding by per-round max is breaking when a zero-length table is sent in for decoding. We need tests!

**Comment by ambrosejcarr** [comment]
Fixed by #1271
