### ISSUE TITLE
Cannot do ImageStack.{transform,apply} after ImageStack.{sel,isel}

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#1268]
The resulting ImageStack takes a reference to the backing MPDataArray.  When we pass the MPDataArray to the child processes, we reshape the raw byte buffer to the shape of the resulting ImageStack.  However, the MPDataArray is sized to reflect the original ImageStack's size, and so the reshape operation fails.

**Comment by ambrosejcarr** [comment]
in-place operations _also_ fail after `.sel` and `.isel`

**Comment by ttung** [comment]
That does not surprise me.
