### ISSUE TITLE
Missing links (or wrong links) to source code for individual image manipulation functions

### ISSUE THREAD

**Issue by njmei** [spacetx/starfish#1269]
1) It would be really nice to have links to source code (even if for thin wrappers)

Examples where this would matter:
https://spacetx-starfish.readthedocs.io/en/latest/api/image/index.html?highlight=iterate%20over%20axes#starfish.image.Filter.DeconvolvePSF

2) Some functions that do have links to source code appear to be pointing to the base class...

https://spacetx-starfish.readthedocs.io/en/latest/_modules/starfish/core/image/_registration/_learn_transform/_base.html#LearnTransform

**Comment by neuromusic** [comment]
Thanks for the suggestion @njmei and to @mattcai for looking into this...

> for adding source code links, there are no config values for `sphinx.ext.viewcode`. So the only way to add source links for module docs in `image`, `morphology`, and `spots` is to explicitly list every module. That's not a big lift for now, but it means any future module additions will need to be manually added to api docs.

Since we can't automate it well given the starfish architecture, I'm going to close this issue.
