### ISSUE TITLE
[Docs] Doc search results return invalid urls

### ISSUE THREAD

**Issue by njmei** [spacetx/starfish#1270]
Example search:
https://spacetx-starfish.readthedocs.io/en/latest/search.html?q=clip&check_keywords=yes&area=default

Example invalid url results:
https://spacetx-starfish.readthedocs.io/en/latest/_modules/starfish/image/_filter/clip.html?highlight=clip

https://spacetx-starfish.readthedocs.io/en/latest/_modules/starfish/image/_filter/richardson_lucy_deconvolution.html?highlight=clip

**Comment by neuromusic** [comment]
This appears to be fixed. Closing.
