### ISSUE TITLE
Intuitive SpaceTx format conversion tools

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1286]
Getting data into SpaceTx format is a barrier for new users, and our existing tooling was unintuitive to them. We will need to develop (TileFetcher) or collaborate to build (Bio-Formats) easier-to-use tooling. 

Some ideas floated by wranglers @hewgreen and @zperova included functional tooling wrapping `TileFetcher` that accepts config including a regex for the file naming conventions and a standardized format containing the physical coordinates and codebook (probably .csv or .tsv, to be user friendly).

We would probably want to auto-detect the image file type.

**Comment by shanaxel42** [comment]
closing, repeat of #1318
