### ISSUE TITLE
osmFISH complete data set does not load

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#1294]
It is made of float64 numpy tiles, and has data outside of (0,1).

@ambrosejcarr @dganguli who converted this data set?  can we figure out a good way to fix this?

**Comment by neuromusic** [comment]
@ambrosejcarr will point @ttung to the raw data

**Comment by ttung** [comment]
@ambrosejcarr can you assign this to me once you link me the data?  kthx.

**Comment by ambrosejcarr** [comment]
@ttung I've tried to record the provenance in the tile fetchers whenever possible: 

https://github.com/spacetx/starfish/blob/master/docs/source/_static/data_formatting_examples/format_osmfish.py#L197

**Comment by ttung** [comment]
Ideally, we should record the provenance in the formatted data. :)

**Comment by kevinyamauchi** [comment]
@JennyVoPhamhi and I are hoping to use the osmFISH data set for some of our work. I chatted with @ambrosejcarr and @shanaxel42 today and it sounds like it's still a work in progress. We understand you have a lot in the queue, I just wanted to make a note here that we'd be psyched to use the data once it's ready!
