### ISSUE TITLE
Add support for other types of projections on ImageStack

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#1302]
# Proposal
I think it would be useful to expose other methods of projecting along axes for `ImageStack` (e.g., `DataArray.sum()` and `DataArray.mean()`). This would add support the ExFISH case for projecting across (R, C) before spot segmentation (#1301).

# Implementation
Some possibilities:
1. I think the thing that is the least work is to make a filter, `Filter.Project` that takes projection type as an input argument. This could replace `Filter.MaxProject`.
2. We could do the same as (1), but make it a method of `ImageStack`. I think a lot of the notebooks would have to be updated, as they use `ImageStack.max_proj()`.
3. We could also make one filter component per projection type, but this seems too granular.

As a related aside: I think there should be only one way to max project (i.e., `ImageStack.max_proj()` and `Filter.MaxProject` are redundant).

Thoughts, @dganguli , @ambrosejcarr ?

**Comment by ttung** [comment]
For reasons of API stability, we should not remove `Filter.MaxProject` for a number of releases after we implement `Filter.Reduce`.

`ImageStack.max_proj()` should be a hidden method, IMO.

**Comment by kevinyamauchi** [comment]
@ttung, is `Filter.Reduce` a planned component or a proposed name for this component?

**Comment by ttung** [comment]
I'm proposing it. :)

**Comment by kevinyamauchi** [comment]
Sounds good, @ttung . I took a crack at it in #1342. I still need to add tests, but feel free to check it out if you're curious.
