### ISSUE TITLE
PixelSpotDecoding  too slow

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1312]
![image](https://user-images.githubusercontent.com/6810854/57240597-b6676700-6fe3-11e9-89fe-4c9d729dbb8d.png)

The slowdown comes from the skimage.regionprops.centroid call on each spot found

possible fix proposed by @dganguli is too "swap that out with a pure numpy call based on the bbox" although some research needs to be down on how accurate this would be in relation to the intensities. 

This also highlights a larger problem in that we need to do some Benchmarking memory and cpu processing for all decoding and detecting to see how things are going to work at scale

Should be as fast blobDetector on SeqFish test dataset

**Comment by dganguli** [comment]
@shanaxel42 this issue is related to #1283. I vote maybe closing #1283 in favor of this one? Alternative can merge #1283 in here, with a simple statement that we should better profile this part of the codebase.

**Comment by shanaxel42** [comment]
> @shanaxel42 this issue is related to #1283. I vote maybe closing #1283 in favor of this one? Alternative can merge #1283 in here, with a simple statement that we should better profile this part of the codebase.

 I'm down with this, I'll close out #1283. and add some info here
