### ISSUE TITLE
Create organized starfish.spacetx bucket 

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1314]
We need to define how we want to organize both the published datasets @dganguli will be working with. And the spaceTX datasets and results for the benchmarking.

**Comment by ambrosejcarr** [comment]
I think #1287 is relevant to the discussion of the formatted/raw separation.

**Comment by ttung** [comment]
My proposal:

Top level: A list of datasets.  NOT ASSAYS.
Second level: {raw, spacetx-formatted, outputs}.
Each second-level folder has timestamped folders.

**Comment by ambrosejcarr** [comment]
Makes sense. Do we want a naming convention for the datasets? What information should be encoded in the name? 

Hoping to avoid things like: 
```
ISS_1
ISS_ambrose
ISS_deep
...
```

**Comment by ttung** [comment]
I would say something more about the tissue type and chemistry?

**Comment by shanaxel42** [comment]
proposal!
`starfish
    published
        assays
            datasets (some sort of schema for naming tissue type and chemistry)
                raw
                formatted
                    date
                        experiment.json
                processed
                    date
                        decoded.csv (or whatever)
    unpublished
        assays
            datasets (some sort of schema for naming tissue type and chemistry)
                raw
                formatted
                    date
                        experiment.json
                processed
                    date
                        decoded.csv (or whatever)
    spaceTX
        assays
            datasets (some sort of schema for naming tissue type and chemistry)
                raw
                formatted
                    date
                        experiment.json
                processed
                    date
                        decoded.csv (or whatever)`

**Comment by ttung** [comment]
I'm generally supportive of this approach.

What's with the top-level starfish thing?

**Comment by shanaxel42** [comment]
> What's with the top-level starfish thing?

oh thats just whatever the top level is so I guess now its `starfish.data.public` but could be whatever I don't really have a preference for that

**Comment by ambrosejcarr** [comment]
I am downloading some slide-seq data to work with. Based on the above proposal, I intend to put it in: 

`starfish.data.public/published/rodriques_science_2019_slide-seq_perkinje-cerebellum/20190605/<data>`

The "datasets" corresponds to `<first-author-last-name>_<science>_<year>_<assay_type>_<tissue-type>`

How does this sound for the "datasets" schema?

**Comment by shanaxel42** [comment]
scheme sounds fine but it should go in `starfish.data.published`, not `starfish.data.public`, the former is the new bucket

**Comment by shanaxel42** [comment]
starfish.data.spacetx/ now contains all the current spaceTX data and results we have in an organized structure. The structure as well as the commands I used to copy the datasets from their original locations is described here 
```
ISS_30
		mouse		

			formatted: https://console.aws.amazon.com/s3/buckets/spacetx.starfish.data.upload/xiaoyan_qian/
						ISS_mouse_HCA_07_MultiFOV/?region=us-east-1&tab=overview

						aws --profile spacetx-admin s3 sync s3://spacetx.starfish.data.upload/xiaoyan_qian/ISS_mouse_HCA_07_MultiFOV/ s3://starfish.data.spacetx/ISS_30/mouse/formatted/


		human

			formatted: https://console.aws.amazon.com/s3/buckets/spacetx.starfish.data.upload/xiaoyan_qian/ISS_human_HCA_07_MultiFOV/
						main_files/?region=us-east-1&tab=overview

			
			starish results: 
				aws --profile spacetx-admin s3 sync  --exclude "*" --include "*iss_spacetx_*" s3://spacetx.starfish.data.public/xiaoyan_qian/ISS_human_HCA_07_MultiFOV/ s3://starfish.data.spacetx/ISS_30/human/starfish_results/


	ISS_120 
		mouse		

			formatted: https://console.aws.amazon.com/s3/object/spacetx.starfish.data.upload/xiaoyan_qian/
						ISS_m_brain_03/README.txt?region=us-east-1&tab=overview

						aws --profile spacetx-admin s3 sync s3://spacetx.starfish.data.upload/xiaoyan_qian/ISS_m_brain_03/ s3://starfish.data.spacetx/ISS_120/mouse/formatted/

		human

			formatted: https://console.aws.amazon.com/s3/buckets/spacetx.starfish.data.upload/xiaoyan_qian/	
						ISS_h_brain_03/?region=us-east-1&tab=overview

						aws --profile spacetx-admin s3 sync s3://spacetx.starfish.data.upload/xiaoyan_qian/ISS_h_brain_03/ s3://starfish.data.spacetx/ISS_120/human/formatted/




	TODO: email about contributer resulsts??????????

FISSEQ
	mouse: 
		contributer results: spacetx.starfish.data.upload/samuel_inverso/20181203-mouse-71

		aws --profile spacetx-admin s3 sync s3://spacetx.starfish.data.upload/samuel_inverso/20181203-mouse-71/ s3://starfish.data.spacetx/FISSEQ/mouse/contributer_results/


BaristaSEQ: 
	mouse:  
		formatted: 
			https://console.aws.amazon.com/s3/buckets/spacetx.starfish.data.public/browse/formatted/20190319/baristaseq/?region=us-east-1&tab=overview

			aws --profile spacetx-admin s3 sync s3://spacetx.starfish.data.public/browse/formatted/20190319/baristaseq/ s3://starfish.data.spacetx/BaristaSEQ/mouse/formatted/

		contributer results: 
			https://console.aws.amazon.com/s3/object/spacetx.starfish.data.upload/xiaoyin_chen/resultsandcode.zip?region=us-east-1&tab=overview

			aws --profile spacetx-admin s3 sync  --exclude "*" --include "*resultsandcode.zip*" s3://spacetx.starfish.data.upload/xiaoyin_chen/ s3://starfish.data.spacetx/BaristaSEQ/mouse/contributer_results



	
seqFISH
	mouse:
		formatted_mulitplexed: 
			https://console.aws.amazon.com/s3/buckets/spacetx.starfish.data.upload/nico_pierson/multiplexed/

			aws --profile spacetx-admin s3 sync s3://starfish.data.spacetx/SeqFISH/mouse/formatted/ s3://starfish.data.spacetx/SeqFISH/mouse/formatted_multiplexed/

		formatted_sequential:
			spacetx.starfish.data.upload/nico_pierson/sequential/

			aws --profile spacetx-admin s3 sync s3://spacetx.starfish.data.upload/nico_pierson/sequential/ s3://starfish.data.spacetx/SeqFISH/mouse/formatted_sequential/


		contributer_results_mulitplexed: 
			spacetx.starfish.data.upload/nico_pierson/multiplexed/output/

			aws --profile spacetx-admin s3 sync s3://starfish.data.spacetx/SeqFISH/mouse/contributer_results/ s3://starfish.data.spacetx/SeqFISH/mouse/contributer_results_multiplexed/ 

smFISH
	mouse: 
		formatted:
			https://console.aws.amazon.com/s3/buckets/starfish.data.spacetx/smFISH/mouse/formatted/20190214/?region=us-east-1&tab=overview

			aws --profile spacetx-admin s3 sync s3://starfish.data.spacetx/smFISH/mouse/formatted/20190214/ s3://starfish.data.spacetx/smFISH/mouse/formatted/


spatial transcriptomics
	mouse: 
		formatted:
			Ambrose TODO
```
