### ISSUE TITLE
seqFISH: data conversion into SpaceTx format 

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1317]
I have an issue with the part of conversion of my data into space TX format. I am using spacetx writer but it is not clear how to add auxiliary images like NUCLEI that must be separated from primary ones and how to write a custom codebook.csv for the conversion into codebook.json. I think it could be easier for a user to have some data example (raw and formatted ) for seqFISH.

**Comment by ttung** [comment]
There's an example of how to include nuclei images in the [BaristaSeq data conversion example](https://spacetx-starfish.readthedocs.io/en/latest/usage/data_formatting_examples/format_baristaseq.html#sphx-glr-usage-data-formatting-examples-format-baristaseq-py).

Here's an example of a [seqfish codebook csv](https://d2nhj9g34unfro.cloudfront.net/browse/raw/seqfish/2017-08-23-10k-gene-barcodes%20round%20I%20to%20V.csv)
