### ISSUE TITLE
Formatting tool for user friendly converting to spaceTX format

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1318]
- [ ] Define file name convention

- [ ] Have tile fetcher example that works with above convention

- [ ] Document in readthedocs

**Comment by ttung** [comment]
Proposal:

files are to be named:

<image_type>-f<fov_number>-r<round_number>-c<ch_number>-z<zplane_number>.<image_extension>

image_type is like primary, dots, etc.
*_number: self explanatory
image_extension: has to be one of the supported image extensions, case insensitive

coordinates are to be read from a specified csv file, where the columns are filename, xmin, xmax, ymin, ymax, zmin, zmax.

images where num_zplanes==1 should declare num_zplane to be any value they desire, and assign NaN to the z coordinates.

**Comment by ttung** [comment]
codebook is still the hardest part of this, IMO...

**Comment by ambrosejcarr** [comment]
There are a few formalisms for codebooks that we might want to support conversion from:

csv where each row is `<gene>,ACCGTC` where each nucleotide is taken to be a sequential round, and a mapping is provided from nucleotide to channel. 

csv where each row is `gene,0010134` where each number represents a sequential round, and the numbers are taken to be the channels.

**Comment by ambrosejcarr** [comment]
I don't have a good solution for codebooks that aren't 1-hot. Fortunately 1-hot appears to be very common.

**Comment by ttung** [comment]
I would prefer just doing:

```
<target>,r0_c0, r0_c1, ...,  rn_cn
SCUBE2,0,1, ..., 0
```

**Comment by neuromusic** [comment]
@ttung so each column defines a coordinate?

I would find the tidy version more intuitive, where each row corresponds to a single value in the codebook...

```
target,round,channel,value
SCUBE2,0,0,1
SCUBE2,0,1,1
BRCA,0,0,1
BRCA,1,1,1
ACTB,0,1,1
ACTB,1,0,1
```

the xarray `to_dataframe()` method would return the data formatted like this (except with zero values, as well). see http://xarray.pydata.org/en/stable/pandas.html#dataset-and-dataframe

**Comment by neuromusic** [comment]
example roundtrip from codebook to csv and back (technically to xarray on the return) https://gist.github.com/neuromusic/87267d7e20279585517c8cd46a0c5601

**Comment by ttung** [comment]
> so each column defines a coordinate?

correct.  for one-hot encodings, it's very easy to sanity check (sums across rows or columns should always be 1)

> I would find the tidy version more intuitive, where each row corresponds to a single value in the codebook...

that's a lot more "rows".  riskier to get it wrong, potentially?  not sure.
