### ISSUE TITLE
Define a way in which to link output of processed experiments to SpaceTX format 

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1319]

**Comment by ttung** [comment]
I don't understand what this issue is about. :(

**Comment by joshmoore** [comment]
I'm likely partially to blame. There are other uses, but this began around the possibility of having a single call to:

```
starfish validate experiment.json # or results.json
```

which validates the entire tree. I was thinking:

```
  experiment
  |_ codebook
  |_ fields_of_view
  |_ results
```

Elsewhere you've mentioned the immutability, which might suggest:

```
 processed
 |_ experiment
     |_ codebook
     |_ fields_of_view
```
