### ISSUE TITLE
Improvements to image segmentation

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1321]
# Objective
*As a computational biologist analyzing imaging data containing cells, I want starfish to implement the tools that I use in my own workflow to segment cells so that starfish can provide end-to-end processing of my data and I can make use of starfish's output formats and visualization capabilities. Starfish must implement these in a way that I can understand and use without assistance from developers*

## Acceptance Criteria
* Refactor watershed segmentation to be more intuitive, watershed supports 3d images.
* Starfish can build a representation of cellular regions from FIJI ROIsets (enables manual segmentation) (#1370)
* Starfish can apply a pre-trained Ilastik model to segment images in SpaceTx Format
* Starfish implements an object model whose contracts fit these features.
* SegmentationMaskCollection can be queried will a cell_id to return a specified mask (#1487)
* Starfish has adequate user-facing documentation that our users can leverage segmentation without developer assistance
* Segmentation methods respond in interpretable ways when no cells are identified (#468)

## Validation
* Test that users (including WG5) can successfully use starfish methods. 

## Out of scope
* Reconciling segmentation artifacts at image boundaries (future work)

## Additional Notes

*Note: you must have the [zenhub chrome extension](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US) installed to see the issues linked to this Epic.*

**Comment by ambrosejcarr** [comment]
Watershed work will enable 3d support per #53

**Comment by pdichiaro** [comment]
it is challenging to segment different cell types in the same image. I am wondering if it is possible to create a segmentation mask using different segmentation methods. For example an user wants to use watershed segmentation with a membrane staining to create automatically a mask. Then he wants to refine it manually in those aereas where the cell segnentation was not so accurate.

**Comment by ambrosejcarr** [comment]
Hi @pdichiaro, This is a *great* question. 

On the question of automated mask generation, we want to provide examples of how to improve the inputs to watershed that might help with different cell sizes. @dganguli was telling me about approaches where watershed basins were built based on the kernel density of the decoded points, which should be sensitive to cell size, and could reduce the need to refine the segmentation. 

If interactive refinement is still necessary, it might be smoother to read the masks into [napari](https://github.com/napari/napari), and extend `starfish.display` to enable mask editing. @sofroniewn , am I correct that napari already enables editing of the shape layer?

**Comment by pdichiaro** [comment]
Hi @ambrosejcarr, it is a really great approach. For some situations (for example proliferating tumor) I think it is necessary to load the mask on starfish.dispaly and to edit it.

**Comment by sofroniewn** [comment]
Editing the labels layer is possible right now as long as the data isn't so big that it turns into a pyramid. we can support editing pyramid labels data at some point if this is necessary.

we'd probably need to add a custom keybinding to starfish display that would "save" the new edited labels in some way you wanted though

**Comment by ttung** [comment]
I believe this is done.
