### ISSUE TITLE
expose more options for watershed segmentation

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#1324]
from @dganguli :

skimage allows multiple parameterizations of the watershed algorithm that we wrap. of relevance: the image, markers, and a mask

https://scikit-image.org/docs/dev/api/skimage.segmentation.html?highlight=watershed#skimage.segmentation.watershed

For our usage of this wrapper, we typically set the image as either a stain for all RNA molecules or a max projection of the images. Often these images are blurred to acheive better segmentation results. Markers tend to be either the DAPI image or a thresholded version of DAPI. Our current implementation masks anything pixels that have neither DAPI or spots.

We currently are opinionated about how to perform these steps, but some users want to perform segmentation differently.

We should expose other options for defining markers and masks to users through our watershed API.

**Comment by ambrosejcarr** [comment]
There is some good information on fixing over-segmentation in #998 from @sethb3744
