### ISSUE TITLE
Add author attributions to docstrings for functions in `starfish.data`

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#1331]
- [ ] MERFISH
- [ ] allen_smFISH
- [ ] DARTFISH
- [ ] ISS
- [ ] osmFISH
- [ ] BaristaSeq
- [x] ImagingMassCytometry
- [ ] SeqFISH
- [ ] STARmap

**Comment by shanaxel42** [comment]
If not published and not part of spaceTX list person who gave data. If part of spaceTX do this and acknowledge spaceTX

**Comment by ttung** [comment]
Isn't this done, @ambrosejcarr?

**Comment by ambrosejcarr** [comment]
Yes.
