### ISSUE TITLE
verify physical coordinates are consistent throughout spot finding 

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#1332]
1. Document the implications.
2. Transferring physical coordinates to the intensity table should work for the last row/column of pixels.

**Comment by ttung** [comment]
`transfer_physical_coords_from_imagestack_to_intensity_table` is probably also affected.

**Comment by ttung** [comment]
1. if you have a pixel range of (0, 4), corresponding to physical coordinates of (0.0, 0.4), the actual valid range for centroids is (0, 4.9999..).  `interp` will break (return NaN, I believe) if you exceed the range of the original source.  Possible solution: extend the pixel->physical coordinates array by one element; in this case, (0, 5), and `interp` in that range.

2. when a third-party library reports (1, 1) as the pixel coordinates of a spot's centroid, does that mean the centroid is in the top-left corner of the pixel in the 2nd column, 2nd row?

**Comment by ttung** [comment]
@shanaxel42 and I had a long conversation about this today, and we think there are basically two options:

# Example:
- 5x5 image
- center pixel is lit
- physical (xmin, xmax) is (0, 10)

# Option 1
## Rules
- Pixel's origin (0, 0) is at the center of a pixel
- A tile's physical min coordinate is the left/top extent of the tile, and the physical max coordinate is the right/bottom of the tile.

## Implications
- Spot finding output is correct (a 5x5 image with the center pixel lit would have its centroid called as (2, 2).
- Plotting the centroid makes sense (matplotlib plots (2, 2) as the absolute center of the 5x5 image).
- The physical coordinates in the xarray will be based on the physical coordinates of the pixel's center, and thus are somewhat surprising.  The top-left pixel in the 5x5 image will be assigned physical coordinates (1, 1), instead of (0, 0).  The bottom-right pixel in the 5x5 image will be assigned physical coordinates (9, 9) instead of (10, 10).
- Valid pixel coordinate range in the 5x5 example: (0, 5]
- Valid physical coordinate range in the 5x5 example: (0, 10)

## Doodle

![IMG_4335](https://user-images.githubusercontent.com/280924/60850763-9a2fa400-a1a5-11e9-968a-d7672903b7f9.jpg)


# Option 2
## Rules
- Pixel's origin (0, 0) is at the top-left of a pixel.
- A tile's physical min coordinate is the left/top extent of the tile, and the physical max coordinate is the top-left corner of the bottommost/rightmost pixel.

## Implications
- Spot finding output is offset by .5 pixels (a 5x5 image with the center pixel lit would have its centroid called as (2, 2).
- However, this is cancelled out by the -.5 pixel offset from our understanding of a pixel's center and matplotlib's understanding of a pixel's center, and as such, plotting the centroid mostly makes sense (the labels on the axes will not match though).
- The physical coordinates in the xarray will be based on the physical coordinates of the pixel's top-left corner, and are not surprising at all.  The top-left pixel in the 5x5 image will be assigned physical coordinates (0, 0).  The bottom-right pixel in the 5x5 image will be assigned physical coordinates (10, 10).
- Valid pixel coordinate range in the 5x5 example: (0, 6]
- Valid physical coordinate range in the 5x5 example: (0, 12.5]

## Doodle

![IMG_4336](https://user-images.githubusercontent.com/280924/60850772-a4ea3900-a1a5-11e9-976e-0ada1ce1b362.jpg)

**Comment by neuromusic** [comment]
Here's how ITK handles physical coordinates: 

![image](https://user-images.githubusercontent.com/1245615/60851353-7aee4200-a1b8-11e9-8e9c-9394ea46ee46.png)

/via https://simpleitk-prototype.readthedocs.io/en/latest/user_guide/plot_image.html

**Comment by ttung** [comment]
@neuromusic If I read this correctly, this is basically option 1.

**Comment by neuromusic** [comment]
@ttung basically, yes. the only piece I'm not sure about is whether the array in your doodle should be instantiated with `x_min, x_max = 0, 10` as in your assumptions or `x_min, x_max = 1, 9`, in which case x_min and x_max do not represent the full extent of the image, but the physical coordinates that correspond to the min and max pixel coordinates

**Comment by neuromusic** [comment]
I would expect to be able to call `min` on an xarray coordinate and get the same value that I passed in as the "min" when I instantiated it.

For example: 
``` Python
import xarray as xr
import numpy as np

min, max = 1, 9
n = 5

arr = xr.DataArray(
    np.random.rand(n, n),
    [('x', np.linspace(min,max,n)), 
     ('y', np.linspace(min,max,n))]
)

arr.x.min()
```

```
<xarray.DataArray 'x' ()>
array(1.)
```

**Comment by ttung** [comment]
> @ttung basically, yes. the only piece I'm not sure about is whether the array in your doodle should be instantiated with x_min, x_max = 0, 10 as you stated under "Example" or x_min, x_max = 1, 9. In the latter case, x_min and x_max do not represent the full extent of the image, but the physical coordinates that correspond to the min and max pixel coordinates.

Ah yes, this is your twitter question.

I ruled that particular option out because both @kevinyamauchi and @berl requested that x_max - x_min = pixel_size * n_pixels.

**Comment by neuromusic** [comment]
awesome. let's just make it clear in any documentation that these values represent the physical extent of the images, and NOT the min and max of the physical coordinates for the resulting xarray. I like your doodle... it makes this clear.

**Comment by ambrosejcarr** [comment]
> awesome. let's just make it clear in any documentation that these values represent the physical extent of the images, and NOT the min and max of the physical coordinates for the resulting xarray. I like your doodle... it makes this clear.

Basically, we need the doodle to be rewritten in illustrator and added to the documentation :-) 

I'm not as deep into the nuance of either option and don't have strong opinions about which we pick. If I'm understanding things correctly, our users want Option 2. Do we feel confident moving forward with that plan?

**Comment by ttung** [comment]
> I'm not as deep into the nuance of either option and don't have strong opinions about which we pick. If I'm understanding things correctly, our users want Option 2. Do we feel confident moving forward with that plan?

Originally, our users (as defined by @kevinyamauchi and @berl) wanted Option 2.  We didn't understand the implications until we spent some time exploring the issue, but I'm hoping that by making them explicit, we can make a reasoned choice.

**Comment by neuromusic** [comment]
This is an area where I think we should strive to conform with established standards in similar & associated tools.

When viewing the "Option 1" data with holoviews (which probably has the best support for visualizing xarray data), the labels are as expected:

![image](https://user-images.githubusercontent.com/1245615/60909715-94d56680-a244-11e9-9721-06275bbb0ca6.png)

**Comment by kevinyamauchi** [comment]
Thanks for all of this great discussion everyone! After the doodles and discussion, I now think Option 1 is the best path forward. I agree with @neuromusic that aligning with the established standards is a priority, as it makes the data easier to use the data with other tools and it is more intuitive for new users. Also, I like that `x_max - x_min = pixel_size * n_pixels`.

**Comment by shanaxel42** [comment]
@berl @njmei @kevinyamauchi sounds like we're settling on option 1, are we cool to proceed?

**Comment by shanaxel42** [comment]
We have chosen option 1! Work todo captured here #1459
