### ISSUE TITLE
`IntensityTable.concatenate_intensity_tables` seems oddly slow

### ISSUE THREAD

**Issue by njmei** [spacetx/starfish#1363]
Hi,

I tried merging `IntensityTable`s from a small test dataset with 3 FOVs (1 round, 3 fov, 3 ch, 37 z, 2048 y, 2048 x)

The 3 `IntensityTable`s have 1707, 1040, and 241 spots respectively. I can also provide netcdf'd versions of the tables if desired.

I did:
```
merged_decoded = IntensityTable.concatenate_intensity_tables([decoded_fov_000, decoded_fov_001, decoded_fov_002], overlap_strategy=OverlapStrategy.TAKE_MAX)
```

This somehow takes a wall time of ~3 minutes.

EDIT:
[decoded_intensity_table_netcdfs.tar.gz](https://github.com/spacetx/starfish/files/3193446/decoded_intensity_table_netcdfs.tar.gz)

**Comment by ttung** [comment]
Yeah, that does seem pretty bad.  tables would be really helpful.  cc: @shanaxel42

**Comment by shanaxel42** [comment]
`overlap_strategy=OverlapStrategy.TAKE_MAX` is doing a bit of computation so it makes sense it wouldn't be as fast as just a normal concat but that does seem especially slow. I can look
