### ISSUE TITLE
open .nc files

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1366]
After the spot detection I do not understand how to open files (.nc); I need to visually inspect images (I would be really great if it was possible to open them with Fiji) and outputs to know if spot detection method worked.

**Comment by ttung** [comment]
You can load them back as an IntensityTable (`IntensityTable.open_netcdf`) and use starfish.display to visualize the images and the spots (see https://spacetx-starfish.readthedocs.io/en/stable/getting_started/loading_data/index.html?highlight=display#visualizing-data)

**Comment by ttung** [comment]
Please let me know if this addresses your requirements.

**Comment by pdichiaro** [comment]
Can you give me a detailed example? 
I am following the instructions on this page: https://spacetx-starfish.readthedocs.io/en/stable/getting_started/loading_data/index.html?highlight=display#visualizing-data, but I do not understand if starfish.display(image) opens an interactively viewer or I have to define what image is. I usually use the CLI and I wonder if there is an easier way to open images and spots. For instance I used starfish filter DetectSpots with the parameter - -show but it did not open any images for the visually inspection(it created only .nc file).

**Comment by ttung** [comment]
Unfortunately, I don't think there is a way to visualize spots & images together using the CLI.  Would you be comfortable with a python solution?

**Comment by pdichiaro** [comment]
I opened imageStack and intensityTable using starfish.display to visualize the images and the spots as you explained me. 
I was wondering if it is possible to export imageStack and spots together. It would be very useful to export them in a format like TIFF that can be opened with Fiji (for example using the method to_multipage_tiff that I can easily use for ImageStacks)

**Comment by ttung** [comment]
We don't support such an export mechanism.  Could you explain your use case for this (i.e., what does this solve that napari doesn't currently do), and what the expectations for behavior might be?  Would the spots detected on a given RCZ be shown on other RCZ? (RCZ = round-channel-z)

**Comment by ttung** [comment]
Also cc: @neuromusic

**Comment by pdichiaro** [comment]
Napari works very well for the visually inspection of  ImageStack and intensityTable and so to set up the process of spot detection. I would like to export that result in a Tiff format that can be opened with Fiji as well. I think it would be very useful to have a processed image with the identified mRNA spots (it would really nice to have it after the segmentation as well) which can be associated to a list of genes and dot counts created at the end of pipeline.

**Comment by ambrosejcarr** [comment]
We support exporting the imagestacks, but not conversion of the IntensityTable insto something FIJI understands. 

See the following link for imagestack export: https://github.com/spacetx/starfish/blob/master/starfish/core/imagestack/imagestack.py#L1013
