### ISSUE TITLE
Support manually-defined ROIs for cell segmentation

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1370]
# Objective

*As a user relying on manual segmentation, I want to assign spots to cells that I’ve already segmented in another annotation tool so that I can generate a spatially annotated gene expression matrix.*

## Acceptance Criteria
- [ ] User can assign spots to cells based on masks or polygons saved on disk or at a URL
- [ ] Supported formats include FIJI’s Segmentation Manager (raster), Ilastik (raster), FIJI’s ROI Manager (polygon), and GeoJSON (polygon)
- [ ] For each file type, a rendered tutorial exists in documentation demonstrating how to load masks/polygons, visualize the segmented cells, assign spots to cells, and generate a gene expression matrix
- [ ] A rendered tutorial exists in documentation demonstrating how to query the segmentation mask based on the cell id in a gene expression matrix

## Notes
- Brian Long has a GeoJSON file for the Allen Institute mouse SpaceTx data
- Deep has a FIJI ROIset for the cultured dataset
- [Prototype implementation by Deep & Ambrose for Segmentation Manager, ROI Manager, and GeoJSON](https://github.com/spacetx/starfish/blob/1d2993fdcee3d2d30464bd9965ee6cdd1626efe6/notebooks/manual_segmentation_example.ipynb)
- Example ROIsets can be found with SeqFISH data: 

```
$ aws s3 ls --profile spacetx spacetx.starfish.data.public/browse/raw/seqfish/
2018-10-16 14:36:50 2919279786 1.tif
2018-10-16 14:36:51 2919279786 2.tif
2018-10-16 14:36:51     198407 2017-08-23-10k-gene-barcodes round I to V.csv
2018-10-16 14:36:51 2919279786 3.tif
2018-10-16 14:36:51 2919279786 4.tif
2018-10-16 14:36:51 2919279786 5.tif
2018-10-16 14:38:16      30713 RoiSet.zip
2018-10-16 14:38:16    2497440 rep4-coordinates_Pos0.csv
```

## Validation

- [ ] User feedback on tutorial demonstrating loading and applying FIJI Segmentation Manager masks
- [ ] User feedback on API docs for loading FIJI FIJI Segmentation Manager masks
- [ ] User feedback on tutorial demonstrating loading and applying FIJI ROIset
- [ ] User feedback on API docs for loading FIJI ROIset
- [ ] User feedback on tutorial or demonstrating loading and applying GeoJSON
- [ ] User feedback on API docs for loading GeoJSON
- [ ] User feedback on tutorial showing how to query the segmentation mask based on the cell id in a gene expression matrix

**Comment by pdichiaro** [comment]
In some cases I need to segment manually. I think it will be really useful to import ROIs as segmentation mask from ImageJ/Fiji.

**Comment by ambrosejcarr** [comment]
@pdichiaro would you be willing to send us an ROI file and paired image that you'd like to have us import? Any example data will do, it needn't be image-based transcriptomics. I'm willing to test out imports of them. If this works, you can send the data to starfish@chanzuckerberg.com

**Comment by ambrosejcarr** [comment]
@pdichiaro thanks for the sending the data. the `read-roi` package appears to load the rois you've linked without difficulty. I'm not broadly familiar with the types of ROIs that the ImageJ ROIset supports, but reading the package's code it appears that it translates each of the ROIs into a polygon. Is this consistent with your understanding of how things should work? 

@shanaxel42 @kne42 @ttung opening up the ROIset, it produces an object in memory with the following structure: 

```python
In [1]: type(rois)
Out[1]: collections.OrderedDict
In [2]: rois['0003-0842-1744'].keys()
Out[2]: dict_keys(['type', 'x', 'y', 'n', 'width', 'name', 'position']
```

Where `x` and `y` are pixel coordinates, `n` is the total number of points, `name` is the dict key (here `0003-0842-1744`), `position` records information about the location within various non-(`y, x`) axes that the ROI lies in -- there's a bit of complexity here and I don't fully understand it, I'd need to play around with more complex ROIs, I think. `width` in these examples is `0`, which would be consistent with the fact that they are 2-d. 

We currently have a SegmentationMaskCollection which can be built from a `label_image` which must have coordinates. To extend to accept ImageJ ROIs, we will need to: 

1. Determine how we want to request physical coordinate information from users; these are not embedded in the ROIset
2. Convert the polygons into a masks. 

Do any of you have suggestions about how we might want to approach this?

**Comment by pdichiaro** [comment]
they are like polygons that surround cells like the screenshot below.

<img width="1027" alt="Screenshot 2019-07-15 at 22 19 00" src="https://user-images.githubusercontent.com/50377927/61246789-f2d7e180-a74f-11e9-8434-2d0a28b02e98.png">

I think I can create a segmentation mask using ROI and Fiji. Maybe it is possible to import it in starfish with label_image.
