### ISSUE TITLE
Inplace conversion to Starfish format seems slow

### ISSUE THREAD

**Issue by njmei** [spacetx/starfish#1388]
A 2 round, 5 channel, 29 fov, 44 zplane mini-experiment takes about 30 minutes to convert to starfish format. This is likely to be problematic for our pipeline especially if we want to be converting + analyzing data on a per round basis as soon as it comes off the microscope.

It seems like the majority of time is still being taken up by `write` calls by `slicedimage` even for inplace conversion.

zipped cProfile output file:
[starfish_conversion.prof.tar.gz](https://github.com/spacetx/starfish/files/3249036/starfish_conversion.prof.tar.gz)

Visualization with snakeviz:
![Screenshot from 2019-06-03 12-03-08](https://user-images.githubusercontent.com/43766899/58827334-a0a38c80-85f7-11e9-92d4-f748c7c57ff6.png)

CC: @berl

**Comment by ttung** [comment]
What does `format_survey_data.py` do?

**Comment by njmei** [comment]
Basically it reads in our metadata format and organizes it so that starfish can fetch tiles. Then it calls `write_irregular_experiment_json`. There source for it is:

```
def format_survey_data(input_manifest_path: Path, output_dir: Path,
                       aux_probes: set = {'DAPI'}):
    survey_manifest = SurveyManifest(manifest_path=input_manifest_path,
                                     aux_probes=aux_probes)

    aux_tfs = {aux_type: SurveyAuxTileFetcher(survey_manifest, aux_type)
               for aux_type in aux_probes}
    tile_fetchers = {'primary': SurveyPrimaryTileFetcher(survey_manifest),
                     **aux_tfs}

    inplace.enable_inplace_mode()

    write_irregular_experiment_json(
        path=str(output_dir.resolve()),
        tile_format=ImageFormat.TIFF,
        image_tile_coordinates=survey_manifest.expt_dims,
        tile_fetchers=tile_fetchers,
        postprocess_func=add_codebook,
        fov_path_generator=fov_path_generator,
        tile_opener=inplace.inplace_tile_opener
    )
```

**Comment by njmei** [comment]
It's totally possible that conversion is as fast as it can be. I'm just curious whether it could be faster. So I should probably change the subject name.

**Comment by ttung** [comment]
I verified that your tile fetchers don't need to return any sane data.  That should shave 900+ seconds from your profile.  As long as it returns correctly shaped data, the actual data is discarded.

I'm codifying this expectation into a test.

**Comment by njmei** [comment]
Oh, so instead of the `tile_data` `FetchedTile` method returning `skimage.io.imread()` (like it currently does) just have it return a dummy of some sort?

**Comment by ttung** [comment]
Yes, any np array of the correct shape and dtype should work.

**Comment by njmei** [comment]
Hmm... I wonder if that will give significant time savings. Even if you pass bogus data, it will still get [sha256 hashed](https://github.com/spacetx/slicedimage/blob/d8db571fd8e17186271f166992e990084cc48ca5/slicedimage/io.py#L331) an extra `num_rounds * num_fovs * num_chs * x_dim * y_dim` times.

**Comment by ttung** [comment]
I am somewhat skeptical that the extra sha computation will cost that much time.  It's far more likely that the extra encoding into tiff costs way more time.

**Comment by ttung** [comment]
In any case, can you just give it a whirl?  Should be an easy change. :)

**Comment by njmei** [comment]
Bizarrely, things got worse?

Here's what I did:
```
    @functools.lru_cache(maxsize=1)
    def tile_data(self) -> np.ndarray:
        return np.zeros((self.tile.shape.y, self.tile.shape.x))
```

zipped cProfile output file:
[starfish_conversion_2.prof.tar.gz](https://github.com/spacetx/starfish/files/3249870/starfish_conversion_2.prof.tar.gz)

snakeviz:
![Screenshot from 2019-06-03 16-49-37](https://user-images.githubusercontent.com/43766899/58841658-c8a6e600-861f-11e9-95b5-6639bcba6e04.png)

**Comment by njmei** [comment]
@ttung Hey Tony, I had tried your suggestion, but it did not appear to make things any faster...

**Comment by ttung** [comment]
Is this the same data set?  I'm a bit suspicious since the imsave portion should be the same, but the new profile is 670s while the old profile is only 339s.

**Comment by njmei** [comment]
Yeah exact same dataset. Very odd, I know...
