### ISSUE TITLE
ExpressionMatrix construction propagates "nan" spots

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1392]
## Issue
Decoding uses "nan" as the placeholder for a gene id that does not decode. When Expression Matrices are constructed, we propagate "nan" as a gene value, which typically has a high count, as usually about half of the spots do not decode. 

## Proposal 
"nan" should not be propagated, but should be recorded as a metadata that reflects the number of spots in a cell that did not decode.

**Comment by neuromusic** [comment]
Based on conversation w/ @mattcai & @shanaxel42 ...

we should include both counts of "total spots" and "unassigned/non-decoded spots" as metadata
