### ISSUE TITLE
Remove in place computation

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1399]

**Comment by shanaxel42** [comment]
@berl @kevinyamauchi @njmei  would this be ok with you guys?

**Comment by njmei** [comment]
Err which in-place computation are we talking about?

Is the the `in_place` arg used in the following?

```
bpass = Filter.Bandpass(*args)
bpass.run(some_imagestack, in_place=True)
```

**Comment by shanaxel42** [comment]
> Err which in-place computation are we talking about?
> 
> Is the the `in_place` arg used in the following?
> 
> ```
> bpass = Filter.Bandpass(*args)
> bpass.run(some_imagestack, in_place=True)
> ```

Yup! we're talking about removing the ability to do this because it makes recording provenance much harder.

**Comment by njmei** [comment]
Hmm... I guess we will just need to be careful about memory usage?
```
bpass  = Filter.Bandpass(*args)
# Will necessarily take up 2x the size of original_imagestack
bandpassed_imagestack = bpass.run(original_imagestack)
del original_imagestack
```

**Comment by ttung** [comment]
Yes, it does increase worst-case memory consumption. :(

**Comment by njmei** [comment]
So just one datapoint, but I tried pre-emptively removing `in_place=True` but at least on my dev workstation which only has 32 GB of RAM, this proves to be fatal (`bus error (core dumped)`) for running even fairly small test datasets.

Restoring `in_place=True` allows things to run to completion without core dumps.

If `in_place` **absolutely** needs to go that's fine, just give me heads up as I will probably need to acquire a different dev machine.

**Comment by ttung** [comment]
Did you delete the intermediate ImageStacks?

**Comment by njmei** [comment]
I did not, I thought Python GC should be smart enough to do that automagically?

**Comment by ttung** [comment]
If you don't delete the variable, it's a reference that the GC can't touch.

**Comment by shanaxel42** [comment]
closing in favor of #1439
