### ISSUE TITLE
ExpressionMatrix methods

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1411]
After target assignment I created an expression matrix (a 2-dimensional cells x genes tensor). 

<img width="589" alt="Screenshot 2019-06-18 at 19 23 41" src="https://user-images.githubusercontent.com/50377927/59705626-0e0e0a80-91ff-11e9-83cd-04fe9d0f25d2.png">

I need to save it for the following usage with single-cell analysis software packages but ExpressionMatrix methods return these kinds of errors.

matrix.save('expression_matrix')

DataArray.name or Dataset key must be either a string or None for serialization to netCDF files

matrix.save_loom('expression_matrix1')

invalid indexer array, does not have integer dtype: array(<Axes.X: 'x'>, dtype=object)

matrix.save_anndata('expression_matrix2')

invalid indexer array, does not have integer dtype: array(<Axes.X: 'x'>, dtype=object)

**Comment by shanaxel42** [comment]
Sorry about this @pdichiaro I've opened a PR to fix these issues. Another thing to note is that when saving as a anndata file the filename must end in ".h5" so `matrix.save_anndata('expression_matrix2.h5')`  will work after my changes land.

**Comment by pdichiaro** [comment]
please let me know when these issues will be fixed. Thanks.
