### ISSUE TITLE
create ImageStack from IntensityTable and SegmentationMaskCollection

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1414]
Is it possible to create ImageStack from IntensityTable and SegmentationMaskCollection?

I was wondering if it is possible to use starfish.ImageStack.from_numpy.

<img width="1776" alt="Screenshot 2019-06-19 at 18 43 08" src="https://user-images.githubusercontent.com/50377927/59784173-1bd89400-92c2-11e9-87b1-c744cd8617c9.png">

**Comment by ttung** [comment]
It would not be possible to go back to ImageStack once you move to spot space (the exception is if you are using pixel decoding, which technically does retain all the data to go back to image space).

**Comment by ttung** [comment]
Could you describe the use case that might require this?

**Comment by pdichiaro** [comment]
I need to visually inspect Segmentation.Watershed to see which threshold to apply to nuclei and stain images. I was wondering if there is a function that returns the outline of segmented cells. Starfish.display does not work in this case. 

After starfish.spots.TargetAssignment.Label I need to visualize the resulting IntensityTable to see if it works and all dots that are only contained within cells. I tried to use MERmaid but I do not know if I can use it with starfish outputs.

**Comment by shanaxel42** [comment]
@dganguli

**Comment by dganguli** [comment]
Hi @pdichiaro, @ttung is correct in that there is no clean way to create an ImageStack from an IntensityTable and SegmentationMaskCollection. We do not support this functionality.

However, for your use case, there is currently a PR under review (https://github.com/spacetx/starfish/pull/1430) that lets you use Starfish.display to view segmentation masks on top of your imaging data. Starfish.display also currently allows you to view spots on top of your image data. As such, Starfish.display will now satisfy both of your use cases. Using Starfish.display, you will be able to visually inspect the quality of your cell segmentation and target assignment.

Furthermore, you can use MERmaid with Starfish. IntensityTable exposes a to_mermaid function that allows you to visualize your spots in Mermaid.

This PR is likely to be merged shortly.

**Comment by dganguli** [comment]
I'll close this for now, but please re-open if this does not solve your problem!
