### ISSUE TITLE
Decoded tables 

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1416]
starfish.spots.Decode and starfish.spots.AssignTargets  return IntensityTables as outputs. Is it possible to create decoded tables stored as .csv files tha can be read by pandas in Python and in R ?

**Comment by ttung** [comment]
`to_mermaid` effectively is a gzipped csv file.  Can you try that to see if it produces the output you want?

**Comment by ambrosejcarr** [comment]
Hi @pdichiaro. I believe that `IntensityTable.to_decoded_spots` should do what you're looking for. I'm going to close this, but if this doesn't solve your problem feel free to reopen it and we're happy to discuss further.
