### ISSUE TITLE
[Question] Using Starfish with a task queue/scheduling framework

### ISSUE THREAD

**Issue by njmei** [spacetx/starfish#1423]
Hi all,

So I've been looking into running Starfish with a task queue and scheduling framework combo (maybe something like "Celery + Airflow") in order to extend Starfish so that it can do things like:

- Preprocess and analyze imaging rounds within an experiment in near real-time as they come off the microscope
- Deal more seamlessly with hybrid type experiments (MERFISH + smFISH)
- Easily create and maintain different types and combinations of preprocessing/analysis workflows in a production environment

Unfortunately, a lot of these frameworks themselves use Python's `multiprocessing` pools for workers and I'm encountering issues where Starfish's use of `multiprocessing` is clashing. (e.g. errors like `daemonic processes are not allowed to have children` basically [trying to run multiprocessing pools in multiprocessing pools is bad](https://stackoverflow.com/questions/17223301/python-multiprocessing-is-it-possible-to-have-a-pool-inside-of-a-pool)).

In the short term I think I will plan to call Starfish stuff via `subprocess`. So I guess my questions are:

1) Is this `subprocess` route the most straightforward one or are there better potential strategies that can be used right now?

2) Long term for the Starfish team is there a rough timeline for when features like the `CLI` would be added back or for adding new features like `dask`?

**Comment by ttung** [comment]
Yes, `subprocess` is probably the best way to do it.  Do you know why they use multiprocessing for workers?  That just seems fragile.

We did a pretty deep exploration of dask; we found some serious issues with dask+xarray.  While we mapped out a path forward, it is pretty resource intensive (i.e., it likely won't be done for a while).

Does the cli solve any problems that a standalone python script does not solve?

**Comment by shanaxel42** [comment]
Another thing to note is that setting `n_processes=1` in Imagestack.apply() disables multiprocessing. So that could be another route to take.

**Comment by njmei** [comment]
Thanks for the replies! Not s
