### ISSUE TITLE
multiprocessing pool processes spawned within combine_adjacent_features persist till parent process terminates

### ISSUE THREAD

**Issue by richardque** [spacetx/starfish#1435]
When running my DARTFISH pipeline for multiple FOVs within an experiment, I noticed that multiple processes would continue to spawn with each additional FOV that was processed. I believe I tracked down the culprit to _create_spot_attributes within combine_adjacent_features.py, lines 325-335, a multiprocessing pool is called but doesn't seem to have a termination. Moving it within a with statement appeared to solve the issue for me. 
Was the pool left running by design and necessary for other functions?

**Comment by ttung** [comment]
This is a bug.  Thanks for the report!
