### ISSUE TITLE
Harmonize apply and reduce

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1446]
`split/apply/reduce/combine` are common, related frameworks that users expect to work harmoniously with standard APIs 

Starfish currently has: 

1. `starfish.Filter.reduce` which takes a string reference to a function and module and reduces the dimensionality of an input `ImageStack`. 

2. `starfish.ImageStack.apply` which takes a callable and applies it to chunks of the `ImageStack`, without changing the dimensionality. 

@dganguli and I suspect it would be more intuitive either for `reduce to be a classmethod of the `ImageStack` or for `Apply` to become a filter. This need not dictate that this be the sole code path for apply, as we recognize that multiple other pipeline components leverage it, but it could be that it becomes a private method.

**Comment by ttung** [comment]
`apply` should be a filter (in addition to being an instance method).  reduce as a classmethod of ImageStack makes no sense.

**Comment by ambrosejcarr** [comment]
> apply should be a filter (in addition to being an instance method). reduce as a classmethod of ImageStack makes no sense.

Cool with me, my requirement here is just consistency between the two.
