### ISSUE TITLE
Automatic threshold using Spot Detection

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1454]
I use LocalSearchBlobDetector  to find spots of different sizes in seqFISH. I was wondering if there is a function to establish a threshold value plotting the number of spots found upon thresholding the filtered image as a function of the threshold value.

**Comment by ambrosejcarr** [comment]
Thank you for the issue! Our spot finding is currently somewhat fragmented. @shanaxel42 has begun work to reconcile our various spot finders. You can see a sketch of the plans in #1005 . 

As it stands, we _do_ implement an auto threshold-finding approach, but only in the LocalMaxPeakFinder. It evaluates the number of spots detected at various thresholds and picks a threshold in the stable regime of the threshold parameter. We would like to extend this characteristic out to other spot finders as part of the above work. 

For visualization and parameter selection in the mean time, the `starfish.display` method can display only spots exceeding a specific intensity (threshold) with the `mask_intensities` parameter. If you set a permissive intensity on the spot finder, you can successively increase the `mask_intensities` spot floor until the background spots you want to exclude fall out of the analysis. Does this help you with your request?

**Comment by pdichiaro** [comment]
Thank you for you reply. 
Your solution is working to establish a right threshold.
 May I ask you what anchor round and search radius exactly mean ? 
I think that the anchor round should be the first hybridization round (before any stripping step; in my case is round 0) where LocalSearchBlobDetector finds all the spots. Then the algorithm looks for those spots in the channels of following rounds based on a established search radius. How to determine how many pixels should I put as search radius parameter? Does it depend on the registration step?

**Comment by ambrosejcarr** [comment]
See #1469 for an answer. :-)
