### ISSUE TITLE
de-dupe contributing.rst

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#1470]
currently, contributing.rst largely `duplicates docs/source/contributing/index.rst`

while the page in the docs is important for *code* contributors, contributing.rst is important for all contributors, including users who submit issues. in fact, Github will encourage new contributors to read this doc when they start to submit an issue

we should update contributing.rst to provide high-level guidelines for contributions, including links to relevant docs for code contributions

**Comment by mattcai** [comment]
closed by #1868
