### ISSUE TITLE
create links to glossary entries from terms elsewhere in the docs

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#1477]
**Is your feature request related to a problem? Please describe.**

It can be hard for new users to understand what various terms refer to. We have a glossary (thanks @ttung!) but it is hard for new users to discover this. For example, see https://github.com/spacetx/starfish/issues/671#issuecomment-516651352

**Describe the solution you'd like**

Sphinx has a builtin "glossary" function, which we can use. This would mean doing the following...

1. converting glossary.md to glossary.rst
2. tag the glossary with `.. glossary::` & make sure it conforms to a particular syntax
3. when terms show up elsewhere in the documentation, including docstrings, add the `:term:` tag to create a link to the glossary entry

For details, see https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html

**Describe alternatives you've considered**
We could also manually create links.

**Comment by neuromusic** [comment]
cc @kevinyamauchi

**Comment by kevinyamauchi** [comment]
Thanks! This would be super helpful.

**Comment by neuromusic** [comment]
closed with #1811
