### ISSUE TITLE
Spot_ID missing in IntensityTable using LocalSearchBlobDetector

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1479]
When I use LocalSearchBlobDetector I generate an IntensityTable without Spot_ID. It is not possible to use AssignTarget.Label

**Comment by shanaxel42** [comment]
This should actually be addressed with the work in #1450

**Comment by pdichiaro** [comment]
LocalSearchBlobDetector generates the following IntensityTable without Spot_ID:

<img width="491" alt="Screenshot 2019-08-06 at 19 42 26" src="https://user-images.githubusercontent.com/50377927/62563085-851c6280-b882-11e9-84a9-9de09d1aa2c1.png">

**Comment by pdichiaro** [comment]
AssignTarget.Label generates this error:
<img width="994" alt="Screenshot 2019-08-06 at 19 46 11" src="https://user-images.githubusercontent.com/50377927/62563244-e80df980-b882-11e9-81b0-f34554bbc614.png">

**Comment by neuromusic** [comment]
did #1450 fix this? if not, please re-open
