### ISSUE TITLE
Vignette explaining how spot finder parameters can be tuned for different image types. 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1480]
**As a** user of starfish's spot finders **I want** a tutorial that clearly explains how the spot finder parameters work with visual examples **so that** I can understand how to tune spot finding parameters for data like mine. 

### Acceptance Criteria

1. Vignette demonstrating spot finding on images with varying signal and noise parameters.
2. Vignette Includes tuning of both radius and intensity parameters
3. Validate with 3 scientists that the vignette is accurate and adequate to tune spot finders. 

### Notes

* See original user request [here](https://spacetx.slack.com/archives/CCU5DN4DV/p1564962438034000?thread_ts=1564961684.033200&cid=CCU5DN4DV)

**Comment by neuromusic** [comment]
superceded by #1749
