### ISSUE TITLE
Starfish should leverage parallelism on our users' architectures

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1486]
# Objective
*As a scientist using starfish, I want starfish to leverage the compute resources that I have available, so that I'm not running unnecessarily slow workflows when faster alternatives exist.*

## Acceptance criteria
* Solution optimizes CPU usage
* Solution works on Windows, HPC, Cloud, Linux
* Solution should be forward facing regarding GPU usage, if possible
* CI tests relevant operating systems
* Implement examples with benchmarks of starfish running on HPC, Cloud, Windows, Linux. 

## Validation
* Validate that our users can use starfish on windows and HPC. 

## Out of scope: 
* GPU implementations of starfish algorithms

**Comment by ttung** [comment]
This issue is overly broad.  @shanaxel42 is working on the cloud runner, and most of the code is reasonably parallel already.
