### ISSUE TITLE
Access a mask in a SegmentationMaskCollection by ExpressionMatrix cell_id

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#1487]
**Is your feature request related to a problem? Please describe.**
I think it would be useful if we could get a particular mask from a `SegmentationMaskCollection` using the `cell_id` in a corresponding `ExpressionMatrix`.

**Describe the solution you'd like**
- A method that accepts a `cell_id` returns the mask 
- Store masks in a dictionary and make the key the `cell_id`

**Additional context**
I think this is useful for visualization (e.g., create an image with cells colored by "type") and QC (e.g., inspect segmentation of a cell with funky gene expression).

**Comment by ttung** [comment]
I believe this is done.
