### ISSUE TITLE
Enforce uint16 input type

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#149]
Right now starfish loads float, we should do one of: 
- [ ] only accept `uint16`
- [ ] convert to `uint16` or complain if we can't deduce how to do this from the data.

**Comment by ambrosejcarr** [comment]
After a team discussion we decided we should not restrict to uint16. @ttung do your recently merged PRs address the second point?

**Comment by ttung** [comment]
Not really.  It allows for any type as long as they're convertible to a type that can represent the entire range (i.e., it does not allow float -> int).

**Comment by ambrosejcarr** [comment]
Sorry, you're right, and that's what we want. I think this can be closed now.
