### ISSUE TITLE
Improved Codebook.from_numpy() example

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#1491]
**Is your feature request related to a problem? Please describe.**
I think the [example for `Codebook.from_numpy()`](https://spacetx-starfish.readthedocs.io/en/latest/api/data_structures/codebook.html#starfish.core.codebook.codebook.Codebook.from_numpy) is confusing because both the round and target size are 2, so it's not clear which dimensions in the input array correspond to dimensions in the `Codebook`.

**Describe the solution you'd like**
I think giving each dimension in the example array should have a unique size so it's more clear how it maps and also describe it in the documentation.

**Comment by ambrosejcarr** [comment]
Thanks for the comment @kevinyamauchi . I think this makes sense to change. 👍
