### ISSUE TITLE
Run starfish CI on windows

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1493]
**As a** starfish user on a windows platform **I want** starfish to be tested on windows **so that** I am confident that starfish will work on my operating system.

### Acceptance Criteria
1. Windows added to starfish CI

**Comment by ambrosejcarr** [comment]
Tagging @dany-fu. Thanks for the bug report on the community call yesterday!

**Comment by ttung** [comment]
DONE
