### ISSUE TITLE
Cell filters should be implemented on SegmentationMaskCollection

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1496]
# Objective

Currently there are several filters that act on region objects that are implemented in the watershed segmentation object. These should be moved to SegmentationMaskCollection. 

## Acceptance Criteria
- `min_area`, `max_area` filters that remove cells below and above certain total region areas implemented as methods of `SegmentationMaskCollection`
- `min_distance` based cell de-clumping implemented as methods of `SegmentationMaskCollection`

**Comment by ttung** [comment]
Arbitrary filters can be applied with https://spacetx-starfish.readthedocs.io/en/stable/api/morphology/index.html#filter
