### ISSUE TITLE
format_seqFISH.py

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1502]
I want to convert my images (2048x2048, 16 bit) but format_seqFISH.py sometimes creates TIFF format images with different shape (4x2048). 

![Screenshot from 2019-08-21 11-55-37](https://user-images.githubusercontent.com/50377927/63427156-c7ae7500-c414-11e9-957d-409e26820e06.png)

**Comment by ambrosejcarr** [comment]
Hi @pdichiaro . This does indeed look odd. The `format_seqFISH.py` script was built specifically for data from the Cai lab and reads the image shape directly from the files. It expects the images to be organized as (z, ch, y, x). I am wondering if perhaps your data do not have this ordering. Beyond that, it would be difficult for me to help debug this without seeing how your data are organized. 

One orthogonal suggestion that might help is that we have produced more general tooling to format data which you could try. if you split your data into a series of single-plane tiff files, starfish will read the file name conventions and an auxiliary file containing physical coordinates into the metadata needed for SpaceTx format: 

https://spacetx-starfish.readthedocs.io/en/latest/usage/data_formatting_examples/exec_format_structured_data.html#sphx-glr-usage-data-formatting-examples-exec-format-structured-data-py

I wonder if this would work for your data. If you're game to try, we'd be very interested in feedback on how it worked for you!

**Comment by pdichiaro** [comment]
Hi,
I do not understand why if I shrink my images from 4 channels to 2 ones format_seqFISH.py works very well. if you want I can send to you my images because I can not get the cause of the issue.

**Comment by ambrosejcarr** [comment]
The `format_seqFISH.py` script has a `primary_image_dimensions` setting. Have you updated that to match your examples? In this case, [the script](https://github.com/spacetx/starfish/blob/master/docs/source/_static/data_formatting_examples/format_seqFISH.py#L180) expects: 

```python
    primary_image_dimensions: Mapping[Union[str, Axes], int] = {
        Axes.ROUND: 5,
        Axes.CH: 12,
        Axes.ZPLANE: 29,
    }
```

**Comment by pdichiaro** [comment]
Yes, I did.

**Comment by ttung** [comment]
When you say that sometimes it produces tiles with an unexpected shape, how does that manifest?  Is it a small number of tiles per experiment that are like this?  Or all the tiles of some experiments?

If you are comfortable, can you try loading the n-dimensional TIFF and dumping its shape?

If not, can you upload an image somewhere and we can take a look at it?

**Comment by pdichiaro** [comment]
for images with one or two channels seqFISH_format.py works(the shape is correct x=2048 and y=2048) but when I acquire more than 2 channels the script generates TIFF images with unexpected shape(x=number of channels and y=2048). 
As alternative I used SpaceTx writer to convert my data. It worked and always creates TIFF images with the real shape(x=2048 and y=2048) but I do not know how to handle it for generating a valid codebook.json (canonical codebook.csv written for seqFISH_format.py is not recognized).

I sent an email to starfish@chanzuckerberg.com containing 2 links to download my data.

**Comment by ttung** [comment]
@pdichiaro Sorry for the late response.  I looked at one of the raw 4D TIFs and the shape was (34, 2048, 2048, 4).

format_seqFISH expects the shape to be [zplane, ch, y, x], so that explains what you are seeing.

The easiest solution is to change how the script slices the data out of the 4D TIFF:

Instead of:
```
        return cached_read_fn(self._file_path)[self._zplane, self._ch]
```

You probably want:
```
        return cached_read_fn(self._file_path)[self._zplane, :, :, self._ch]
```

**Comment by ttung** [comment]
Let me know if this is still an issue.
