### ISSUE TITLE
Starfish Tutorials

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1522]
## Objective

*As a scientist learning to use starfish, I want comprehensive tutorials that demonstrate how starfish's components work and how to pick the right image processing components so that I can build an image processing pipeline for my own data*

## Acceptance Criteria
* "Tutorial" section of docs that walks through rendered examples demonstrating data formatting, image corrections, enhancing signal, normalization, finding and decoding spots, cell segmentation, and spot assignment

**Comment by neuromusic** [comment]
Organization proposed by @mattcai:

1. Installation
2. Data Access
3. Image Corrections
4. Enhancing signal & removing background noise
5. Normalization
6. Finding and decoding spots
7. Cell Segmentation
8. Assign spots to cells
9. Assessing quality

**Comment by neuromusic** [comment]
closing this... most of the tutorials are done. tracking in individual issues & under "documentation improvements" epic #858
