### ISSUE TITLE
Add offline support for starfish.data

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#1530]
**Is your feature request related to a problem? Please describe.**
I would like to be able to work offline with data that starfish has cached. Currently when I don't have an internet connection, `starfish.data.MERFISH()`, for example, hangs for a very long time before throwing a `ConnectionError`

**Describe the solution you'd like**
I would like for `starfish.data` to read from cache whenever it is faster than reading from the web link.

**Comment by ttung** [comment]
Dupe of #917
