### ISSUE TITLE
most of detected blobs are in first frame of the stack when we use BlobDetector

### ISSUE THREAD

**Issue by abedghanbari2** [spacetx/starfish#1556]
#### Description

I'm using BlobDetector and I see most of the detected blobs in my first z-level frame. 

Here is the file to recreate [tiff](https://github.com/abedghanbari2/starFish1/raw/master/testBlobDetector.TIFF)
```
p = DetectSpots.BlobDetector(
    min_sigma=1,
    max_sigma=10,
    num_sigma=10,
    threshold=np.percentile(np.ravel(filtered.xarray.values), 90),
    measurement_type='mean',
    detector_method='blob_dog'
)
intensities = p.run(
    primary_image,
#     blobs_axes=(Axes.ZPLANE),
#     n_processes=20
)

```

![image](https://user-images.githubusercontent.com/22683143/65073055-10981180-d960-11e9-98b1-2db19956e382.png)

![image](https://user-images.githubusercontent.com/22683143/65073138-39b8a200-d960-11e9-842c-ace7ac393c29.png)

#### Versions
Windows-10-10.0.14393-SP0
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
NumPy 1.17.2
SciPy 1.3.1
scikit-image 0.15.0
pandas 0.25.1
sklearn 0.21.3
xarray 0.12.3
sympy 1.4
starfish 0.1.5+23.g766d325.dirty

**Comment by ambrosejcarr** [comment]
@abedghanbari2 If you are able to send us the data that corresponds to this problem that would help me debug. You can email it to `starfish-data@chanzuckerberg.com`

However, I can also see that our documentation might have tripped you up. Passing `blobs_axes=(Axes.ZPLANE,)` implies that the Z-plane should be max projecting prior to measurement. I see you've commented this out, which is good. It sounds like you're interested in measuring across Z, which would be accomplished with the `is_volume=True` flag, as follows:

```python
p = DetectSpots.BlobDetector(
    min_sigma=1,
    max_sigma=10,
    num_sigma=10,
    threshold=np.percentile(np.ravel(filtered.xarray.values), 90),
    measurement_type='mean',
    detector_method='blob_dog',
    is_volume=True,
)
intensities = p.run(primary_image)
```

It seems from this issue that there is an opportunity for starfish to improve the clarity of how to detect spots in various shapes of image data.

**Comment by abedghanbari2** [comment]
Thanks Ambrose for responding quickly.

I just updated the issue with a link to the file, but here is the link again:
[tiff stack](https://github.com/abedghanbari2/starFish1/raw/master/testBlobDetector.TIFF)

I didn't change `is_volume` as its default value is set to True ...

**Comment by ambrosejcarr** [comment]
Perfect, I'll take a look. Thanks.

**Comment by ambrosejcarr** [comment]
You hit a bug in the way we call `blob_dog` -- we pass `num_sigma` as `sigma_ratio`, which is not going to perform as expected. I've created #1558 to track. That said, I tried to tune blog_dog on your data and struggled because you have aggregates of spots of different sizes, a pattern for which blob_dog struggles. See this [example](https://scikit-image.org/docs/dev/auto_examples/features_detection/plot_blob.html)

I've demonstrated how I would go about tuning `blob_log` on your data in this [gist](https://gist.github.com/ambrosejcarr/b9e20574f08e341a4c5fa8206c6bdf80) 

Please let me know if this solves your problem!

**Comment by abedghanbari2** [comment]
This is exactly what I was hoping to achieve! Thank you Ambrose!
