### ISSUE TITLE
Supporting tif/nd2 file formats

### ISSUE THREAD

**Issue by abedghanbari2** [spacetx/starfish#1557]
**Is your feature request related to a problem? Please describe.**

We are using Nikon microscopes and in each round (out of more than 10) of our experiment we have ~80 GB of data in `.nd2` format. We are using nd2 files as we originally didn't want to lose any metadata.

**Describe the solution you'd like**
I was hopping to have a support for nd2 files to make json files (and single frame `.tiff` files) directly from `.nd2` files.

**Describe alternatives you've considered**
 In order to write the json file what we do for now is to convert all files from nd2 to single frame tiff format that have channel-label and z-level in their filenames so it could be used by `get_tiel()' and later make a formatted folder containing all the frames and json files. Very suboptimal specifically dealing with this large volume.

**Additional context**
I wish there were no need for starfish to save frames in its own format and separately from the original stack. This feature will save more than few TBs for each of our animals ...

-- and sorry if I posted few issues/feature requests in a row!

**Comment by ttung** [comment]
I think this could be an interesting topic for our [community sync phone call](https://github.com/spacetx/starfish/issues/1494).  I added it to the agenda for the next call (9/26).

**Comment by ambrosejcarr** [comment]
If we decided to enable this functionality, there's potentially something to learn about how `zarr` _communicates_ how users should extend their abstracted their back-ends: https://zarr.readthedocs.io/en/stable/api/storage.html#

It feels similar to our discussion about letting users write adapters to the TileFetcher contract.

**Comment by abedghanbari2** [comment]
Right after this feature request I found the `from_numpy` which solves part of the problem.

**Comment by abedghanbari2** [comment]
I just found out about `from_numpy` in starfish which in combination with nd2reader package solves the problem of loading nd2 files into starfish

**Comment by ambrosejcarr** [comment]
Very cool! Would you be willing to share your solution with us? It would be helpful if we take the plunge and generalize.

**Comment by abedghanbari2** [comment]
Sure, just that with our data it can't allocate enough memory to hold it in memory, but works when I tested with few z-levels

`import nd2reader
import numpy as np
import starfish

nd2 = nd2reader.Nd2(r'Z:\Projects\ARG\Animals\pr005\round2\sample2Round2.nd2')
stack = np.empty([1, 1, nd2.width, nd2.height, 10], dtype=np.uint8)
for iz in range(10):
    stack[0, 0, :, :, iz] = np.array(nd2.reader.get_frame_2D(c=0, t=0, z=iz, x=0, y=0));

experiment = starfish.ImageStack.from_numpy(stack)`

**Comment by ambrosejcarr** [comment]
Thanks! Do I understand correctly that your data is organized a series of
fused images (one per round, channel, and z) that is built by stitching
multiple fields of view?

**Comment by abedghanbari2** [comment]
1- We do our stitching beforehand. We have overlapping tiles that results into photo bleaching. This has huge impact on blob detection. To avoid that I had to modify an open-source stitching package (TeraStitcher) to put tiles that has been acquired earlier (not bleached yet) on top of those that are Bleached to avoid losing SNR (results inconsistency in overlapped FOVs areas). 

An example of before/after of the correction:
![image](https://user-images.githubusercontent.com/22683143/65352433-a8903800-dbb8-11e9-8dfe-b5c6763b6d90.png)

I'm not sure how starfish is handling the overlaps in FOVs ...

2- We save stacks of images for each round and for each channel (xyz). For different rounds, we don't want to import them into starfish as we rely on our own semi-supervised registration software (Neurotator). Even though all channels are acquired simultaneously we decided to keep them in separate `.tif`s as our in-house and third-party applications are not supporting multi-channel tifs good enough. Also, the single file is big that apps that rely on loading the whole data into RAM fail to open them.

3- Another related issue: we have some inconsistency in our data as sometimes it has been saved in 12 bits then shifted to 16 bits and now back to 12 bits. How does that impact starfish? Does it read tif files assuming its uint16 resulting in some underexposure for the data that has been saved in 12 bits?

**Comment by ambrosejcarr** [comment]
Hi Abed,

Right now we have an option to merge intensity tables, which contain spot
finding results, by picking the overlapping image that detected more spots,
and discarding the other image's features.

Our users seem satisfied with this, for the time being, but we admit it's a
bit rudimentary! If you have suggestions on how to improve this we'd love
to hear them.

Regarding reading Tiff files, we leverage `skimage.io.imread` which imports
the `tifffile` plugin. You can read about it here:
https://scikit-image.org/docs/dev/api/skimage.external.tifffile.html

It's also worth noting that starfish internally represents image data in
float32, supports a number of clipping and rescaling approaches which can
be applied over arbitrary groupings. For example, you could scale each
channel separately between [0, 1], each field of view, or each individual
tile.

**Comment by ambrosejcarr** [comment]
@christoffermattssonlangseth @xyanqian and @simone-codeluppi mentioned they would be interested in starfish implementing direct-read capability of nd2 files.

**Comment by abedghanbari2** [comment]
That's great! please let me know if I could be of any help

**Comment by xyanqian** [comment]
Actually I do have one general question about nd2 format. If I do stitching in NIS, I only get a flattened big image and all metadata about the original tile position is lost. Is that normal? 
I have exactly the same 12-bit and 16-bit problem as you. My experience so far is that most programs treat 12bit as 16bit and we just set intensity threshold based on 16bit scaled to [0 1] if it's needed.

**Comment by abedghanbari2** [comment]
Are you concerned about the absolute position of each tile? For us, the relative position of the tiles are the same for all different experiments and we don’t save the metadata. Saving the xml metadata is an option too

My original request was about removing an unnecessary step of saving individual tiffs in starfish format. 

We save our nd2 to individual tiles(each containg all z-planes). Stitch them using TeraStitcher. Load the stitched tif stack into starfish using from_numpy. For me, from_numpy function solved most of the problems I had dealing with starfish format. 

However, reading nd2 directly into starfish is useful for people who analyze FOVs separately.

For 12bit images read in 16bit, you are right and  o information is lost. It’s just that we see an underexosed image which is just annoying.

**Comment by ambrosejcarr** [comment]
> You're right that no information is lost when 12 bit is read in 16bit. It’s just that we see an underexosed image which is annoying.

@abedghanbari2 The following should fix your exposure problem as @xyanqian suggested:

```python
from starfish.image import Filter
image = Filter.Clip(image, expand_dynamic_range=False)
```

Is this under-exposure annoying enough that you would you would want starfish to offer the option to expand the dynamic range to [0, 1] on loading? Or, is it enough to run the above function?

**Comment by neuromusic** [comment]
Note: #1737 implemented the ability for you to define your own custom data loader, which you should be able to use to write an ND2 file reader. We have an example of its use with 3D TIFF files at https://spacetx-starfish.readthedocs.io/en/latest/gallery/data_loading/plot_tilefetcher_loader.html#sphx-glr-gallery-data-loading-plot-tilefetcher-loader-py

You'll still need to write your own functions to build a JSON, but this will handle the data loading.

I'm going to go ahead and close this issue. If you need more help, reach out on https://forum.image.sc/tag/starfish :D
