### ISSUE TITLE
Create a new data type to handle xr.DataArray + np.ndarray

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#1564]
xr.DataArray and np.ndarray used to both be Sequence[Number] or at least be mypy-compatible with it.  Now it does not.  We should have a data type that encompasses the two possibilities.

**Comment by shanaxel42** [comment]
@ttung was this fixed with your new arraylike data type?

**Comment by ttung** [comment]
ArrayLike basically solves the problem.

**Comment by ttung** [comment]
It is a bit broader than what this calls for.
