### ISSUE TITLE
IntensityTable.to_dataframe and how to counts spots

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1576]
LocalSearchBlobDetector generates an IntensityTable which I convert to dataframe.  IntensityTable.to_dataframe requires an additional argument but I do not understand what it means.

After that I decode the IntensityTable: 
intensities = intensities.fillna(0)
decoded = exp.codebook.decode_per_round_max(intensities)
how can I count all the spots per target? 

I use the code below:
genes, counts = np.unique(decoded.loc[decoded[Features.PASSES_THRESHOLDS]][Features.TARGET], return_counts=True)
table = pd.Series(counts, index=genes).sort_values(ascending=False).
I am not sure that I am counting only the spots detected in the same round.

**Comment by berl** [comment]
If you're starting from a `DecodedIntensityTable`, try using the `groupby` method:
```
countgroups = decoded.groupby("target").groups
my_counts = {gene:len(countgroups[gene]) for gene in countgroups.keys()}
```

**Comment by pdichiaro** [comment]
Hi @berl thanks for your reply. Your method works .
