### ISSUE TITLE
Linux jupyter notebook  issues

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#1587]
#### Description
@berl reports that sometimes he sees `IOStream.flush timed out` when running on Windows:

from slack:

```
brianl: 
I also realized that running this in a notebook may have led to some IO problems.  can we get a flag to stop showing the progress bar?

brianl:
like if you are scrolling around in the terminal window it can block stdout and a worker in your Pool will die silently and your map() never returns
```

#### Steps/Code to Reproduce
See above

#### Expected Results
no errors.

#### Actual Results
Beats me.

**Comment by ttung** [comment]
@berl do you mind adding a bit about your runtime environment?  is this native windows or WSL?  Which terminal application are you using?

**Comment by berl** [comment]
the `IOStream` error was on linux, but it was from a jupyter notebook. no such errors come up when you run the same code directly (i.e. `> python  runthis.py`)

**Comment by neuromusic** [comment]
is this still an issue @berl?

I'm going to close this. feel free to re-open if you run into it again
