### ISSUE TITLE
Expose TileFetcher api to users to provide them the ability to write a loader for their file formats 

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1603]
Describes work out of discussion #1557

**Comment by neuromusic** [comment]
@ttung can you unpack your vision a bit here?

**Comment by ttung** [comment]
Sure, basically, we would offer an ImageStack loader that takes a python source file.  That source file should have a TileFetcher / FetchedTile implementation that knows how to unpack the data.

**Comment by ttung** [comment]
And as usual, documentation showing how it works.
