### ISSUE TITLE
Link to notebook is broken

### ISSUE THREAD

**Issue by hewgreen** [spacetx/starfish#163]
This link in the main readme is broken. https://github.com/spacetx/starfish/blob/master/notebooks/Starfish%20Simple%20ISS%20tutorial%20%7C%20Mouse%20vs.%20Human%20Fibroblasts.ipynb

How do I see a worked example? I'm interested to see examples of input and output.

Thanks

Matt

**Comment by ttung** [comment]
Apologies.  https://github.com/spacetx/starfish/blob/3584032261c6d3dbb09bb2d1a8fb3096033bba5f/notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.ipynb is the notebook until we get the fix landed.
