### ISSUE TITLE
format_seqFISH using starfish 0.1.8

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1643]
Codebook error when running format_seqFISH in starfish 0.1.8 . 

<img width="977" alt="Screenshot 2019-11-07 at 12 33 35" src="https://user-images.githubusercontent.com/50377927/68483392-c3d40700-023b-11ea-962a-533e53cb1f73.png">

**Comment by ttung** [comment]
This bug is occurring because `2-Mar` is in the codebook twice.
