### ISSUE TITLE
decoding on ImageStack from_numpy()

### ISSUE THREAD

**Issue by berl** [spacetx/starfish#1756]
#### Description

I've made an `ImageStack` from a `numpy` array, but the `Codebook.decode_metric` method fails to validate the shapes because it's expecting a `sizes` attribute of `ImageStack`.  My `ImageStack` only has `ImageStack.xarray.sizes` not `ImageStack.sizes`

```
----> 1 codebook.decode_metric(tstack,0, 1.0, 2)
      2 
      3 
      4 # In[ ]:

~/projects/starfish/starfish/core/codebook/codebook.py in decode_metric(self, intensities, max_distance, min_intensity, norm_order, metric)
    573         """
    574 
--> 575         self._validate_decode_intensity_input_matches_codebook_shape(intensities)
    576 
    577         # add empty metadata fields and return

~/projects/starfish/starfish/core/codebook/codebook.py in _validate_decode_intensity_input_matches_codebook_shape(self, intensities)
    522     ):
    523         """verify that the shapes of the codebook and intensities match"""
--> 524         ch_match = intensities.sizes[Axes.CH] == self.sizes[Axes.CH]
    525         round_match = intensities.sizes[Axes.ROUND] == self.sizes[Axes.ROUND]
    526         if not (ch_match and round_match):

AttributeError: 'ImageStack' object has no attribute 'sizes'
```
#### Steps/Code to Reproduce

```
tstack2 = starfish.ImageStack.from_numpy(np.zeros((1,1,1,512,512), dtype = np.float32))

print(tstack2.xarray.sizes)

print(tstack2.sizes)
```
gives
```
Frozen({'r': 1, 'c': 1, 'z': 1, 'y': 512, 'x': 512})

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-b91182e5ad1e> in <module>
      1 print(tstack2.xarray.sizes)
      2 
----> 3 print(tstack2.sizes)

AttributeError: 'ImageStack' object has no attribute 'sizes'

```

#### Expected Results
working decoding on `ImageStack` that was constructed from `numpy` arrays. 

#### Actual Results
see above:
`AttributeError: 'ImageStack' object has no attribute 'sizes'`

#### Versions
Linux-4.15.0-74-generic-x86_64-with-debian-buster-sid
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]
NumPy 1.17.4
SciPy 1.4.1
scikit-image 0.15.0
pandas 0.25.3
sklearn 0.22
xarray 0.14.1
sympy 1.5
starfish 0.1.10+38.g0106f031

**Comment by neuromusic** [comment]
`Codebook.decode_metric` should be applied to an intensity table, right?

**Comment by berl** [comment]
dude you're totally right. my bad.  I'll make a new issue: `starfish` is not idiot-proof
