### ISSUE TITLE
improve tests for from_codebook

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#1774]
https://github.com/spacetx/starfish/blob/a3990d27c763579a8452ea760e8adcca792c907a/starfish/core/imagestack/test/factories/from_codebook.py#L32

**Comment by ttung** [comment]
Ummm, wrong code snippet?

**Comment by ttung** [comment]
Incidentally, @mattcai suggested this is an area that could use improvement.

**Comment by neuromusic** [comment]
woops, fixed the snippet/link

**Comment by ttung** [comment]
Wait, no this is not what @mattcai says we should improve.

**Comment by neuromusic** [comment]
TODO: kill the TODO
