### ISSUE TITLE
[todo] docs for tile_opener kwarg to ImageStack.export

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#1786]
https://github.com/spacetx/starfish/blob/0106f031edc641ae0fef595548d9b1030679d591/starfish/core/imagestack/imagestack.py#L1134

**Comment by ttung** [comment]
wait who wrote this awful code? :)

**Comment by neuromusic** [comment]
I love how git calls it `blame`

![image](https://user-images.githubusercontent.com/1245615/73896892-289dfe00-4839-11ea-830b-bc9c96e16525.png)
