### ISSUE TITLE
learn_translation does not work

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1816]
transforms_list = learn_translation.run(img.reduce({Axes.ZPLANE}, func="max"), verbose=True) gives me the following error:

![Screenshot 2020-02-18 at 09 48 18](https://user-images.githubusercontent.com/50377927/74719282-05f5e700-5234-11ea-9137-f99b7c56051f.png)

starfish.__version__=0.2.0

**Comment by mattcai** [comment]
This seems to be an issue with scikit-image v0.16

starfish 0.2.0 has requirement scikit-image!=0.16.0.*,!=0.16.1.*,!=0.16.2.*,>=0.14.0

**Comment by neuromusic** [comment]
Closing this issue. Feel free to reopen if you have more Qs :D
