### ISSUE TITLE
Laplacian of Gaussian (LoG) filter

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1824]
As a user I would like to know the function to apply Laplacian of Gaussian (LoG) filter and how to choose the correct sigma .

**Comment by mattcai** [comment]
If you are using the LoG filter for blob detection, starfish has a ``starfish.spots.FindSpots.BlobDetector`` class that can be run with its ``run`` method. If you just want to convolve a LoG filter and return the output image, ``starfish.image.Filter.Laplace`` wraps ``scipy.ndimage.gaussian_laplace`` and can also be run with its ``run`` method. Details on these classes can be found by searching the docs and diving into the scipy and skimage docs.

The correct sigma depends on scale of features you want to detect. If you are trying to detect gaussian blobs, sigma should be approximately blob_radius/sqrt(2) for 2D and blob_radius/sqrt(3) for 3D.
