### ISSUE TITLE
Tutorial "Loading ImageJ ROI Sets"

### ISSUE THREAD

**Issue by giovp** [spacetx/starfish#1899]
**Is your feature request related to a problem? Please describe.**
In the tutorial [Loading ImageJ ROI Sets](https://spacetx-starfish.readthedocs.io/en/latest/gallery/tutorials/manual_segmentation.html#tutorial-manual-segmentation) it's unclear how to get/generate the ROI.zip file.

The explanation for ImageJ seems quite clear, but it's not clear what image to use for that specific task. I also looked for the image in `~/.starfish/cache` but could not find any pointer to the MERFISH data (which I assume is the one needed for the tutorial). This is also related to the [assigning spot to cells tutorial](https://spacetx-starfish.readthedocs.io/en/latest/gallery/tutorials/assigning_spots.html#assigning-spots-to-cells)

**Describe the solution you'd like**
either include ROI in `starfish.data` or better explanation how to generate the files.

**Describe alternatives you've considered**

**Additional context**
This issue references the JOSS submission openjournals/joss-reviews#2440

**Comment by neuromusic** [comment]
Thanks for calling this out, @giovp !!

We want to explicitly demonstrate loading from a file, so here's the plan:
- Update the example to download `RoiSet.zip` from the [blob on Github](https://github.com/spacetx/starfish/blob/b3aa7758f3d60c2c28083cfa1cf72e954d294592/starfish/core/morphology/binary_mask/test/RoiSet.zip)
- load from the downloaded file

**Comment by mattcai** [comment]
In order to preserve the ability for readthedocs to render example gallery in the future (#1865), we chose to comment out the code that downloads `RoiSet.zip` from github.
