### ISSUE TITLE
Quickstart and napari

### ISSUE THREAD

**Issue by vals** [spacetx/starfish#1901]
The 'default' installation instruction on the Readme for the repository simply says to install with `$ pip install starfish`. But the quickstart guide requires Starfish to have been installed with `$ pip install starfish[napari]`.

It would be better either if Napari wasn't required for the quick start, or included with the default installation.

Related to https://github.com/openjournals/joss-reviews/issues/2440

**Comment by mattcai** [comment]
Since many users find napari to be very valuable, we want to keep napari in the quickstart guide.  I will update the default installation instructions instead.

**Comment by neuromusic** [comment]
Closed with #1906
