### ISSUE TITLE
Displaying example from data formatting tutorial

### ISSUE THREAD

**Issue by vals** [spacetx/starfish#1903]
After going through the tutorial on how to format image data for Starfish (https://spacetx-starfish.readthedocs.io/en/latest/gallery/data_formatting/plot_format_structured_data.html#sphx-glr-gallery-data-formatting-plot-format-structured-data-py) I wanted to use the `display()` function to look at it. But if you do e.g. 
```
imgs = e.fov().get_image('primary')
display(nuclei)
```
napari launches with 'Not Responding' status and crashes the Python interpreter when you kill the window.

Related to https://github.com/openjournals/joss-reviews/issues/2440

**Comment by mattcai** [comment]
I am not able to recreate your issue. Does the `display()` function work for you when you run the quickstart tutorial?

After running the code in [format structred data tutorial](https://spacetx-starfish.readthedocs.io/en/latest/gallery/data_formatting/plot_format_structured_data.html#sphx-glr-gallery-data-formatting-plot-format-structured-data-py) I am able to look at the (blank) images with:

```
from starfish import display
imgs = exp.fov().get_image('primary')
viewer = display(imgs)
```

**Comment by neuromusic** [comment]
Hey @vals, can you confirm that this is an issue on the quickstart tutorial, too?

If you continue to see this bug, can you post the output of the following...

``` Python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import skimage; print("scikit-image", skimage.__version__)
import pandas; print("pandas", pandas.__version__)
import sklearn; print("sklearn", sklearn.__version__)
import xarray; print("xarray", xarray.__version__)
import sympy; print("sympy", sympy.__version__)
import starfish; print("starfish", starfish.__version__)
import napari; print("napari", napari.__version__)
```

thanks!

**Comment by neuromusic** [comment]
I'm going to close this issue, but please feel free to re-open @vals if you continue to see the problem.
