### ISSUE TITLE
Include output in example notebooks

### ISSUE THREAD

**Issue by vals** [spacetx/starfish#1904]
The notebooks with examples of using Starfish for different experiments at https://github.com/spacetx/starfish/tree/master/notebooks seem nice. From those it seems pretty straightforward to adapt settings etc to a new experiment. But it would be a better resource if the output from running the notebooks would be included. This way one can learn more with different functions do when e.g. scaling data without having to download and run the notebook yourself.

Related to https://github.com/openjournals/joss-reviews/issues/2440

**Comment by mattcai** [comment]
This will be addressed by merging #1892 and solving the readthedocs resource limitations for rendering gallery examples (#1865).

**Comment by neuromusic** [comment]
Thank you for the recommendation, @vals & @shazanfar. I agree that this would be highly valuable, however, we can't support this at this time. The datasets that these notebooks process are quite large and the RAM and time needed to render them far exceeds the resource limits of ReadTheDocs for open source projects. Details are captured in #1865.
