### ISSUE TITLE
Are the masks in the left in the tutorial really two cells?

### ISSUE THREAD

**Issue by vals** [spacetx/starfish#1926]
[ Related to openjournals/joss-reviews/issues/2440 ]

Are the masks in the left of the example in the tutorial two cells? There seems to be two nuclei, but are they two cells? Maybe a different less confusing FOV could be used? Or this could be commented upon in the segmentation section of the Quick Start tutorial.

![image](https://user-images.githubusercontent.com/668803/101120385-80bda200-35bb-11eb-9150-d9be8e8579b1.png)

**Comment by neuromusic** [comment]
Indeed, they are! 

As noted in the quick-start, the cells in this dataset express either the mouse or human ACTB gene, but not both. This can be seen by exploring each of the images in the stack, where you can see that, despite the apparent ambiguity, the segmentation has distinguished between two cells... one expressing the human ACTB and one expressing the mouse ACTB.

**Comment by neuromusic** [comment]
I've added a clarification to the quickstart.
