### ISSUE TITLE
error importing scikit's 'match_histograms'

### ISSUE THREAD

**Issue by juliomateoslangerak** [spacetx/starfish#1932]
#### Description
importing starfish.data fails with AttributeError: module 'skimage.transform' has no attribute 'match_histograms'

#### Steps/Code to Reproduce
```python
from starfish import data
```

#### Expected Results
Might be that the error is in line 4 of copat.py
```python
if version.parse(skimage.__version__) > version.parse("0.14.2"):
```
where the sense of the comparison is inverted. 'match_histograms' is not present in most recent versions of skimage

**Comment by ttung** [comment]
This was in `skimage.transform` between 0.14.2.  It was moved to `skimage.exposure` with 0.16.0.

**Comment by ttung** [comment]
https://scikit-image.org/docs/0.16.x/release_notes_and_installation.html#deprecations
