### ISSUE TITLE
starfish is incompatible with Python 3.9

### ISSUE THREAD

**Issue by ora-lv** [spacetx/starfish#1950]
#### Description
We have not been able to get starfish to work in Python 3.9

#### Steps/Code to Reproduce
Currently the latest version of skimage that starfish is compatible with is 0.15.0 (or 0.15.x)
The oldest version of skimage we were able to pip install on Python 3.9 is 0.16.2

#### Expected Results

We can run starfish on Python 3.9 with a compatible version of skimage (more recent than 0.15.0)

#### Actual Results

We can install skimage 0.18.0 and starfish 0.2.2 on Python 3.9.2, but they are not compatible (running into this issue https://github.com/spacetx/starfish/issues/1887 when running the quick start guide)

Note that there was no actual fix for the issue mentioned, only flagging that the scikit-image version is incompatible with starfish (but now 0.18.0 is available and back to the same issue)

#### Versions

Linux-5.4.89+-x86_64-with-glibc2.31
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]
NumPy 1.19.5
SciPy 1.6.3
scikit-image 0.18.0
pandas 1.2.4
sklearn 0.24.2
xarray 0.18.2
sympy 1.5.1
starfish 0.2.2

**Comment by neuromusic** [comment]
this should be fixed with #1963
