### ISSUE TITLE
AttributeError: 'DataArray' object has no attribute 'flags' in quick start run 

### ISSUE THREAD

**Issue by sebherbert** [spacetx/starfish#1952]
## 🐛 Bug

I followed the [quick start documentation](https://spacetx-starfish.readthedocs.io/en/latest/gallery/quick_start/plot_quick_start.html#sphx-glr-gallery-quick-start-plot-quick-start-py) and ran the [plot_quick_start.ipynb notebook](https://spacetx-starfish.readthedocs.io/en/latest/_downloads/78075d56b7166cb4067f9dd8720da573/plot_quick_start.py).

It seems to be the same problem as #1887 (closed) and  #1946 (open), but I'm not entirely sure I understood if that PR will be merged so I prefer opening a new issue, feel free to close it if I just have to wait :) 

## To Reproduce

Exactly the ones described in the quick start. 
1. conda create -n starfish "python=3.7"
2. pip install starfish
3. pip install seaborn
4. Run the plot_quick_start.ipynb until the Run pipeline cell

#### Actual Results
Error is: (Full notebook state is [traceback.txt](https://github.com/napari/napari/files/6703432/traceback.txt))
AttributeError: 'DataArray' object has no attribute 'flags'

#### Versions
Linux-5.4.0-74-generic-x86_64-with-debian-bullseye-sid
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0]
NumPy 1.21.0
SciPy 1.7.0
scikit-image 0.18.1
pandas 1.2.5
sklearn 0.24.2
xarray 0.18.2
sympy 1.5.1
starfish 0.2.2

Let me know if I can add anything or if there's a simple fix on my side.

**Comment by kevinyamauchi** [comment]
Hey @sebherbert , it's great to see you here! It could be worth taking a look at https://github.com/spacetx/starfish/pull/1951, which might fix this issue.

If you'd like to give that PR a go before it merges with master, you could [check the PR out locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally) and install. I am happy to provide more more detailed instructions if that would be helpful!

**Comment by sebherbert** [comment]
Hi @kevinyamauchi! 
Thanks for the suggestion and offer! I can't test it today, but I'll definitely try that next week!

**Comment by sebherbert** [comment]
So it's better but still doesn't entirely :)

Just to be clear on my progress:
Locally checked out the #1951 PR using gh
- `gh repo clone spacetx/starfish`
- `gh pr checkout 1951`
Created a fresh conda repo `conda create -n starfish "python=3.7"`
Installed StarFish from source `python3 -m pip install`
Installed Seaborn `pip install seaborn`

I ran again the provided plot_quick_start notebook and obtained an error at the same "run the pipeline" cell. Registration of the image worked, but the "find_spots" function crashed. See 
[traceback_PR1951.txt](https://github.com/spacetx/starfish/files/6726521/traceback_PR1951.txt)


I'll try to see if I can understand why.

**Comment by sebherbert** [comment]
Ok... TLDR the PR is indeed fixing my issue :)

I've rebuild from git and it now works perfectly (`python3 -m pip install .`)
It's using `pip install starfish` that doesn't work. Maybe this needs more time to update?

Thanks for the fix! I'll now be able to continue testing the other examples!

**Comment by kevinyamauchi** [comment]
Awesome! Thanks for letting us know, @sebherbert . Indeed, we have not made a new release, so the version on pypi is "behind" the current master.

In light of your comment, I will close this issue. Please feel free to re-open it if the issue re-emerges.
