### ISSUE TITLE
Unable to run dev install on Mac M2 

### ISSUE THREAD

**Issue by ctcisar** [spacetx/starfish#2004]
Trying to set up a dev starfish install in a fresh conda environment with Python 3.8 fails on a Mac M2.

The line `make install-dev` generates the following output: [uyen_install_error.txt](https://github.com/spacetx/starfish/files/11194667/uyen_install_error.txt)

This error also occurs if numpy is installed first via `pip install numpy`.

I am currently building packages manually for linux/arm64 to see if I can get around this. I suspect this issue might be due to old packages being pinned in `requirements/REQUIREMENTS-CI.txt`

**Comment by karchern** [comment]
Do you have any news on this? I'm running into the same issue as you.

**Comment by shachafl** [comment]
Resolved with PR #2009
