### ISSUE TITLE
How can I do 3D spot detection or 3D decoding?

### ISSUE THREAD

**Issue by hziyin** [spacetx/starfish#2010]
Dear starfish developers,
Firstly, thank you for creating such a useful tool for spot detection and decode analysis.
It is said that the spot finding method "BlobDetector" can work in 3D and the spot decoding method "PerRoundMaxChannel" can work in 3D too.
I am wondering if you can provide some examples for 3D spot finding and 3D decoding. It would be appreciated if you could tell more about how spot finding method works in 3D.
Thanks for your help.

**Comment by berl** [comment]
hi @hziyin  
the detection and decoding methods work should in 3D- here's the [example of 3d spotfinding and decoding for smFISH data](notebooks/smFISH.ipynb)
