### ISSUE TITLE
versioneeer.py breaks on installation

### ISSUE THREAD

**Issue by johnfmarkham** [spacetx/starfish#2011]
#### Description

Problem is described here:
https://github.com/EJEP/datapoint-python/issues/183
configparser.SafeConfigParser() and parser.readfp() have been removed.

#### Versions

>>> import platform; print(platform.platform())
Linux-5.14.0-362.18.1.el9_3.x86_64-x86_64-with-glibc2.34
>>> import sys; print("Python", sys.version)
Python 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:35:02) [GCC 11.2.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.26.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.11.4
>>> import skimage; print("scikit-image", skimage.__version__)
scikit-image 0.22.0
>>> import pandas; print("pandas", pandas.__version__)
pandas 2.2.1
>>> import sklearn; print("sklearn", sklearn.__version__)
sklearn 1.4.1.post1
>>> import xarray; print("xarray", xarray.__version__)
xarray 2024.2.0
>>> import sympy; print("sympy", sympy.__version__)
sympy 1.12

**Comment by berl** [comment]
@johnfmarkham  want to make a PR for this? looks like that same thread suggests a fix that might work even with the current repo [here](https://github.com/EJEP/datapoint-python/issues/183#issuecomment-1934818575)

**Comment by johnfmarkham** [comment]
@berl, please excuse my ignorance, what do you mean by "make a PR"?

**Comment by berl** [comment]
@johnfmarkham no problem! it's easy:  
1. fork the repo 
2. make a new branch on your fork, maybe something like `2011-fix-versioneer`
3. fix the problem, maybe using the suggestion from that thread
4. save the changes, make a commit on your new branch and and push (to your fork). now your changes should be in a new branch on your fork of the repo on github. 
5. make a pull request from your fork to `master` on this repo


I'm happy to help more and there are also lots of tutorials around for this kind of workflow

**Comment by shachafl** [comment]
@berl @johnfmarkham I have looked into it (forked and fixed versioneer) but Starfish can't support python 3.12 because of dependency issues (numba, etc).
Once all the main dependencies support python 3.12, we can test.
