### ISSUE TITLE
Error in loading ISS data in quick start tutorial

### ISSUE THREAD

**Issue by rocketeer1998** [spacetx/starfish#2013]
Because of the updating version of scikit-image, `from starfish import data` throws an ImportError. We need to fix three files:
1. In `site-packages\starfish\core\image\_registration\LearnTransform\translation.py`, change from `skimage.feature.registration_translation` into `skimage.registration.phase_cross_correlation`
2. In `site-packages\starfish\core\morphology\Filter\min_distance_label.py`, change from `skimage.morphology.watershed` into `skimage.segmentation.watershed`
3. In `site-packages\starfish\core\morphology\Segment\watershed.py`, change from `skimage.morphology.watershed` into `skimage.segmentation.watershed`

**Comment by rocketeer1998** [comment]
And why not update the corresponding arguments in the most recent release?

**Comment by shachafl** [comment]
@rocketeer1998 there is an open PR #2009 that addresses this and needs to be reviewed and merged into the master branch. 
For now you can either:
1) For scikit-image 0.21, fork my branch: git clone -b python3.8 https://github.com/shachafl/starfish.git
2) For scikit-image 0.18.3, use the master branch in a clean virtual environment and execute `make install-dev`

**Comment by shachafl** [comment]
Resolved with PR #2009
