### ISSUE TITLE
Research: CLI and API parameters are defined once and used for both calls. 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#218]
Currently, starfish defines both API and CLI parameters, both of which can declare default paramters and help strings. 

We'd like to harmonize this, ideally by programming the information into the API and automatically generating the CLI. 

Tony thought it might be possible to do this with a decorator, but wants to experiment with how that could affect usability.

**Comment by shanaxel42** [comment]
I know we just switched everything to click, but https://github.com/epsy/clize seems pretty nice. It takes the params and help strings from the docblocks of your api method and creates an equivalent cli command.

**Comment by joshmoore** [comment]
Certainly seems like what `clize` is doing is the type of synchronization that this issue refers to. I'd _imagine_ that writing a decorator to parse the function and generate `click`-bindings would be doable. Leave it to everyone else to first decide if moving away from click is the thing to do.

**Comment by neuromusic** [comment]
See also https://github.com/AllenInstitute/argschema

**Comment by joshmoore** [comment]
@neuromusic : very nice! I _still_ leave it to the wider community if they can give up `click` (since it was the explicit ❤️ for `click` which led to the migration), but `argschema` does seem to cover both this issue as well as my addition of `starfish.util.config` (assuming all config keys would be passable via the command-line). Perhaps a bridge between `argschema` and `click` (or similar) would be possible?

**Comment by neuromusic** [comment]
@joshmoore: of course. I :heart: `click` on many levels.

> Perhaps a bridge between `argschema` and `click` (or similar) would be possible?

Going to tag @fcollman here to see if he wants to weigh in.

**Comment by fcollman** [comment]
so one concept that I have a branch for but haven't fully written out is to define an arbitrary source for dictionaries, of which json and argparse are simply two examples.  The idea being that module writers should define their input parameters once, and then system's engineers can worry about writing converters to different interface methods... of which command line arguments is one, maybe messages from a messaging system is another, maybe json files is a third, etc etc etc.   I think I've already successfully built dynamic definitions between marshmallow schemas and argparse objects, and sphinx autodoc, and even sqlalchemy models, so I'm guessing it wouldn't be too hard to write one for click classes.. and then argschema is simply the mechanism centralized place where these dictionaries of different sources come together and are validated.  

https://github.com/AllenInstitute/argschema/tree/input_source_2

this is the branch that does this... I need to prioritize getting this actually finished as it will be a minor breaking change to the API, so I wanted to put it in argschema 2.0.

**Comment by shanaxel42** [comment]
closing this in favor of "Do we need cli question"
