### ISSUE TITLE
Investigate "dots" image vocabulary

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#220]
We generate a bunch of "dots" images that represent bright spots in the image. These are typically max projections over some subset of the data. Brian long suggested we might want to store some information on how such projections were created (e.g. max projection over z? z, h, and c? 

Determine how to store this data in starfish and the starfish spec.

**Comment by ttung** [comment]
maybe max-proj-{axes-list, sorted}

**Comment by ambrosejcarr** [comment]
I like it, except I'd be verbose: maximum-projection-{axes-list, sorted}

**Comment by ambrosejcarr** [comment]
Now that we use xarray, we can store arbitrary metadata on the DataArray object. I also opened #449 because I think max projection should generate a new ImageStack. It could be possible to store such information on the provenance of the new imagestacks in the attrs field. That would be really neat, as users would be able to see how their data was processed.

**Comment by ambrosejcarr** [comment]
@shanaxel42 how hard would it be for max_proj to be recorded in the log? I think that's all that is left to close out this issue.
