### ISSUE TITLE
PipelineComponents need some kind of class docs

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#233]
e.g., right now the classes in `__init__.py` for each `pipeline_component` look something like this: 

```python
class PixelSpotDetector(PipelineComponent):

    pixel_finder_algorithm_class = None
    pixel_finder_group: argparse.ArgumentParser

    @classmethod
    def implementing_algorithms(cls):
        return _base.PixelFinderAlgorithmBase.__subclasses__()

    @classmethod
    def add_to_parser(cls, subparsers):
        """Adds the pixel finder component to the CLI argument parser."""
        ...
```

We could use some Docs explaining how these work!

**Comment by ttung** [comment]
also relevant: guidelines into pipelinecomponents about what belongs in a pipeline component constructor and what belongs in the run(..) method

**Comment by ambrosejcarr** [comment]
Also needed: How to extend them, how to use them.
