### ISSUE TITLE
ImportError: no module named constants

### ISSUE THREAD

**Issue by bbqrebs** [spacetx/starfish#235]
I'm trying to run go through the instructions in the readme from command line. After pip installing starfish, when I try to run get_iss_data.py, I get the above error from the line 
`from starfish.constants import Coordinates, Indices`

Any suggestions on how to fix this?

**Comment by ttung** [comment]
I released a new version of the starfish package.

**Comment by bbqrebs** [comment]
After updating starfish, this is the error I'm getting now:
<img width="479" alt="starfish error" src="https://user-images.githubusercontent.com/33011037/40927566-ab805980-67e4-11e8-9f69-6c7b40e516e6.png">

**Comment by ttung** [comment]
Are you running python 3.6?

**Comment by ambrosejcarr** [comment]
Hey, thanks for posting the error! Starfish requires python 3.6, which is the source of your problem. That error is from [PEP526](https://www.python.org/dev/peps/pep-0526/), which allows static type hinting. 

What operating system are you running on? We can try to add some simple installation workflows for python 3.6 for common operating systems.

**Comment by bbqrebs** [comment]
Oh ok, I will try again after installing python 3.6. I am running on linux (Ubuntu). Thanks!

**Comment by bbqrebs** [comment]
I am waiting for an administrator to install Python 3.6, but I temporarily switched over to a Windows machine. Now I can download the data, but I run into problems when I try to register the images.
<img width="749" alt="register1" src="https://user-images.githubusercontent.com/33011037/40933721-f91d4b9a-67f7-11e8-897a-0395f10ae6cb.png">
<img width="751" alt="register2" src="https://user-images.githubusercontent.com/33011037/40933724-fe984eda-67f7-11e8-8635-3bda2837978f.png">

I made sure the json file was saved to the right place. Any idea why this is happening?

**Comment by ttung** [comment]
We haven't done any validation against Windows.  The shortest path to getting this working is probably running this on Window's linux compatibility layer (https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by ambrosejcarr** [comment]
@bbqrebs Did Tony's fixes get this working for you?

**Comment by bbqrebs** [comment]
@ambrosejcarr  I'm still working with a system admin to try to get python 3.6 on the linux machines, but if that doesn't work, I will try the Linux subsystem on Windows.
