### ISSUE TITLE
ImportError: No module named pip 

### ISSUE THREAD

**Issue by rania199730** [spacetx/starfish#236]
# guys
i have problem when trying to install Trity 
it shown these
 
Using /usr/lib/python2.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip
Traceback (most recent call last):
  File "install.py", line 31, in <module>
    import pip
ImportError: No module named pip

i tried all solvents in the internet nothing work

**Comment by ttung** [comment]
Sorry, I don't follow your question.  Can you try restating it?

**Comment by ambrosejcarr** [comment]
It may help us understand better if you could show both the command you executed and the error that was produced.

Thanks!

**Comment by rania199730** [comment]
after downloading Trity and choosing the option 1 this what i got 

[>] Select Operating System: 1
[*] Loading...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Searching for pip
Best match: pip 9.0.1
Adding pip 9.0.1 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip
Traceback (most recent call last):
  File "install.py", line 31, in <module>
    import pip
ImportError: No module named pip

**Comment by rania199730** [comment]
i tried to install pip using 
`pip install pip`
but it is alreddy installed :: 

`Requirement already satisfied: pip in /usr/lib/python2.7/dist-packages`

**Comment by ambrosejcarr** [comment]
Apologies, as developers of the `starfish` package, `Trity` installation is not something we're able to support.

**Comment by ambrosejcarr** [comment]
@rania199730 I'm going to close this. If you feel it needs to be reopened please feel free to add additional detail clarifying how we can improve `starfish` to make it more usable.
