### ISSUE TITLE
improve synthetic data generation

### ISSUE THREAD

**Issue by sofroniewn** [spacetx/starfish#243]
After talking with @ambrosejcarr - there are a number of improvements that could be made to the current simulation code. They are 

- [x] Add support for 3D data, do by modifying placement of spots to be in 3D and add anisotropic gaussian filter to simulate PSF

- [ ] Add jitter to xyz location of spots across hybridization rounds, do for each spot independently, want to be a parameter that can be set to 0

- [ ] Make minimum separation distance between points (i.e. so no two points are too close together) to ensure spot detection is 100% accurate on 'easy' data - could be done by first generating list of points and then discarding close ones, and if necessary adding in extras until a desired number of points is obtained

- [ ] Add code for generating cell images and having spots clustered into cells. This could be used to test cell segmentation code. Could be very simple, like blobs, or could be generated through a neural network

- [x] Allow user to specify different types of codebooks (including error correction)

**Comment by ambrosejcarr** [comment]
@mbabadi This is the simulation ticket we were suggesting could be a cool place for you and Luca to start.

**Comment by ambrosejcarr** [comment]
Something worth adding -- right now the simulations are quite slow at producing complete ImageStacks. I believe this is due to Poisson random number generation. Anything that could be done to speed this up would speed up our testing, and be a great help!

**Comment by ambrosejcarr** [comment]
@40577552

**Comment by dalessioluca** [comment]
I can look into this issue - Luca.
