### ISSUE TITLE
Check in versioned spaceTx specification

### ISSUE THREAD

**Issue by berl** [spacetx/starfish#282]
@ttung  just putting this down somewhere so it doesn't get lost in the email thread- it was your idea!

**Comment by ambrosejcarr** [comment]
I've made a significant edit to the [spec](https://docs.google.com/document/d/12V-BQF-wh1GDBXwUH2hQrPhw6n0oQqENPK-YHGv59w4/edit#heading=h.l7xxxky10oy0). It could use a review from @ttung @berl and @dganguli .

**Comment by ambrosejcarr** [comment]
Closed by spacetx/sptx-format#1
