### ISSUE TITLE
get_algorithm_name should mirror the class name

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#283]
@ttung since we've agreed to switch from

```from starfish.pipeline.filter.white_top_hat import WhiteTopHat``` 

to 

```from starfish.pipeline.filter import Filter``` 

I've realized that the name of the algorithms that populate the `Filter` object are the ones that we define in `get_algorithm_name`, not the name of the class itself. 

What do you think about mandating that `get_algorithm_name` return the name of the class, so that the name that is called stays consistent with the method in the codebase?

**Comment by ttung** [comment]
If that's the case, we don't even need the method. Just do class.__name__

**Comment by ambrosejcarr** [comment]
I am in favor of any reduction in complexity, and see no reason why we would want to use anything other than the class name. I'll file this away as a todo.

**Comment by ambrosejcarr** [comment]
closed by c1a36f3
