### ISSUE TITLE
Stack vs ImageStack in allen_smFISH notebook on master

### ISSUE THREAD

**Issue by berl** [spacetx/starfish#299]
This is passing a Stack to the SpotFinder, but the SpotFinder is expecting an ImageStack.  Is there any easy conversion between the two?

from starfish.pipeline.features.spots.detector import SpotFinder
kwargs = dict(...)
lmpf = SpotFinder.LocalMaxPeakFinder(**kwargs)
spot_attributes = lmpf.find(s)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-38711b2bfea0> in <module>()
     16 )
     17 lmpf = SpotFinder.LocalMaxPeakFinder(**kwargs)
---> 18 spot_attributes = lmpf.find(s)

c:\users\synbio\documents\starfish\starfish\pipeline\features\spots\detector\local_max_peak_finder.py in find(self, stack)
    122             Stack where we find the spots in.
    123         """
--> 124         spot_attributes: List[SpotAttributes] = stack.apply(
    125             self.find_attributes, in_place=False, is_volume=self.is_volume, verbose=self.verbose)
    126 

AttributeError: 'Stack' object has no attribute 'apply'

**Comment by ttung** [comment]
Use the .image attribute to get an ImageStack from a Stack

**Comment by berl** [comment]
yep, just figured that out.
