### ISSUE TITLE
Errors when using example notebooks

### ISSUE THREAD

**Issue by ebouilhol** [spacetx/starfish#300]
Hi,
I tried a few notebooks and I can't rich the end of anyone I tried.
Let's focus on the allen_smFISH.ipynb here : 
At the step 5 

```
from starfish.pipeline.filter import Filter
s_clip = Filter.Clip(p_min=10, p_max=100, verbose=True)
s_clip.filter(s)
```

I get the following error : 

```
--------------------------------------------------------------------
AttributeError                     Traceback (most recent call last)
<ipython-input-16-6caa463fd5e6> in <module>()
      1 from starfish.pipeline.filter import Filter
      2 s_clip = Filter.Clip(p_min=10, p_max=100, verbose=True)
----> 3 s_clip.filter(s)

~/Documents/10_starfish/starfish/starfish/pipeline/filter/clip.py in filter(self, stack)
     75         """
     76         clip = partial(self.clip, p_min=self.p_min, p_max=self.p_max)
---> 77         stack.apply(clip, is_volume=self.is_volume, verbose=self.verbose)

AttributeError: 'Stack' object has no attribute 'apply'
```

I use python 3.6 on Ubuntu 18.04
I pulled the starfish repository on monday 02 July 11h.
I didn't change anything in the notebook's code, including the URL for the JSON, to be sure it don't come from my JSON.
(I get the same error if I try to launch it on other data)

Thanks for your help,

Emmanuel

**Comment by ttung** [comment]
@ambrosejcarr do you know if the allen_SMFISH notebook is up-to-date?

**Comment by ambrosejcarr** [comment]
I'll be able to take a look tomorrow on the plane. This issue suggests not. @ebouilhol sorry for the slow response, I'm out on vacation this week. 

I think as a part of "get the notebooks working again" I should write tests for each notebook similar to the iss one.

**Comment by ambrosejcarr** [comment]
- Looks like when we extracted stack from filters the allen_smFISH notebook got missed. #307 provides a fix.
- MERFISH will take a bit longer to fix, as I'd like to finish #304 before wrangling the outputs. 
- [ISS](https://github.com/spacetx/starfish/blob/master/notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb) is currently working, if you want to look at a functional example @ebouilhol

**Comment by ebouilhol** [comment]
> ISS is currently working, if you want to look at a functional example


Okay, thanks a lot, I switch on ISS then !

**Comment by ambrosejcarr** [comment]
> Okay, thanks a lot, I switch on ISS then !

Thanks for noticing the broken notebooks. 👍
