### ISSUE TITLE
make a local pipeline runner

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#311]
Starfish users will expect to be able to process multiple FOVs efficiently, but at the moment we are focusing on single FOVs. 

The simplest multi-field of view orchestration would be to process them sequentially with a for loop. More sophisticated would be a multi-processing based approach. Finally, we will want to link with the HCA cromwell/wdl architecture. 

Design an API to enable these kinds of multi-field of view processing. This will interact with #310 and depends on #302

**Comment by ttung** [comment]
@berl Would love your feedback if you get a chance.  https://github.com/spacetx/starfish/pull/1160/files#diff-7fddd31cfc49ca7f1ce96c1e0d2cc138 is an example of a recipe.
