### ISSUE TITLE
data typing

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#316]
Do we use uint16 everywhere?
Do we force algorithms to declare what the data types for each input / output will be?
Wild west?

**Comment by ttung** [comment]
See discussion starting around https://spacetx.slack.com/archives/CAR91U354/p1531262002000193

**Comment by kevinyamauchi** [comment]
Hey! I wanted to follow up on this issue. I am implementing some filters and was wondering if you decided how image data type is going to be handled. Should we add a function decorator, as suggested by Ambrose? Or will there be some sort of type check upon ingestion and then an assumed data type throughout the pipeline. 

Sorry if I missed something - I'm trying to follow along with the Slack, but I'm a bit behind.

**Comment by kevinyamauchi** [comment]
Sounds great. I will try to take a look at skimage's typing before tomorow's sync. Thanks!

**Comment by ttung** [comment]
My proposal:

The internal representation in starfish should default to float (32 or 64 is definitely debatable).  To be added:

1. A pipeline component to format input data into float, with an optional param to manage non-linear mappings.
2. A decorator that a specific algorithm implementation can utilize, which will inspect the input data and converts it to the requested type, and the results back to float.  There are optional params to manage non-linear mappings in each direction.

Some examples of (2):

This will convert the internal data type (float) to np.uint32, and the results will be returned to float.  All conversions are linear.
```
@datatype(np.uint32)
def run(..):
```

This will convert the internal data type (float) to np.uint32, and the results will be returned to float.  Converting from float to np.uint32 will be done with the scaling algorithm provided by XXX, and converting from np.uint32 to float will be done linearly.
```
@datatype(np.uint32, in_scaling=XXX)
def run(..):
```

This will convert the internal data type (float) to np.uint32, and the results will be returned to float.  Converting from float to np.uint32 will be done with the scaling algorithm provided by XXX, and converting from np.uint32 to float will be done with the scaling algorithm provided by YYY.
```
@datatype(np.uint32, in_scaling=XXX, out_scaling=YYY)
def run(..):
```

**Comment by kevinyamauchi** [comment]
Thanks Tony for the proposal and clear examples! I think the proposal looks good. I have a couple of comments below. I look forward to discussing further.

- In addition to non-linear mappings, I think the input pipeline component needs to perform linear conversions for ranges that are less than the full range indicated by the datatype. For example, some microscope cameras output  12 bit data in 16 bit images. I am not sure if the range should be an input argument or added to the metadata (the later seems better, as that should probably be preserved as part of the record).
- skimage has a bunch of [conversion functions](https://github.com/scikit-image/scikit-image/blob/master/skimage/util/dtype.py). Perhaps we can implement some of these in the dataype decorator?
- For the internal data type, should we use the same ranges as [defined by skimage](http://scikit-image.org/docs/dev/user_guide/data_types.html)? I think this makes sense, as it will make interfacing with skimage easier and we already have a lot of skimage dependencies.

**Comment by ttung** [comment]
Conversions for ranges that are less than the full range == nonlinear.  If you draw the input-output in an x-y graph, you will notice it's a straight line, followed by a bend, and another straight line. :)

**Comment by kevinyamauchi** [comment]
Just to record the outcome of our meeting yesterday: we decided to implement Tony's proposal and use float32 as the internal datatype.

Also, who is going to make the function decorators and pipeline tools?

**Comment by ttung** [comment]
> Also, who is going to make the function decorators and pipeline tools?

I think that's on me.

**Comment by ttung** [comment]
#501 switches the pipeline to float32.  Follow up tasks: #547, #549, #556
