### ISSUE TITLE
Codebook change suggestion: "gene_name" -> "molecular_target" 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#327]
This modification to the codebook would make it more general if we ever wanted to use it to specify non-gene molecules (transcripts, exons, cytoskeleton, etc... )

**Comment by dganguli** [comment]
how about simply 'target' instead of 'molecular_target? and while we're at it, what about re-naming h (for hybridization round) to r (for simply, round). both changes make the terminology more general across methods, e.g., it's just as awkward to talk about hybridization when dealing with in-situ-sequencing data as it is to talk about genes when you're targeting non-genes molecules.

**Comment by ambrosejcarr** [comment]
I like both of these suggestions. One other thing I brought up in the metadata thread is whether we'd like to support broader parameter inference than we currently do. Right now we say that omission of a (channel, round, value) tuple implies that it's "off".

Do we also want to enable a reduction in verbosity by allowing:

1. Missing "round" = 0. This would simplify the codebook for non-multiplex methods
2. Missing "value" = 1. This would simplify all existing codebooks, as so far, "0" has not been used. 

Also, I'm embarrassed. Per our dartfish converstion, If you wanted to code an explicit blank channel, you could by assigning the channel a number and marking the expected value as 0 each time it was used.

**Comment by dganguli** [comment]
Yeah missing "round" = 0 indeed simplifies codebook for _non-sequential_ non-multiplex methods. and i also agree with a missing "value" being a 1 is a great idea. having a "value" is future-proof as per @ttung suggestion, but we don't yet use it. i think both of these implicit changes are fine as long as they're explicitly communicated.

**Comment by ambrosejcarr** [comment]
Ok, so what would be involved here is:
1. Update to codebook documentation to reflect the change
2. Update to codebook code to use the default values
3. Update to spec to explain how this works

One follow up thought: I would prefer that we strongly encourage implicit use only in cases where they parameter can be completely omitted.

E.g. I dislike the below 2-round 1-channel codebook, and would prefer an 'r': 0 in the first line. 

```
codeword: [
  {'c': 1},
  {'c': 1, 'r': 1}
]
```

**Comment by ttung** [comment]
Love the gene -> target rename.
Love the hybridization -> round rename.

Making value optional is iffy to me because we already omit value=0.
Making round optional if it's entirely not present seems great.  Making it optional generally seems meh.

**Comment by ambrosejcarr** [comment]
> Making value optional is iffy to me because we already omit value=0.

I can see why you're concerned. What if we posed this more concretely? There could be two cases: binary codebooks and continuous-valued codebooks (we can have a flag, if we really want to make this explicit instead of inferring which is which)

Continuous valued codebook (future, maybe not needed?): 
- if a code specifies a channel/hyb, value must be specified (value is not optional)
- if a channel/hyb combination is omitted, it's value is assumed zero

Binary case:
- value is considered 1 when a channel/hyb combination is listed, 0 when it is not. (value is not used)

I'm not attached to the above separation, and would rather we had a general solution... but I think it's worth trying to find a solution we all like for this. 👍

**Comment by ambrosejcarr** [comment]
Relevant discussion: https://github.com/HumanCellAtlas/metadata-schema/issues/368#issuecomment-406085274
