### ISSUE TITLE
Codebook + IntensityTable Tech Debt

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#329]
- [ ] Reduce verbosity of Constants (do not need Enums)
- [ ] Figure out how to add required attrs (see [extending xarray](http://xarray.pydata.org/en/stable/internals.html#extending-xarray))
- [ ] Figure out how to add new properties (see above) 
- [ ] Reduce number of tests & fixtures. Replace fast/simple fixtures with factories for simplicity. 

@ttung @dganguli please add anything else here when you find something you don't like while using the new xarray-based objects.

**Comment by ttung** [comment]
Generally speaking, it would be helpful to understand what issues you're coming up against with xarray.  If there are discussions about this, links to them would be really helpful.

**Comment by ambrosejcarr** [comment]
Good point. I will add some tracebacks with examples of the issues I'm seeing. So far, at a high level: 

1. problems with my decision to subclass `xarray.DataArray`: 
  a. can't modify `__init__` because many class methods use it to general sub-objects (e.g. `DataArray.max`
  b. can't add `@property` methods (something about the object state -- I need to investigate this further)

**Comment by ambrosejcarr** [comment]
There are some cases where operations on the IntensityTable, for example `groupby` operations, will take the IntensityTable `features` multiindex and convert it into an `Object`. This makes interacting with the data in the converted object very difficult and obscures the resulting object names (e.g. `target`). 

We need to get in touch with the xarray devs about the status of multiindexes and ask them if there are alternative ways of representing indexes over the dimensions of the xarray that don't suffer this from this issue (and other serialization problems).
