### ISSUE TITLE
Add a progress bar to stack.read()

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#356]
This is probably more of a nice to have, but it would be really helpful if there was a progress bar for stack.read(). When loading/downloading large images (e.g., the Allen smFISH notebook) it nice to know how it is progressing.

**Comment by ambrosejcarr** [comment]
This makes sense to me. Tagged @ttung, since this is definitely in his realm of expertise.

**Comment by kevinyamauchi** [comment]
I'd like to have a progress bar for Jupyter notebooks. However, I wouldn't complain if you also added one for the CLI :P

**Comment by ttung** [comment]
https://github.com/tqdm/tqdm

this looks like it supports both CLI and jupyter.

**Comment by ambrosejcarr** [comment]
Cool! We're already using it in the API and Jupyter. :)

**Comment by ttung** [comment]
Fixed by #437
