### ISSUE TITLE
Decide if we want to implement a ConnectedComponentsSpotDetector

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#369]
See https://github.com/spacetx/starfish/pull/357#issuecomment-410331350 for discussion

> [snip] ... ConnectedComponentsSpotDetector can also be a 'thing' in this module that extends SpotFinderAlgorithmBase. It's image_to_spots function binarizes the image, runs a connected components algorithm, filters out identified regions that don't meet an area or intensity threshold, and otherwise operates the same as the other two spot detectors. This is only slightly different than how it's used in pixel based readout in features.pixels.

**Comment by kevinyamauchi** [comment]
I think it would be nice to have a connected components spot detector. Generally, they're pretty fast and I hypothesize they would be useful for detecting spots from pixel-wise decoded images (which could be decomposed into a set of binary images).

**Comment by dganguli** [comment]
we do have a connected components labeler to support pixel wise decoding methods. however, in the codebase, it's in features.pixels.combine_adjacent_features (next to features.pixels.pixel_spot_detector). combine_adjacent_features does not explicitly follow the same API as what's in pixels.spots.detector._base, even though the former is indeed a spot detector. 

all of this unpleasantness arises from the difference between 'spot detection' based pipeline (ImageStack -> Spots -> Decode) vs. a 'pixel detection' based pipeline, which inverts spots and decode (ImageStack -> Decode -> Connected Components Spos Detection). 

I wonder if, for the former 'spot detection' pipeline, we'd still want a connected components labeler as a spot labeling strategy? For example, for MarcoFISH, you could imagine running skimage.blob_log, trackpy.locate, OR skimage.label on the (binarized) 'dots' image. We currently do not support the latter. Should we? If so, we can re-factor the existing code to easily do so in a manner that obviates features.pixels.

**Comment by dganguli** [comment]
@kevinyamauchi ^^^

**Comment by kevinyamauchi** [comment]
Thanks for the explanation, @dganguli. I think it is useful to have a connected components labeler for the spot detection pipeline. This is how the earlier Arjun Raj smFISH papers detected spots (LoG + connected components blob detection) and I think it can work well if there is good spot contrast. I think MarcoFISH is a great candidate given the high SNR.

With regards to refactoring, do you mean pulling the connected components labeling out of features.pixels.combine_adjacent_features and add it as a detector component? As I understand it, pixel-wise decoding + spot detection is implemented as a single component (PixelSpotDetector). Is this right? 

I think it makes sense to separate pixel-wise decoding and spot detection. In general, I think of pixel-wise decoding as a filter. The input is a [round, channel, z, x, y] array and the output is a [target, z, x, y] array. We would then run any spot detector on the [target, z, x, y] array. In addition to decoding barcoded probes, I would be interested in experimenting with a "decoder filter" to reject autoflourescent particles (e.g., if the autofluorescence is present in multiple channels and the probes are only in one each). Thoughts?

**Comment by berl** [comment]
@kevinyamauchi @dganguli I think we should support spotfinding and decoding in arbitrary order for both pixels and particles.  Nice example @kevinyamauchi... rejection of particular swaths of r,c space could be useful before or after spot finding.
