### ISSUE TITLE
Make out-of-place computation the default

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#384]
- Make in-place=False the default for apply loops and filters in `ImageStack`.

**Comment by ttung** [comment]
Why does it suck?

**Comment by ambrosejcarr** [comment]
It's great for memory utilization when the algorithms are designed to do piecewise in-place computation, but makes it much harder to develop/debug in interactive sessions.

**Comment by ttung** [comment]
Interesting.  I bet that internally, the algorithms are not in-place anyway.

**Comment by ambrosejcarr** [comment]
I believe this can now be closed.

**Comment by ambrosejcarr** [comment]
Reopening because in-place is still default -- originally the ticket was closed because out-of-place is now _possible_ everywhere, but the default still needs to be changed.
