### ISSUE TITLE
Make a starfish citation

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#399]
The readme should have instructions on how to cite starfish.

**Comment by ambrosejcarr** [comment]
Seems most packages have actual publications to point to, however the scipy library suggests something like the below: 

Ganguli D, Tung T, Carr AJ, Axelrod S, Freeman J. Starfish: Open Source Image Based Transcriptomics and Proteomics Tools, 2018-, http://github.com/spacetx/starfish [Online; accessed 2018-08-19].

Here’s an example of a BibTeX entry:

@Misc{,
  author =    {Deep Ganguli, Tony Tung, Ambrose J Carr, Shannon Axelrod, Jeremy Freeman, and  others},
  title =     {{Starfish}: Open Source Image Based Transcriptomics and Proteomics Tools},
  year =      {2018--},
  url = "http://github.com/spacetx/starfish",
  note = {[Online; accessed <today>]}
}

See also: https://www.scipy.org/citing.html

@dganguli @ttung thoughts?

**Comment by ttung** [comment]
Seems reasonable?  Alphabetically sort the contributors and 👍

**Comment by ambrosejcarr** [comment]
Closed by #467
