### ISSUE TITLE
Code that loads Experiments and ImageStacks should do a soft verification of data formats

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#400]
ACs: 
- Existing files validate
- Reconcile any non-validating data

**Comment by joshmoore** [comment]
see gh-516 for a proposal for validating via pytest

**Comment by ttung** [comment]
Full verification (i.e., checking that checksums match the data) would break lazy loading, so we only want to verify the metadata other than checksums.

**Comment by joshmoore** [comment]
i.e. the STRICT env variable in gh-538 should also have (or default to?) a lazy setting?

**Comment by ttung** [comment]
Is this done?  I strongly suspect it is...?

**Comment by joshmoore** [comment]
For everything run by travis, `STARFISH_STRICT_LOADING=true` which does validation of just the json and doesn't break lazy loading. So for anything we can validate via `validate_sptx.validate`, then yes, it's done.

**Comment by ambrosejcarr** [comment]
Are our `ENV` variables documented somewhere? I'm having difficulty finding them.

**Comment by joshmoore** [comment]
@ambrosejcarr : were you thinking a section under https://spacetx-starfish.readthedocs.io/en/latest/API/index.html? or perhaps a new section?

**Comment by joshmoore** [comment]
will do once gh-900 and gh-789 land.

**Comment by joshmoore** [comment]
see: https://github.com/spacetx/starfish/pull/901
