### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#41]
This project needs some documentation style guidelines, preliminary documentation, auto-generation of documentation, and a statement in the contribution.md about how to build new documentation.

An example of a project that does this well: https://dask.pydata.org/en/latest/

**Comment by ambrosejcarr** [comment]
When you document the code base, If you would find it useful to have outside eyes on the project, I'd be willing to review the PR.

**Comment by ambrosejcarr** [comment]
https://numpydoc.readthedocs.io/en/latest/

**Comment by ttung** [comment]
https://github.com/spacetx/starfish/tree/tonytung-docs is basically as far as i got.
