### ISSUE TITLE
Convert existing jupyter notebooks into unit tests

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#43]
The notebook repository will contain several examples of how to use Starfish to analyze data from several assays, e.g., MERFISH, DARTFISH, Padlock Probes, sequential smFISH, etc.

While these notebooks provide direct examples of how to use the Starfish API, they can also be re-factored into unit tests such that developers can make sure they're not making breaking changes.

Developers will also need to make sure that the Jupyter notebooks are sufficiently updated if the corresponding unit tests need to be updated.

**Comment by dganguli** [comment]
The notebook repository will contain several examples of how to use Starfish to analyze data from several assays, e.g., MERFISH, DARTFISH, Padlock Probes, sequential smFISH, etc.

While these notebooks provide direct examples of how to use the Starfish API, they can also be re-factored into unit tests such that developers can make sure they're not making breaking changes.

Developers will also need to make sure that the Jupyter notebooks are sufficiently updated if the corresponding unit tests need to be updated.

**Comment by dganguli** [comment]
As of writing this, there's one example notebook. However, after issues  #54 #55 #56 #57 are completed there will be more work to do!

**Comment by ambrosejcarr** [comment]
@ttung Does this mean that all of our notebooks now execute successfully on master?

**Comment by ttung** [comment]
Ok I'll reopen.

**Comment by ttung** [comment]
@shanaxel42  did this.
