### ISSUE TITLE
Verify conda compatibility

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#44]

**Comment by joshmoore** [comment]
I've pushed my branch to https://github.com/joshmoore/bioconda-recipes/tree/starfish. Happy to keep it up-to-date but would either need a heads up in Slack or tag for each of https://github.com/spacetx/starfish/commits/master/setup.py so that I can follow the RSS feed.

**Comment by joshmoore** [comment]
https://github.com/spacetx/starfish/releases/tag/0.0.10 cheers. Now following https://github.com/spacetx/starfish/releases.atom

**Comment by joshmoore** [comment]
Hit the first blocker. All prereqs must also be available in bioconda, so I started packaging showit, slicedimage and regional. For slicedimage:

```
Error: bad character '-' in package/version: 0.0.24-dev
```

Thoughts on having a non `-dev` version?

**Comment by ambrosejcarr** [comment]
You know, I've seen lots of `0.0.24rc2` and similar. Perhaps this is why? Should we try `0.0.24dev` first?

**Comment by ttung** [comment]
I think we should somehow get travis testing w/ conda.  Maybe set up an environment, install starfish, and test that we can at least invoke the cli?

**Comment by joshmoore** [comment]
> You know, I've seen lots of 0.0.24rc2 and similar. Perhaps this is why? Should we try 0.0.24dev first?

https://www.python.org/dev/peps/pep-0440/ suggests:

```
[N!]N(.N)*[{a|b|rc}N][.postN][.devN]
```

> I think we should somehow get travis testing w/ conda. Maybe set up an environment, install starfish, and test that we can at least invoke the cli?

I'd suggest step one would be an environment.yml file, which can also download from pip etc. Then either travis could consume that or it could be consumed in the Dockerfile or another Dockerfile.

My goal with the bioconda recipces would then be to reduce the need for the environment file, i.e. `conda install -c bioconda starfish`.

**Comment by joshmoore** [comment]
```
$ cat starfish.yml
name: starfish
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- click
- matplotlib
- numpy!=1.13.0
- pandas>=0.23.4
- pytest>=3.6.3
- requests
- semantic_version
- scikit-image>=0.14.0
- scikit-learn
- scipy
- tqdm
- trackpy
- validators
- xarray
- pip:
  - regional
  - slicedimage==0.0.1
  - showit==1.1.4
$ conda env create -f starfish.yml
...
Successfully built regional slicedimage showit
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.4 requires cython, which is not installed.
Installing collected packages: regional, diskcache, enum34, packaging, slicedimage, showit
Successfully installed diskcache-3.0.6 enum34-1.1.6 packaging-17.1 regional-1.1.2 showit-1.1.4 slicedimage-0.0.1
#
# To activate this environment, use:
# > source activate starfish
#
# To deactivate an active environment, use:
# > source deactivate
#
$ source activate starfish
(starfish) $ python -c "import slicedimage; print(slicedimage.__file__)"
/opt/anaconda/envs/starfish/lib/python3.6/site-packages/slicedimage/__init__.py
```

**Comment by ttung** [comment]
Closing this.  I get the sense that with the docker run ... in `.travis.yml`, we are done?  attn: @joshmoore

**Comment by joshmoore** [comment]
Building starfish into a conda environment is certainly being tested regularly by travis (and it's how I do all my development work).

Probably most important on that front will be whether or not to keep the environment files up to date. An option would be to drop the explicit package list and instead import requirements.yml. It's a bit less conda-y, but unless someone other than me is using the environment files, they are likely to get out of sync.

Otherwise, the bioconda builds I think are a fine _distribution_ mechanism. This is the script I use to bump versions:

```
bioconda-recipes jamoore$ cat bump-starfish.sh
set -eux

curl_sha1(){
    exec curl -sL "$@" | shasum | cut -d ' ' -f 1
}

PROJECT=$1
UPPER=$(echo "$PROJECT" | tr '[:lower:]' '[:upper:]')
VERSION=$2
FILE=${FILE:-recipes/$PROJECT/meta.yaml}
REPO=${REPO:-josh}
BRANCH=${BRANCH:-"${PROJECT}-${VERSION}"}
SHA1=$(curl_sha1 https://github.com/spacetx/$PROJECT/archive/${VERSION}.zip)

# Editing these two lines:
# {% set STARFISH_VERSION = "0.0.16" %}
# sha1: a5b57090d425202dd2bf57693224ec81035972c7
echo Updating with $VERSION and $SHA1
sed -iE "s/"${UPPER}"_VERSION.=.\".*\"/${UPPER}_VERSION = \"${VERSION}\"/" $FILE
sed -iE "s/sha1:.*/sha1: ${SHA1}/" $FILE

# Now process in git
git fetch origin
git checkout -b $BRANCH origin/master
git commit -a -m "Bump ${PROJECT} to ${VERSION}"
git push $REPO $BRANCH
```

which travis could be taught to do if there's interest.

**Comment by ttung** [comment]
is it https://github.com/spacetx/starfish/blob/master/environment.yml?

**Comment by joshmoore** [comment]
Indeed.

**Comment by ttung** [comment]
Could we just put that in a release.sh script that runs `python setup.py sdist upload` and updates this file?

**Comment by joshmoore** [comment]
Yep. I will do something like that the next time I need to bump.
