### ISSUE TITLE
Generate User Stories for spaceTx

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#440]
@mweiden @berl @dganguli @kevinyamauchi @ttung 

Some aspects of image-based transcriptomics experiments have been brought up over the past two months, such as the number of files, the need to process in real time, and the necessity of adding a channel map to the codebook to pair channels to their indices which suggest we could benefit from more complete user stories, and that it would both help us prepare starfish to scale to real experiments, and might help better prepare our HCA collaborators to support an imaging workflow. 

Ideally these user Journeys would ties together aspects of deliverables we're already requesting -- experimental protocols and processing pipelines, with additional nuance of how these function in practice (when does analysis start -- during experimentation or after it completes? if during, what is the unit of data that is processed? When analyzing data, are these particular measurements that the users like to see to select processing thresholds? 

Could we generate two such journeys internally (Brian, Kevin if willing) to serve as examples, and then source additional ones from our collaborators, either as a deliverable for call 1 or call 2?

**Comment by dganguli** [comment]
We may be able to bootstrap off of some old user stories here: https://docs.google.com/document/d/144bG93GZrzdFIcIixso_peOboYNpiFJPlzSMKTR47QU/edit?usp=sharing

And some data volume statistics here:
https://docs.google.com/spreadsheets/d/1axL6v-ulUwD2PhktslNsm_ViFAvPgbHoHHeUWc_Mecw/edit?usp=sharing

**Comment by kevinyamauchi** [comment]
Hey. I'm happy to help with this! However, I'm not sure I totally understand what goes into the "user story" and "Journey". Do you want example pipelines and experimental protocols annotated with why we are doing each step and any friction we've observed? Sorry if it's explained in @dganguli's Google doc, but I don't have permissions to view it :P

**Comment by ambrosejcarr** [comment]
Given @mweiden 's suggestion, perhaps we need to start with outlining what the services do and then have more targeted interviews with users? 

Alternatively, I was envisioning sourcing high-level walk throughs of an experiment as it pertains to starfish and the DCP processing infrastructure. What this means that is it should highlight points of interaction with those services and downplay (very important) aspects of the microscopy protocol and sample preparation. 

Descriptions of, for example, what the data looks like and how it is generated, followed by what you want to do with it and how you want to process it would be very helpful. 

The one that provoked this concern for me is from sequential smFISH. Please note that I'm totally making this up: 

> Brianna is a microscopist doing sequential smFISH experiments. She creates a priority list of markers that she wants to measure and will measure as many of these as she can before her tissue degrades. She begins her experiment by taking some basic images to calibrate the microscope which do not need any processing specific to image-based transcriptomics or starfish. 
>
> Brianna then measures a complete field of view, measuring one color channel and a DAPI nuclear stain in each imaging round. As mentioned, the number of rounds are not known a-priori. After imaging the field of view, the images are registered using the microscope's software and data is uploaded and completely processed to determine the efficacy of clearing and the ability to recognize spots. 
>
> If necessary, parameter tweaks are made, and then the second field of view is imaged. For subsequent fields of view, data is processed every 5 rounds to verify that the imaging parameters are still correct" 
> When the imaging is complete, Briana wants to process her data and call spots. To do this, she will begin by filtering the images ... [ include processing blurb; acceptable to omit if it's just "follow the starfish `iss_processing_notebook.ipynb` workflow].

**Comment by berl** [comment]
@mweiden here are some user stories that I hope are more in line with what you described.  `multiround smFISH contributor` here represents 2-3 groups in our SpaceTx consortium, and some of these would also be more widely applicable across other users.


As a multiround smFISH contributor, I 

1. upload data in ~100GB chunks  (one chunk per round of chemistry) because I need ongoing feedback from the experiment that is only available after a round is analyzed
2. upload data in ~100GB chunks because waiting until the whole experiment is done takes up local storage space and makes upload less convenient(?)
3. analyze each chunk using starfish as soon as it's uploaded
4. merge data from many chunks into a single experiment because each experiment is made up of many rounds
5. merge analysis results from many chunks into a single analyzed experiment using starfish

**Comment by mweiden** [comment]
* @berl thanks for these. This is a good start.
* @ambrosejcarr I like your experiment formulation too. Focusing on the flow of data through the experiment sounds like exactly the right focus.
