### ISSUE TITLE
ImageStack methods should generate new ImageStacks, not numpy arrays

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#449]
Right now, many methods (max_proj, get_slice) extract numpy arrays or xarrays from ImageStack. This is problematic because they're no longer fully-featured image objects. You can't write them, for example. 

I think longer term it would be nice for objects to at least have an option of generating a new ImageStack. Since ImageStacks all expose the underlying array, this feels like an increase in flexibility to me, and would simplify get_slice because the axes labels would remain attached to the object (no need to emit a tuple). The main hiccup would be how to deal with projected axes (e.g. does a max proj of all categorical values produce a (1, 1, 1, y, x) ImageStack?

I like the way that xarray deals with this, which would be (1, 1, 1, y, x) with an option to squeeze out the extra axes (y, x). In the latter case, maybe we emit a non-ImageStack object. 

@ttung @dganguli @shanaxel42  Interested in your thoughts.

**Comment by ttung** [comment]
@shanaxel42 has done this for `max_proj`.  Does it make sense to do this for `get_slice`?  attn @ambrosejcarr  @dganguli

**Comment by ttung** [comment]
If not, we can close this.

I suspect that what you really want to use is the crop methods when you want to produce another ImageStack, which is already present or in PR.
