### ISSUE TITLE
RFC: ImageStack __repr__ 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#463]
We get beautiful `__repr__` and informative commands for IntensityTable and Codebook by virtue of subclassing xarray.DataArray: 

```
    <xarray.IntensityTable (features: 2, c: 3, h: 4)>
    array([[[    0.,     0.,     0.,     0.],
            [    0.,     0.,  8022., 12412.],
            [11160.,  9546.,     0.,     0.]],

           [[    0.,     0.,     0.,     0.],
            [    0.,     0., 10506., 10830.],
            [11172., 12331.,     0.,     0.]]])
    Coordinates:
    * features   (features) MultiIndex
    - z          (features) int64 7 3
    - y          (features) int64 14 32
    - x          (features) int64 32 15
    - r          (features) float64 nan nan
    * c          (c) int64 0 1 2
    * h          (h) int64 0 1 2 3
      target     (features) object 08b1a822-a1b4-4e06-81ea-8a4bd2b004a9 ...
```

What information would we want to expose to users of ImageStack? To start, we could simply delegate to the xarray.DataArray (replacing `xarray.DataArray` with `ImageStack.xarray`), with an option to display the `extras` associated with it?

**Comment by dganguli** [comment]
what are extras? I love the __repr__ xarray provides. at bare minimum, ImageStack should also provide that.

**Comment by ambrosejcarr** [comment]
extras are the optional metadata field we let users dump stuff into in case we forgot about it in the spec. Could be unwieldy to expose, upon second thought.
