### ISSUE TITLE
Watershed throws difficult to parse error when no cells are identified

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#468]
# Objective
Starfish watershed currently throws difficult to parse errors when no cells are detected. Watershed, and all other segmentation methods should succeed, return with no cells identified, and emit a specific warning. 

## Acceptance Criteria
- Zero-cell cases are tested under CI

**Comment by neuromusic** [comment]
this is likely fixed. feel free to reopen if not.
