### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#47]
A good example can be found in the Atom project:
https://github.com/atom/atom/blob/master/CONTRIBUTING.md

And the Jupyter project:
https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst

**Comment by ambrosejcarr** [comment]
The biohub microscopy team flagged this as important on the sync today.

**Comment by ambrosejcarr** [comment]
#228 makes our `CONTRIBUTING.md` much more robust. I'll reach out to the biohub team and let them know this is updated. 

Leaving this open, as more improvements will come as we add more testing.
