### ISSUE TITLE
Construct Visualization Suite

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#471]
- Each spot finder must be able to produce decoded images
- copy number charts
- histogram of spot area
- histogram of distances from codes
- violin or joint-line plots (ask colin) showing barcode qualities
- other QC?

**Comment by kevinyamauchi** [comment]
I am not sure if this falls within the scope of the initial version of the viz suite, but it would be really nice to have tools to compare multiple datasets (e.g., some sort of performance metric over varying filtering parameters).

**Comment by dganguli** [comment]
@kevinyamauchi totally agree -- we're working hard to make sure that all the things above work seamlessly across assays and datasets. @ambrosejcarr and i can show you some preliminary results to this end shortly.

**Comment by kevinyamauchi** [comment]
Awesome. As we've previously discussed, this is directly inline with our lines of inquiry and I am happy to help if necessary.
