### ISSUE TITLE
Overhall stack API

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#48]
The current Stack abstraction in io.stack.py conflates 'hybridization' images and 'auxilary' images. It's probably a good idea to separate these two under a common base class. This will:

1. Eliminate having to load (and potentially write) all 'hybridization' and 'auxilary' images when you only want to operate on, say, a single auxilary images

2. Eliminate the propagation of an 'org.json' file at each step of computation

3. Make the CLI more flexible and less tied to specific intermediary file formats

**Comment by dganguli** [comment]
@ttung  can we add a 'linter' to make sure that peoples json files are well specified and point to real files? I'm running into this with collaborators self-made json files. This can also be a separate issue to file once the API experiences less churn as well.

**Comment by ttung** [comment]
Once we standardize on the file format, we can do that.

**Comment by ttung** [comment]
Also, would be great to build that tool that makes it easy to build a UI from a json-schema. :)

**Comment by ttung** [comment]
https://github.com/mozilla-services/react-jsonschema-form might do.

**Comment by ttung** [comment]
I think this is done.
