### ISSUE TITLE
Starfish needs a filter that allows flexible scaling of input data

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#489]
the `PerRoundMaxChannelDecoder` simply picks the highest-intensity channel in each round and uses that to decode an experiment. However, it doesn't enforce any scaling of the channels beforehand, which could lead to odd results where one channel has higher overall intensity. 

There are other examples where we need scaling: MERFISH scales channels by Intensity, and BaristaSeq scales channels based on bleed-through across the Illumina machine.

**Comment by dganguli** [comment]
I view the filters as the place to implement intensity scaling operations, not the decoders. 

I like the decoders as being 'dumb' and the magic in signal processing as being done by the 'filters', or, eventually, by some learned model of which the final 'soft-max' or equivalent layers is one of the 'dumb' decoders.

the scale_by_percentile, clip, and zero_channel_by_magnitude filters, or some perhaps more flexible variants of these, can always be applied to the images (before decoding) to handle the issues you mentioned above.

thoughts?

**Comment by ttung** [comment]
I think we should consider making that a different `PipelineComponent`.  Would be in the class of  image → image transformations.

**Comment by dganguli** [comment]
Isn't that what Filters is?

**Comment by ttung** [comment]
Yeah, that's true. :)

**Comment by ambrosejcarr** [comment]
When implementing this, if it takes a dictionary of values, it can support the MERFISH scaling requirement as well.
