### ISSUE TITLE
docker / conda files from sptx-format need to be integrated

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#511]
attn @joshmoore; I think you added these files.  https://github.com/spacetx/starfish/tree/dd9990970e75218ee5afe02f894cc39eda99edca/sptx-format

**Comment by joshmoore** [comment]
Yup. I'll take care of it.

**Comment by joshmoore** [comment]
Pushed to https://github.com/spacetx/starfish/pull/495 all the changes that are needed for the starfish+sptx-format merge. `starfish` is still the default entrypoint, but `--entrypoint=validate-sptx` works as well.

NB: Might make sense to have a `starfish validate` now

**Comment by ambrosejcarr** [comment]
> NB: Might make sense to have a starfish validate now

I agree here.

**Comment by joshmoore** [comment]
see https://github.com/spacetx/starfish/pull/523
