### ISSUE TITLE
FieldOfView tile_shape has ambiguous (x, y) ordering

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#528]
The schema claims that it is ordered (x, y)
https://github.com/spacetx/sptx-format/blob/master/schema/field_of_view/field_of_view.json#L91

Internally, we don't validate on this field yet, we simply slurp in the data and make sure that the sizes fit. However, we might want to provide information on a TileSet (before it's loaded into memory).

We should replace this with an explicit map of {x: size, y: size}, instead of a list to prevent errors.

Ported from spacetx/sptx-format#23

**Comment by ttung** [comment]
For this to be complete and unambiguous, I think we need to specify (possibly [here](https://docs.google.com/document/d/12V-BQF-wh1GDBXwUH2hQrPhw6n0oQqENPK-YHGv59w4/)) that the tile data should be read into memory row-major.  Strictly speaking, we are agnostic about the organization of the data on disk, but when we get it, it has to be row-major.

We can also change tile_shape to be a dict so it's less _error prone_, but it's actually quite clear as it is.

Thoughts, @ambrosejcarr?

**Comment by ttung** [comment]
Feel free to assign it back to me with your opinions. :)

**Comment by ambrosejcarr** [comment]
I was not clear originally, the problem is that the spec and the code disagree on the ordering. Code is (y, x), which we agree is correct. I believe you decided to move toward the dictionary option.
