### ISSUE TITLE
Error loading validate_sptx.cli

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#533]
Attempts to run the notebooks currently fail due to an ImportError that is not caught by tests. Perhaps it has to do with the import path. @joshmoore could you take a look at this? 
```python3
from starfish.experiment import Experiment
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-37cb51847870> in <module>()
      8 import seaborn as sns
      9 
---> 10 from starfish.experiment import Experiment
     11 from starfish.types import Features, Indices
     12 

~/projects/spacetx/starfish/starfish/__init__.py in <module>()
     15 from .intensity_table import IntensityTable
     16 from .stack import ImageStack
---> 17 from .starfish import starfish

~/projects/spacetx/starfish/starfish/starfish.py in <module>()
     16     TargetAssignment,
     17 )
---> 18 from validate_sptx.cli import Cli as ValidateCli
     19 from .util.argparse import FsExistsType
     20 

ModuleNotFoundError: No module named 'validate_sptx.cli'
```

**Comment by joshmoore** [comment]
Yup. I'll explore. I assume from `origin/master`? Are you running interactively or headless?

**Comment by ambrosejcarr** [comment]
Correct, master @ 9808c4f

I'm running interactively.

**Comment by joshmoore** [comment]
From that commit with 

```
pip uninstall starfish
export PYTHONPATH=$PWD
jupyter notebook
```

The following are passing the import stage for me:
 * http://localhost:8888/notebooks/notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
 * http://localhost:8888/notebooks/notebooks/ISS_complete.ipynb

_Without_ `export PYTHONPATH` it fails with `ModuleNotFoundError: No module named 'starfish'`

**Comment by ambrosejcarr** [comment]
Yes. Still fails for me.

**Comment by joshmoore** [comment]
Also passes for me.

**Comment by ambrosejcarr** [comment]
Problem with my (apparently borked) environment. I have permanently switched to using a venv and we can close this. Thanks @ttung for the appropriately-leveled criticism of my non-venv install strategy. 😆
