### ISSUE TITLE
Should instance documents contain a link to their schema?

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#539]
At the moment, `validate_sptx.validate_sptx` hard codes the validator that should be used to validate a document. If documents contained a link to their own schema, then this would be unneeded. A generator down the object tree could at each separation of layers instantiate a new correct validator.

----
### Investigations ###
 * [ ] https://github.com/spacetx/starfish/issues/539#issuecomment-423732001 -- allow explicit schema as optional value
 * [ ] https://github.com/spacetx/starfish/pull/538#discussion_r219927667 -- point to child schemas from typed fields
 * [ ] allow validation on `--hybridization-json` etc.
 * [ ] also pass source URLs into experiments `extras` field

**Comment by joshmoore** [comment]
I think the primary benefits of *not* specifying are:

 * easier to write instance documents
 * shorter instance documents
 * some (wacko?) chance that an instance document could be considered valid against another schema

The benefits of specifying are:

 * knowing the _intended_ (or production) version
 * and therefore being able to validate a snippet that you are receiving without provenance

**Comment by ambrosejcarr** [comment]
cc @ttung here. This is not my area of expertise, I would delegate the decision to you. I'd also be interested in the HCA metadata folks' opinion 

cc @hewgreen @zperova

**Comment by ttung** [comment]
Could you be more specific what you mean here?  Like pointing to a specific version of the schema doc?  Or just a generic version of the schema doc?

I am unclear on what the benefits of specifying the schema doc (over what we have now, which is a version) might be, but one possibility is that we modify `starfish validate` to optionally write the schema doc URL to the document.

**Comment by joshmoore** [comment]
I'm most familiar with this in the XML space, but generally I think the design decision is whether or not to have a file be self-documenting, i.e. without needing the logic in the source code itself. If I receive an OME-TIFF, I assume that multiple programming languages can use their XSD implementations to know whether or not the file is at least schema valid based on:

```
$ tiffcomment image.ome.tiff  | xmllint --format -
...
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Creator="OME Bio-Formats 5.9.0" UUID="urn:uuid:2f234f1b-047d-4cf4-86a1-48f2c89f76ca" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
  <Image ID="Image:0" Name="image">
    <Pixels BigEndian="false" DimensionOrder="XYZCT" ID="Pixels:0" Interleaved="false" SignificantBits="32" SizeC="1" SizeT="1" SizeX="512" SizeY="512" SizeZ="1" Type="float">
...
```

Of course, that's quite a long string to drop in each json file.

**Comment by ttung** [comment]
Ahh, I see.  Let's go with not specifying the schema (or at least making it optional).

**Comment by joshmoore** [comment]
Ok. I will look into a PR that will add it as an optional value then. Perhaps even an either/or with the numeric version would be possible.
