### ISSUE TITLE
Render README.rst from docs

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#602]
Currently, README.md must duplicate introduction.rst and installation.rst because github cannot render directive-based restructuredtext like

```
.. include:: introduction.rst
```

However, it may be possible to accomplish this rendering with `pandoc` (seems likely) or `sphinx` (was not able to find a solution), which would eliminate duplication in the docs.

**Comment by neuromusic** [comment]
I suggest closing this issue & keeping the README distinct from the docs
