### ISSUE TITLE
investigate adding to_tiff() method to ImageStack 

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#603]
A common pattern I've encountered in using Starfish is:

0. Load data in spaceTx format,
1. Do some filtering,
2. Visualize results.
3. Do thinks make sense? If yes, pass. Else, GOTO 1.
4. Find spots, decode, etc.

For step 2. we expose a show_stack method, which visualizes the data using a Jupyter widget. However, I find myself wanting to pan, zoom, adjust dynamic range, etc. And this is hard to do in a performant way with Jupyter widgets.

Instead, I write out tiff files, and open them in FIJI. This is often painful. I have to convert the float32 images into a tiff specific format. To do this, I often just pick an single tile form the full 5 dimensional stack, convert it to uint16, and pick some ad-hoc tiff-writer to save out data.

I suggest we expose a ImageStack.to_tiff() method. This will take our ImageStack, do all the necessary conversions, and choose a specific tiff format (I vote OME-tiff!) to write to disk. We can potentially some skimage compatibility to do so: http://scikit-image.org/docs/dev/api/skimage.external.tifffile.html

@joshmoore what's the right format for our data? which converter should we use from the Python eco-system?

FYI @ambrosejcarr @ttung @shanaxel42

**Comment by dganguli** [comment]
Here's what I currently do:

```
from skimage import img_as_uint
from skimage.io import imsave
# filt2 is of type ImageStack. Here I'm choosing round 1, channel 1, z-plane 1 to save as a tiff to open #up with FIJI
im_tiff = img_as_uint(filt2.numpy_array[0,0,0,:,:])
imsave('/Users/dganguli/Desktop/fuck.tiff', im_tiff)
```

**Comment by dganguli** [comment]
Would be nice if I could save all dimensions, and use hyperstack functionality of FIJI to look at all the data somehow.

**Comment by joshmoore** [comment]
@dganguli : the three options for writing out OME-TIFFs that occur to me are:

 * **use ome-files-py**: pretty friendly for the user, but the build/deployment burden is pretty high without something like docker, conda or wheels.
 * **call out to Java**: there are libraries like https://github.com/soft-matter/pims that make this more manageable but, again, a deployment burden.
 * **write a simplified ome-tiff writer in python**: I don't imagine this would be too hard and somewhat matches the strategy that I've taken with spacetx-fov-writer where the implementation in one language is designed to support a specific subset of the other language.

In any event, I can certainly get behind this symmetry. spacetx-fov-writer already creates an OME companion file when converting non-sptx filesets to sptx. With this, each such fileset is already openable in the Fiji/OME space. Having the same level of support for native sptx filesets would be nice.

**Comment by joshmoore** [comment]
@dganguli : here's a potential example of doing what you want from an internal IDR use case:

https://github.com/IDR/idr0047-neuert/pull/1/commits/fd73bce002a7f234e991f4bb53dad04d94147d3f

That writes out the same type of `*.companion.ome` file that spacetx-fov-writer does but in Python. There's one gotcha: the current released version of Bio-Formats requires each TIFF to have a special internal UUID. An [upcoming version of Bio-Formats](https://github.com/openmicroscopy/bioformats/pull/3228) will loosen that restriction, allowing existing TIFFs on disk (or TIFFS newly created by `starfish`) to be grouped together by this single generated XML file.

**Comment by ambrosejcarr** [comment]
> Would be nice if I could save all dimensions, and use Hyperstack functionality of FIJI to look at all the data somehow.

+1, it would be great if FIJI understood whatever we're writing to disk. In the grand scheme of "`ImageStack` operations should return `ImageStack`, we should be able to use `get_slice()` to return whatever subset we want to visualize, then dump that to disk and grab it from FIJI.

**Comment by ambrosejcarr** [comment]
cc @kevinyamauchi Here's the issue relating to what we discussed. about more easily writing hyperstacks.

**Comment by ambrosejcarr** [comment]
This was solved with the addition of the `ImageStack.to_multipage_tiff()` function.
