### ISSUE TITLE
A mechanism to flag when a notebook is in notebooks/py but not in .travis.yml

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#605]
Should be a makefile rule that just fails.

Followup from https://github.com/spacetx/starfish/pull/596

**Comment by joshmoore** [comment]
from https://github.com/spacetx/starfish/pull/609/commits/68a0c85eecc90fdcdfb6a3acaf18ecfe40a9285d

```
make check_notebooks
grep notebooks/py/allen_smFISH.py .travis.yml
make: *** [check__notebooks/py/allen_smFISH.py] Error 1
```
