### ISSUE TITLE
Publish a copy of processed results to public folders for analysis community

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#617]
Write processed results for: 

- [ ] notebooks
- [ ] vignettes
- [ ] data in browse, when processable

@ttung should this be set up as part of our CI? Do we need to write some kind of spec for our output formats if we want others to see them as standards they can develop against?

@joshmoore and Jeremy Miller have expressed a need for some output images and count matrices, respectively.

**Comment by ambrosejcarr** [comment]
@berl assigned you to this issue to reflect our work to create the processed outputs from your mouse panel and upload them to our bucket.

**Comment by shanaxel42** [comment]
The place to upload the processed mouse panel dataset is here starfish.data.spacetx/smFISH/mouse/contributer_results

**Comment by shanaxel42** [comment]
We've uploaded the current results from groups to the bucket `starfish.data.spacetx` any new results should also be uploaded to the corresponding groups folder within that bucket.
