### ISSUE TITLE
Fix ScaleByPercentile Filter

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#618]
As it stands, this scaling filter is not functioning properly due to an interaction with the [0, 1] boundary. 

To fix the filter, the entire `FieldOfView` should be remapped into the [0, 1] regime. This can likely be implemented as a pre-processing step where the 90th percentile of the field of view is identified and then the scaling is applied to each slice.

**Comment by dganguli** [comment]
@ambrosejcarr This is related to #547. This filter was written _before_ floats were merged. When it was written, it was indeed written _correctly_. _After_ floats were merged, it broke many of the filters, including this one. That's OK. This is the fix:

In general, **all** filters should call preserve_float_range after the filter is ran. It should be up to the user to specify what they want to do with values > 1. There are two options:

1. Clip
2. Re-scale to lie in [0, 1]

preserve_float_range takes an option, and does one of these two things. Each filter also takes this option and passes it through to preserve_float_range.

**Comment by shanaxel42** [comment]
I can make these changes as a part of #547. @dganguli Do we want clip or rescale to be the default behavior in preserve_float_range?

**Comment by ambrosejcarr** [comment]
Per an offline conversation, there is a bit more complexity to examine here. Transcribing some of it below, I have a concern that linear scaling in the case where `clip=False` is not doing what we want it to as envisioned above. 

```python

In [11]: data
Out[11]: array([0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ])

In [14]: def scale_by_percentile(data: np.ndarray, p: int, clip: bool):
    ...:     """If clip is True, clip data[data > 1] to 1, else scale by max"""
    ...:     val = scoreatpercentile(data, p)
    ...:     scaled = data / val
    ...:     if np.any(scaled > 1):
    ...:         if clip:
    ...:             scaled[scaled > 1] = 1
    ...:         else:
    ...:             scaled = scaled / scaled.max()
    ...:     return scaled


In [16]: scale_by_percentile(data, 80, clip=True)
Out[16]: 
array([0.12195122, 0.24390244, 0.36585366, 0.48780488, 0.6097561 ,
       0.73170732, 0.85365854, 0.97560976, 1.        , 1.        ])

In [17]: scale_by_percentile(data, 80, clip=False)
Out[17]: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]: scale_by_percentile(data, 70, clip=False)
Out[18]: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]: scale_by_percentile(data, 60, clip=False)
Out[19]: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]: scale_by_percentile(data, 50, clip=False)
Out[20]: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [21]: scale_by_percentile(data, 50, clip=True)
Out[21]: 
array([0.18181818, 0.36363636, 0.54545455, 0.72727273, 0.90909091,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [25]: data2 = np.logspace(0, 1, 10)

In [26]: data2 = data2 / data2.max()

In [27]: data2
Out[27]: 
array([0.1       , 0.12915497, 0.16681005, 0.21544347, 0.27825594,
       0.35938137, 0.46415888, 0.59948425, 0.77426368, 1.        ])

In [30]: scale_by_percentile(data2, 60, clip=False)
Out[30]: 
array([0.1       , 0.12915497, 0.16681005, 0.21544347, 0.27825594,
       0.35938137, 0.46415888, 0.59948425, 0.77426368, 1.        ])

In [31]: scale_by_percentile(data2, 90, clip=False)
Out[31]: 
array([0.1       , 0.12915497, 0.16681005, 0.21544347, 0.27825594,
       0.35938137, 0.46415888, 0.59948425, 0.77426368, 1.        ])

In [32]: scale_by_percentile(data2, 99.9999, clip=False)
Out[32]: 
array([0.1       , 0.12915497, 0.16681005, 0.21544347, 0.27825594,
       0.35938137, 0.46415888, 0.59948425, 0.77426368, 1.        ])
```

Deep suggested we look into `skimage.exposure.rescale_intensity` for the `clip=False` case. 

```python3
better_contrast = exposure.rescale_intensity(
...                                     moon, in_range=(v_min, v_max))
```

**Comment by ambrosejcarr** [comment]
@dganguli also made a suggestion that propagating an enum that declares the way to deal with out-of-scale (`x < 0, x > 1`) values, e.g.: 
```
scale.CLIP
scale.RESCALE
scale.DO_NOTHING
```

**Comment by dganguli** [comment]
@shanaxel42 let's do clip as the default.

**Comment by dganguli** [comment]
@ambrosejcarr that y = y./y.max() thing is weird. we should definitely _not_ do that. there's some function that re-scales properly and we just need to think hard about what that is. as you say, it's probably rescale_intensity(). but requires some 'googling'.

**Comment by dganguli** [comment]
also, what happens if you re-do your experiment w/ rescale_intensity() instead of y = y/y.max()?

**Comment by ambrosejcarr** [comment]
Without looking at their code at all to figure out why this is the case, It decides to scale to a different value, but is still insensitive to p. 

```
In [14]: scale_by_percentile_skimage(data2, 80, clip=False)
Out[14]: 
array([0.        , 0.03239441, 0.07423339, 0.12827052, 0.19806216,
       0.28820152, 0.40462098, 0.5549825 , 0.74918187, 1.        ])

In [15]: scale_by_percentile_skimage(data2, 99, clip=False)
Out[15]: 
array([0.        , 0.03239441, 0.07423339, 0.12827052, 0.19806216,
       0.28820152, 0.40462098, 0.5549825 , 0.74918187, 1.        ])

In [16]: scale_by_percentile_skimage(data2, 99.999999, clip=False)
Out[16]: 
array([0.        , 0.03239441, 0.07423339, 0.12827052, 0.19806216,
       0.28820152, 0.40462098, 0.5549825 , 0.74918187, 1.        ])
```

**Comment by ttung** [comment]
My suggestion: each filter accepts an instance of IntensityMapper, a yet-to-be-created class that maps a float value to another float value.  To simplify things, we can make the interface a series of (input range, m, b) tuples.  Roughly defined as:

input range: input range for which the corresponding m + b applies.
m, b: the components to the y=mx+b formula.

How we calculate the output:
```
output = np.zeros(..)
for input_range, m, b in filter_components:
    output[component satisfies input_range] = m * input + b
```

This is flexible enough to express a variety of input:output regimes, and we can provide some sane defaults.

**Comment by ambrosejcarr** [comment]
ScaleByPercentile was removed.
