### ISSUE TITLE
Process entire dataset, not just 1 FOV

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#62]
For now, we've been using the Python API to process 1 FOV at a time to ensure the API makes sense and works as expected. Work on this will continue through #54 #55 #56 #57 etc. However, what does it look like to use the CLI to process an entire dataset comprised of multiple FOVs? How fast is the process? Did it work? How good is our wdl approach?

Work here will also inform #51 #58 #59 #61

**Comment by ambrosejcarr** [comment]
#234 will provide some of the framework to process multiple FOVs in the API. We will start with sequential processing.
