### ISSUE TITLE
Experiment API: getting aux images is different than primary images

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#625]
Let's say I have an experiment like this:

```
<starfish.Experiment (FOVs=2)>
{
fov_000: <starfish.FieldOfView>
  Primary Image: <slicedimage._tileset.TileSet object at 0x11d5e9160>
  Auxiliary Images:
    nuclei: <slicedimage._tileset.TileSet object at 0x11d5b0b70>
    beads: <slicedimage._tileset.TileSet object at 0x11d61e1d0>
fov_001: <starfish.FieldOfView>
  Primary Image: <slicedimage._tileset.TileSet object at 0x11d5e97b8>
  Auxiliary Images:
    nuclei: <slicedimage._tileset.TileSet object at 0x11d619da0>
    beads: <slicedimage._tileset.TileSet object at 0x11d61e4e0>
}
```

to get the primary image i do this:

```stack = e['fov_000'].primary_image```

to get the aux image, i'm tempted to do this:

```e['fov_000'].auxiliary_image['beads']```

via symmetry. Instead the API says I have to do this:

```e['fov_000']['beads']```

which is confusing? 

CC @ambrosejcarr

**Comment by ambrosejcarr** [comment]
I would pose two possibilities: 

1. 
```
e['fov_000'].primary_image
e['fov_000'].beads

**Comment by ttung** [comment]
If we wanted to go down that route, we should change the file format to put all the images at the same level, i.e., 

```
{
  "version": "4.0.0",
  "images": {
    "primary": "hybridization.json",
    "nuclei": "nuclei.json"
  },
  "codebook": "codebook.json",
  "extras": {}
}
```

And then we would require (in the schema) that the `images` dict contains `primary`.

The current model you are proposing does not map well to the file format.

**Comment by ambrosejcarr** [comment]
I approve of this change.
