### ISSUE TITLE
Processing large fields of view

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#627]
We do not upper bound the pixel size of a field of view. We now have FoVs that take up over 20gb in memory, making it difficult to pilot analyses on a laptop. 

Do we:
- do nothing, make this a user responsibility
- create a maximum field of view size to preempt the memory troubles that will occur, and make explicit the need to split
- implement a splitting method (likely depending on 
the same machinery as crop)
- use dask
- other?

**Comment by joshmoore** [comment]
For comparison, in OMERO any image that is `(X * Y) > (3000 * 3000)` and does not contain a native pyramid in the file format will have a pyramid generated for it, using halving to generate some number of subresolutions.

**Comment by ambrosejcarr** [comment]
> For comparison, in OMERO any image that is (X * Y) > (3000 * 3000) and does not contain a native pyramid in the file format will have a pyramid generated for it, using halving to generate some number of subresolutions.

Very cool. We probably don't need the pyramid for our processing use case, right? But that sounds super useful for visualization. 

I think what's needed here might actually be more sophisticated and is based on a set of yet-to-be-implemented features: 

1. ImageStack operations return ImageStacks
    1. Leverage getslice() to do the cropping, which should: 
    2. Make correct changes to coordinates and other metadata such that the returned ImageStack is valid (and can be serialized)

Use these capabilities to: 
1. Cut up a large ImageStack into smaller ones (crop ++)
2. Later stitch ImageStacks back together (a concatenate command?)

I'm happy to split this up into smaller issues if desired. 

cc @ttung

**Comment by ambrosejcarr** [comment]
@dganguli @ttung here is what adding coordinates directly to ImageStack to enable dual pixel/coordinate indexing could look like. Tony, I mentioned I would mock something up. Here it is!

```python3
>>> import numpy as np
>>> import xarray as xr
>>> toy_data = np.zeros((3, 4, 17, 1000, 800))
```
Make some coordinates by extending some arbitrary ranges to each pixel: 
```python3
x_min, x_max = 0.1, 0.3
y_min, y_max = 0.6, 0.8
z_min, z_max = 0.1, 0.15
>>> x_coords = np.linspace(x_min, x_max, data_array.sizes[Indices.X.value])
>>> y_coords = np.linspace(y_min, y_max, data_array.sizes[Indices.Y.value])
>>> z_coords = np.linspace(z_min, z_max, data_array.sizes[Indices.Z.value])
```
Create an xarray: 
```python3
# note that Coordinates.X.value doesn't work because 'xc' does not match 'x' -- we'll need to pick one. 
>>> with_coords = xr.DataArray(
...     data_array.values, 
...     coords={'x': x_coords, 'y': y_coords, 'z': z_coords},
...     dims=(Indices.ROUND.value, Indices.CH.value, Indices.Z.value, Indices.Y.value, Indices.X.value)
... )
```
The array can now be indexed a few ways. This way is least appealing, since it is what we're attempting to escape in moving away from numpy arrays: 
```python3
>>> with_coords[0, 1, 3:4, 5:10, 5:10]
<xarray.DataArray (z: 1, y: 5, x: 5)>
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])
Coordinates:
  * x        (x) float64 0.1013 0.1015 0.1018 0.102 0.1023
  * y        (y) float64 0.601 0.6012 0.6014 0.6016 0.6018
  * z        (z) float64 0.1094
```
better, we can select on the _indices_:
```python3
>>> with_coords.isel(r=0, c=1, z=slice(1, 2), y=slice(5, 10), x=slice(5, 10))
<xarray.DataArray (z: 1, y: 5, x: 5)>
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])
Coordinates:
  * x        (x) float64 0.1013 0.1015 0.1018 0.102 0.1023
  * y        (y) float64 0.601 0.6012 0.6014 0.6016 0.6018
  * z        (z) float64 0.1031
```
Most importantly, we can slice on _physical coordinates_. Here we  slice half of the `x` range. Note that the size of the array in x is now 400 instead of 800. 
```python3
>>> with_coords.sel(x=slice(0.1, 0.2))
<xarray.DataArray (r: 3, c: 4, z: 17, y: 1000, x: 400)>
array([[[[[0., ..., 0.],
          ...,
          [0., ..., 0.]],

         ...,

         [[0., ..., 0.],
          ...,
          [0., ..., 0.]]],


        ...,


        [[[0., ..., 0.],
          ...,
          [0., ..., 0.]],

         ...,

         [[0., ..., 0.],
          ...,
          [0., ..., 0.]]]],



       ...,



       [[[[0., ..., 0.],
          ...,
          [0., ..., 0.]],

         ...,

         [[0., ..., 0.],
          ...,
          [0., ..., 0.]]],


        ...,


        [[[0., ..., 0.],
          ...,
          [0., ..., 0.]],

         ...,

         [[0., ..., 0.],
          ...,
          [0., ..., 0.]]]]])
Coordinates:
  * x        (x) float64 0.1 0.1003 0.1005 0.1008 0.101 0.1013 0.1015 0.1018 ...
  * y        (y) float64 0.6 0.6002 0.6004 0.6006 0.6008 0.601 0.6012 0.6014 ...
  * z        (z) float64 0.1 0.1031 0.1063 0.1094 0.1125 0.1156 0.1187 ...
Dimensions without coordinates: r, c
```

**Comment by ambrosejcarr** [comment]
As an aside, this would be easy to propagate/mirror to the `IntensityTable`, which will be _super_ helpful when we start talking about stitching together multiple FOVs in larger experiments.

**Comment by ttung** [comment]
Ahh, got it.  You're removing the indexing by pixel coordinates, but you still get it from the raw indices.

**Comment by ambrosejcarr** [comment]
Yep, That's right!

Relevant to #622

**Comment by ttung** [comment]
cc @shanaxel42

**Comment by dganguli** [comment]
I think for now, if our MVP user is spaceTx, we should only accept small FOVS (< 3000 x 3000) and throw an exception if we get something bigger. this should be clear in our github version of our file format spec. i believe we asserted this in our google doc version of our spec, and on our calls with spaceTx contributors, but this never made it to our format/code.

for users, this means that the onus is on them to break up large images into smaller subsets. for now.

moving forward, i think we should further investigate ken harris's memory efficient processing pipeline that never relies on stitching. if that's a no go, then we re-visit how to generate a pyramid for the user as per @joshmoore suggestion?

curious what y'all think @ambrosejcarr @ttung ?

**Comment by ambrosejcarr** [comment]
@berl 's pipeline (commit reference: 7998996) requires the following compute and memory resources to run one field of view: 

> running 1 FOV peaks at about 70GB RAM and finishes in about 8 min on a Core i9-7900X (3.3Ghz with ncpu = 20)

cc @ttung @shanaxel42

**Comment by ttung** [comment]
We're not going to fix this issue (for now). It's incumbent on the user to have a machine with sufficient memory to execute the FOV.  We will provide tooling to chop up FOVs into smaller units.
