### ISSUE TITLE
Mean high pass filter needs a test

### ISSUE THREAD

**Issue by kevinyamauchi** [spacetx/starfish#636]
As @ttung pointed out in #620, the mean high pass filter needs a test. Unless there are any objections, I will use the same style of test as the Gaussian high pass (compare the image sum before and after filtering) for now. However, we should probably re-evaluate this testing strategy at some point. For deterministic filters such as these, I think we should have a test image with an expected output and assert that the filter produces this output each time.

**Comment by kevinyamauchi** [comment]
@ttung, @ambrosejcarr, would this be okay for now? I was looking at the GaussianHighPass tests (/starfish/test/pipeline/test_filter.py) and it looks like test_gaussian_high_pass() and test_gaussian_high_pass_apply() are the same. Am I missing something?

**Comment by ambrosejcarr** [comment]
> For deterministic filters such as these, I think we should have a test image with an expected output and assert that the filter produces this output each time.

Agree. I like the checkerboard image used by skimage for some of these things. It should produce an inspectable output.

I think the only thing you need test here is the scientific output. In my open testing profile, I think I hit the rest of the cases that have to do with the API.

**Comment by kevinyamauchi** [comment]
Okay, sounds good. It looks like PR #504 already includes the mean high pass filter, so I think I just need to add the tests in (/starfish/test/pipeline/test_filter.py. Is this correct?

Also, what is the difference between test_gaussian_high_pass() and test_gaussian_high_pass_apply()? It looks like they do the same thing on master.

**Comment by ttung** [comment]
I thought I already did this, but https://github.com/spacetx/starfish/pull/638.

**Comment by kevinyamauchi** [comment]
> I thought I already did this, but #638.

Approved, thanks!

**Comment by ambrosejcarr** [comment]
> Okay, sounds good. It looks like PR #504 already includes the mean high pass filter, so I think I just need to add the tests in (/starfish/test/pipeline/test_filter.py. Is this correct?

Correct.

**Comment by kevinyamauchi** [comment]
Resolved by #655
