### ISSUE TITLE
PixelSpotDetector returns a tuple unlike all the other spot detectors

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#637]
[ambrosejcarr Edit]: 

`PixelSpotDetector` returns an `IntensityTable` and a `ConnectedComponentDecodingResult`

`PixelSpotDetector` executes additional processing steps to find `ConnectedComponents` and from them, generate a `LabelImage` and a `DecodedImage` which identifies the target for each pixel by decoding across rounds and channels. The `DecodedImage` is useful for visualization and so each of these intermediates is returned as part of the `ConnectedComponentDecodingResult`.

**Comment by ttung** [comment]
@ambrosejcarr can you flesh out what needs to be done here to normalize this vs the other spot detectors?

**Comment by ambrosejcarr** [comment]
Edited.

**Comment by shanaxel42** [comment]
non issue now that PixelSpotDetector is now PixelSpotDecoder
