### ISSUE TITLE
CLI should have ability to compute a max projection

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#659]
There are cases in which one filters a full 3D stack, takes a maximum projection across Z, then does all re-maining processing steps (e.g., spot-detection, segmentation, decoding, etc.) on the resulting 2D stack.

This is easy in the API, modulo the fact that, right now, ImageStack.max_proj does not require an ImageStack. But you can't do it in the CLI easily.

**Comment by ttung** [comment]
> ImageStack.max_proj does not require an ImageStack

Do you mean that ImageStack doesn't produce an ImageStack?
