### ISSUE TITLE
TileFetcher and FetchedTile should be able to create spaceTx-format without copying data

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#664]
Users want to be able to generate our metadata without copying image data, which may already exist in a desired location, e.g. an external database, or may be onerously large (`Tb`++). 

It seems like `TileFetcher` and `FetchedTile` could be adapted to reference the location of the images in the directory that is provided instead of writing a new set of Images. 

Better yet would be if a `--no-validate` mode existed in which the images themselves did not need to be read, but rather, just the names would be extracted to build the correct metadata. 

To do: 
- [ ] Can build spaceTx-format using starfish tools without _copying_ image data
- [ ] (Optional) Can build spaceTx-format using starfish tools without _reading or copying_ image data [edit: this is a pro-only feature; this will lead to long term horrible UX, and will not be compatible with the HCA... but would speed up prototyping in some cases]
- [ ] (For Biohub) TileFetcher can parse s3 "directories"

cc @ttung @kevinyamauchi -- this would Benefit the Biohub use case by helping them to support their Image Database. It might also be good for us in the longer term, as it could streamline our updates to spaceTx-format datasets that need to be changed as a result of changes to `starfish` and `slicedimage`.

**Comment by ttung** [comment]
What's would be the path to these not-on-disk images?

**Comment by ttung** [comment]
Summary of findings:

@berl could use a variant that produces the json files that reference existing images.  reading once to calculate the checksums is okay for this round.

**Comment by joshmoore** [comment]
Though the paths wouldn't provide the tile name information, we could likely provide a version which read TIFFs from OMERO which may be useful in the Sanger usage where the Harmony data will first be imported. cc: @olatarkowska

**Comment by berl** [comment]
bumping this because I'm not sure if it's still on the radar. @njmei is working on our analysis pipeline using starfish and we will have limited amount of buffer storage to do processing before we upload to our internal data storage and external archiving.  
cc: @ttung @ambrosejcarr @neuromusic

**Comment by kevinyamauchi** [comment]
Thanks @berl for re-raising the issue. This would also be useful for us at the Biohub!

**Comment by ttung** [comment]
Proposed solution:

`experiment.builder.providers.FetchedTile` should add a second method for providing a path to the original file.
when that method is provided, we should use a custom `tile_opener` in our calls to `Writer.write_to_path` that opens a fake file that accepts write calls but does nothing with them.  everything else will probably just work.

**Comment by njmei** [comment]
@ttung Is this along the lines of what you were thinking? Wanted to double check with you before going further...

https://github.com/njmei/starfish/commit/59d1937b52e2185679cb88f29d83ef62f520e03c

mypy also doesn't seem to like that `ReadOnlyTile` is not a `BinaryIO` type...

**Comment by ttung** [comment]
Long done.
