### ISSUE TITLE
Can Starfish support RNAscope? 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#670]
RNAscope appears to be single-channel RNA-ISH+ a nuclei stain, but its single channel produces spots. Is it possible to analyze such data with Starfish?

**Comment by ambrosejcarr** [comment]
@olatarkowska has your work with starfish shed any light on this question?

**Comment by olatarkowska** [comment]
@ambrosejcarr, that’s scheduled for me for next week. I will try to come back to you as soon as I have something

**Comment by ambrosejcarr** [comment]
@olatarkowska No hurry, just wanted to check in.

**Comment by shanaxel42** [comment]
work in #998 suggests yes.
