### ISSUE TITLE
Document how Starfish expects data to be formatted for alpha users

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#671]
Starfish requires: 
- Registered but not stitched FoVs
- Define a maximum size for each FoV
- Describe, when possible, how to use starfish to chop up an experiment that is too large.

**Comment by ambrosejcarr** [comment]
#1068 completed part one. Assigning to you @ttung for instructions on how to format data given our current expectations.

**Comment by kevinyamauchi** [comment]
I just wanted to give this a bump. Our collaborators are currently working to get their data into spacetx format (single-round RNAscope data) and they were having trouble understanding the different types of coordinates (i.e., physical vs. pixel) and also round vs. field of view from the documentation. In case it's helpful at all, I've pasted an excerpt of what I sent them (feel free to steal/ignore as you see fit).

> There are two types of spatial coordinates assigned to the pixels in the each image:
> 
> - First, there are pixel coordinates (x, y), which are the indices for each pixel in the matrix representation of the image. For example, if we have an images that is 2x2 pixels, the upper left pixel is  (x, y) = (0, 0) and the bottom right pixel is (x, y) = (1, 1)
> - Second, there are physical coordinates (xc, yc, zc). These are the coordinates of the pixels in the microscope reference frame. That is, xc and yc are the stage coordinates (often in microns) and zc is the objective position (also often in microns). If you want to put in the physical coordinates, you can calculate them as listed below.
> - xc_min = stage_position_x_coordinate_in_microns
> - xc_max = xc_min + (pixel_size_in_microns  * num_pixels_in_x_direction)
> 
> Round is a coordinate used for in situ experiments where there are multiple chemistry steps. For example, in chemistries where multiplexing is increased by stripping probes, hybridizing a new set, and then re-imaging, each set of images would be "round". However, since you only have one round, round=0 for your images.
> 
> A "field of view" is the collection of images acquired from a single stage position. Thus, for your data, all images from a single position have the same "fov" number (as you thought.

**Comment by ttung** [comment]
Does https://spacetx-starfish.readthedocs.io/en/stable/help_and_reference/glossary/glossary.html not cover the questions?

**Comment by kevinyamauchi** [comment]
This definitely would have been useful, thanks! We missed this when we were going through the documentation. I'll pass it along.
