### ISSUE TITLE
Write an adapter for Napari stack visualization.

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#677]
Napari is a python package for visualization of image data. We should write an adapter for it. 
See demo: https://slack-files.com/T8MB1T0MA-FD5SHUAR0-84d2f2dc8b. 

Might be a solution for #603

**Comment by kevinyamauchi** [comment]
I was planning to put this into ImageStack.show_stack(). How does that sound?

**Comment by ambrosejcarr** [comment]
> I was planning to put this into ImageStack.show_stack(). How does that sound? (cc @dganguli )

Do you mean it would replace the existing functionality? If so, does it persist in a notebook? Although the existing approach is a bit clunky, I think there's some benefit in that it is just sitting there when you come back to it, versus opening in another window that the user has to close.

**Comment by kevinyamauchi** [comment]
I don't think it needs to completely replace existing functionality. Perhaps show_stack() can take a Napari argument? Alternatively, we can add something to the viz suite. 

Also, I'm going to ask Kira about plotting. We may be able to also do show_spots() in Napari.

**Comment by ambrosejcarr** [comment]
> I don't think it needs to completely replace existing functionality. Perhaps show_stack() can take a Napari argument? Alternatively, we can add something to the viz suite.

Cool, my sense is that the safest thing to do would be to add a function `show_napari()` for now, and then we can combine/discard the old stuff once we've played around a bit.
