### ISSUE TITLE
filters -- remove open cv import

### ISSUE THREAD

**Issue by dganguli** [spacetx/starfish#68]
This is no longer needed since we entirely use skimage. Opencv should also be removed from setup.py and requirements.txt.

**Comment by tractatus** [comment]
Could this be reconsidered? If OpenCV is supported both R and golang versions of this package can be made without having to reinvent the wheel for all the heavy lifting.

**Comment by ttung** [comment]
Could that functionality be provided by language bridges (FFI) rather than to maintain a separate identical package?

**Comment by tractatus** [comment]
Yes C/C++ as the common language for all the heavy lifting with image processing. 
FFI calls to C/C++ from both python, R and golang would be easier to maintain. In addition performance with opencv is better than scikit-image. No? Or are you suggetsing R and golang would make FFI to python?

**Comment by tractatus** [comment]
Essentially doing similar what mc-stan did for hamilton monte carlo:
https://github.com/stan-dev
http://mc-stan.org/

But here instead of Bayesian modeling with MCMC/HMC the analogy here being a common interface for basic image processing.

mcstan's approach has been extremely successful with interfaces actually used and maintained to all the most popular data analysis languages:
R, Python, shell, MATLAB, Julia, Stata

And works great across platforms:
Linux, Mac, Windows

**Comment by ttung** [comment]
I would prefer postponing optimizing for performance until we have a robust pipeline and infrastructure.  Fast iteration to get us there is key, and python is good for that.  We also don't want to tie ourselves down to a particular image processing backend (opencv or scikit-image).  The idea is that the interfaces are well-defined, but if people want to build an alternative backend (perhaps opencl for GPU acceleration), there is nothing preventing them for doing so.

It depends on what you need starfish to do.  Do you just want to process images?  Or do you want to develop algorithms?  If you're just processing images, R/golang can just shell out to starfish to do the work.  If you're developing algorithms, that is trickier and I'll have to give it some thought.

**Comment by tractatus** [comment]
**Do you just want to process images? Or do you want to develop algorithms?**
Both preferably, no?

More specifically I have a dataset with 204 FOV, 30 z-stacks per FOV and about 2000-4000 amplicons per cell.
See:
http://www.histo.io/?v=cycle001

This sequencing run is for 30 cycles.

If I'm developing routines for handling these kinds of data I might as well develop in the starfish framework no? 

To get really high reads it is not enough to do registration and segmentation on maximum intensity projection but it has to be done on the stack. Nor is it enough to do registration on single FOV.

**Comment by ttung** [comment]
If you develop an algorithm that requires opencv, we'd definitely be happy to add it back as a requirement.  I don't think that @dganguli removing it as a requirement now should be read as a sign that opencv cannot be a requirement or cannot be used. :)

**Comment by tractatus** [comment]
@ttung cool. I'll make a fork and have a stab at it during the weekend. 
I'll also add the first round of the cycle of this dataset to cloud if anyone wants to use it for starfish since it is kind of an extreme dataset (16-bit depth, many FOV, several z-stacks, thousands of amplicons per cell).

**Comment by dganguli** [comment]
Hi Daniel! Sorry to be late to this! Yeah we're totally open to opencv (pun intended) being in the project. However, as Tony said, for now we're in rapid iteration mode and not yet considering performance and/or interlanguage operability. As such, we've landed on skimage for now to simplify things.

 Would love the first round of the cycle of this dataset as another dataset to develop against.

**Comment by ttung** [comment]
opencv is gone.
