### ISSUE TITLE
set stack API

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#69]
The current way to update a data stack is:

```
# this is a vector that needs to be a tensor; s knows what the shape is
s.set_stack(s.un_squeeze(stack_filt))  
```

It would be preferable to have an API for `s.set_stack()` that takes an arbitrary list that implicitly knows the correct shape. 

Alternatively, `s.set_stack()` could be a classmethod that generates a _new_ stack, thus removing side-effecting code from the code-base.

**Comment by ttung** [comment]
This API will be much better (I think) after #48 :)

**Comment by ambrosejcarr** [comment]
@ttung I think this is done with the `get_slice()` and `set_slice()` methods.
