### ISSUE TITLE
document schemas need to be versioned

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#700]
The schemas in validate_sptx/schema are not versioned based on document format version.  They should be.

**Comment by ttung** [comment]
docs/source/usage/iss/iss_pipeline.py is a place that needs to be updated once this is supported.

**Comment by ttung** [comment]
If nobody can take this on after I fix #644, I'll probably do this.

**Comment by ttung** [comment]
> you are proposing having multiple sub-directories under validate_sptx/schema per file format? 

Yes.

**Comment by joshmoore** [comment]
Would like to get gh-788 out of the way before doing anything here.

**Comment by joshmoore** [comment]
My understanding is that https://github.com/spacetx/starfish/commit/3d960e1663b02ee6c01f8236aa1190191a5d1b07 (0.1.1) covers this. Closing.
