### ISSUE TITLE
Document use of environments with conda to reduce likelihood of user errors

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#704]
Conda has a similar approach to virtual environments. We should specify that users of Conda should leverage this capability in our documentation and installation instructions. 

[https://conda.io/docs/user-guide/tasks/manage-environments.html](https://conda.io/docs/user-guide/tasks/manage-environments.html)

**Comment by neuromusic** [comment]
... while acknowledging that virtual environments are not strictly required for starfish to work

**Comment by ambrosejcarr** [comment]
@olatarkowska this would be a great place to list any problems you had while installing starfish through conda.
