### ISSUE TITLE
Update sptx-format to support per-round processing

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#723]
non-coded assays generate data over multiple imaging rounds, where each round contains all information needed to identify a given gene target. As such, an "imaging round" represents a logical processing unit. 

Starfish can currently process data in this way, but only by coercing FieldOfView objects to contain a single imaging round. In this case, because sptx-format assumes that a FieldOfView contains _all_ rounds, these single-round FoVs are all labeled as containing "round 0", which is not consistent with reality. 

Could sptx-format be made more flexible, either to allow a `FieldOfView` to contain a labeled subset of one or more rounds or by subdividing `FieldOfView` into `ImagingRound` objects. Presumably in either case, `ImageStack` could still be used as the processing entity.

**Comment by ambrosejcarr** [comment]
An alternative to the above implementation would be to adjust our loading approach to pull in rounds independently. This could be accomplished by an `ImagingRound` object that is nested inside an `ImageStack` or inherits from a shared parent class. 

An `ImagingRound` is still a 5-d tensor where round is a dummy axis, so should be compatible with each of the existing filters and spot callers. It would be compatible with decoding only in cases of non-multiplex methods. The smallest step towards this would involve leveraging crop-on-read to select individual rounds. 

We _could_ add an optional layer to `spacetx-format` that mirrors this additional level of granularity. This would enable users that generate images-by-round to specify a field of view that is built sequentially, but need only contain at minimum a single ImagingRound to be eligible for starfish analysis. The advantage of this is that it allows a user to build the spec as the data is being created.

**Comment by ambrosejcarr** [comment]
Spoke with @dganguli about this for a while. Our guiding principles are: 
```
- punt on writing the file format as the experiment progresses. [per round processing] is gross no matter how good your format is.
- make sure that what you do for non-multiplexed folks feels good for multiplexed folks
- there should be a *very* high bar for a big, not backwards compatible change to the format
- make changes to the api before you make changes to the format
```

Along with this, we think using named keys, and combining that with an `Experiment` API that lets you select specific subsets of data, and process those subsets to `IntensityTables`, where presumably data can then be combined in memory, is a good solution. 

Adequate flexibility could be introduced by modifying `FieldOfView.json`: 
```python3
shape: {
   c: {"cy5": 0, "cy3": 1},
   r: {3, 4, 5}
   z: {0, 1, ... 45}
},`
```

Where tiles are named, and need not be ordered from zero, and then a comparable `Experiment` or `FieldOfView` API update: 
```python3
e = Experiment.from_json(‘experiment.json’, rounds={0, 2, 16}, channels={‘cy5’}, z={1, 2})
```

or 
```python3
e = Experiment.from_json(‘experiment.json’)
e['fov_000'].get(rounds={0, 2, 16}, channels={‘cy5’}, z={1, 2})
```

@dganguli Please check this to make sure this is consistent with your thoughts!

**Comment by ttung** [comment]
Eng work for round-at-a-time decomposed in https://github.com/spacetx/starfish/issues/832
