### ISSUE TITLE
Create a `LabelImage` class

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#724]
Our segmentation (and potentially also some point calling methods) need a label image. These label images are constructed from an `ImageStack` or some projection of an `ImageStack`, and as such they share its metadata `(x, y, z, xc, yc, zc)`. 

How should we represent this in the library? Candidates include an `xarray.DataArray` or an `ImageStack`-like object. 

Using an `xarray.DataArray` would allow `RegionProperties` to be attached as an Attribute, which would tie the two objects together nicely -- right now they are not explicitly linked.  

cc @ttung @shanaxel42

**Comment by ttung** [comment]
I think this is done.  Feel free to reopen if I'm wrong.
