### ISSUE TITLE
Add versioning to `TileFetcher` and `FetchedTile`

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#745]
@EyalFisher submitted an issue on slack that identifies a need to version `TileFetcher` and `FetchedTile` so that users can clearly identify when versions have changed and therefore to expect to need to update their tools. 

On our side, this may be an important place for us to write very clear commit messages (or release notes?) so that we can point users to specific changes they will need to make to their code to update to new versions. 

See [link](https://spacetx.slack.com/archives/CAR91U354/p1540559849002600) for conversation

**Comment by ttung** [comment]
I'm going to wontfix this one, since `format_structured_dataset` is what we'll likely point people to going forward.
