### ISSUE TITLE
Define units for coordinates in schema

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#750]
Assuming micrometers.

**Comment by ttung** [comment]
Personally, I prefer using meters as that is the SI unit, but I think @dganguli will overrule me. :)

**Comment by ambrosejcarr** [comment]
Micrometers makes sense to me. What's the motivation for meters?

**Comment by ttung** [comment]
SI unit!

**Comment by dganguli** [comment]
I vote micrometers.

**Comment by joshmoore** [comment]
see https://github.com/spacetx/starfish/pull/788
