### ISSUE TITLE
`make release` target

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#761]
see: https://github.com/spacetx/starfish/pull/709#discussion_r226819374

Potential sequence:
 * [ ] run extended check_requirements to sync conda
 * [x] bump version number
 * [x] build `sdist`, install, and test with the installation:
   - [ ] run tests with STARFISH_STRICT_LOADING=true (see gh-764)
   - [ ] ~run `get_git_commit_hash` tests etc. (see gh-968)~ (no longer complicated)
 * [x] commit, tag, push tag
 * [x] build package and push to pypi
 * [x] build docker and push to hub
 * [ ] ~generate and push commit to bioconda-recipes (and potentially open a PR)~ (happens automatically now on tagging)
 * [ ] ~add .dev to version number, commit, and push to master~ (not needed with versioneer)

Similar checklist for comparison:
 * https://gist.github.com/audreyr/5990987

Other things to consider:
 * moving away from setuptools per https://packaging.python.org/tutorials/packaging-projects/
   - https://github.com/sdispater/poetry
   - https://github.com/ofek/hatch

**Comment by ambrosejcarr** [comment]
Hey @joshmoore we've received some feedback that it has been hard for external developers to come back to starfish after a few weeks have elapsed and figure out what's happened. We're thinking about initiating to a release cycle (maybe bi-weekly?) to help mitigate this. 

Would you be interested in creating this make target? If you build it, we'll commit to using it every <TBD> weeks, and having clear changelogs :-)

**Comment by joshmoore** [comment]
Investigating. I'll post some thoughts ASAP.

**Comment by joshmoore** [comment]
Ok. I have something that's mostly working based on `pbr`:

 * https://docs.openstack.org/pbr/latest/user/packagers.html
 * http://www.dougalmatthews.com/2016/Sep/01/automate-publishing-to-pypi-with-pbr-and-travis/

If there are any preliminary objections to that, now would be a good time to express them. The general release process would be:

```
git tag -s -m "..." 0.0.35 HEAD  # No need to edit a file with the version
make release-prep   # Fails if no tag is present; runs quickly & installs starfish
make release-verify # Runs slowly, needs to be manually reviewed
make release-upload # Prints commands that all need to run successfully, e.g.

  # Please execute the following steps
  git push origin
  docker push spacetx/starfish:latest
  docker push spacetx/starfish:0.0.35
  twine upload dist/starfish-0.0.35.tar.gz
```

If there are any issues, the commands need to be rolled back last to front:
 - delete from docker
 - delete tag from github
 - delete tag locally
 - `make clean`
 - startover or get a :coffee:

**Comment by joshmoore** [comment]
There are some who have moved away from pbr: `https://github.com/pyscaffold/pyscaffold/issues/116`

other options for the version calculation:

 * manual bump of version with two commits in a row
 * manual bump of version on a detached head
 * [bumpversion](https://developer.atlassian.com/blog/2016/02/bumpversion-is-automation-for-semantic-versioning/)
 * [python-semantic-versioning](https://python-semantic-release.readthedocs.io/en/latest/commands.html)
 * [versioneer](https://github.com/warner/python-versioneer)

**Comment by ambrosejcarr** [comment]
> If there are any preliminary objections to that, now would be a good time to express them. The general release process would be:

Looks like you provided your own objection 😆 

No problems here, very interested to see what you come up with!

**Comment by joshmoore** [comment]
Heh. It did "just work" (TM) for starfish, so I wouldn't be opposed to rolling back to it and dropping versioneer. Probably need a discussion around all of this.

**Comment by ttung** [comment]
I just read this (I suck).  I understand #1059 much better now. :)

**Comment by joshmoore** [comment]
>  I understand #1059 much better now. :)

🤣 (I looked for a place to put this content since it will be useful but didn't find anything definitive. Preferences?

 * README.md
 * RELEASE.md
 * docs/source/usage/...
 * docs/source/maintainers/...
 * docs/source/?
 * Makefile
 * ...
)
