### ISSUE TITLE
Host our docker image somewhere

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#779]
To use workflow engines, our docker image needs to be hosted somewhere. There are a few options: 

- Quay
- Dockerhub
- Google Container Registry
- Amazon Elastic Container Registry

I suspect the last one may make the most sense for us, but wanted to check if anyone has strong opinions

cc @joshmoore @ttung @shanaxel42

**Comment by joshmoore** [comment]
I don't have any strong opinions except related to keeping it up-to-date and perhaps tagging strategies in general. At the moment, the image is built in two locations:

 * https://quay.io/repository/biocontainers/starfish?tab=tags every time there's a new bioconda release
 * https://hub.docker.com/r/spacetx/starfish/builds/ every time I remember to do it (though a combination of a github callback and `make release` could improve that situation)

**Comment by ambrosejcarr** [comment]
Hah, you're way ahead of me. Awesome.

**Comment by joshmoore** [comment]
For the record, looks like Google might potential mirror the starfish image from Docker Hub but Amazon doesn't, as far as I can tell. See https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring

> Container Registry mirrors public Docker Hub images that are frequently requested by Container Registry users.

Assuming [make release](https://github.com/spacetx/starfish/issues/761) pushes to hub, then the above should actually provide solid initial coverage.
