### ISSUE TITLE
Click help for subcommands broken

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#808]
Some reading material:

 * https://github.com/pallets/click/issues/50 "eager required options suppress help"
 * https://github.com/pallets/click/issues/108#issuecomment-255547347 "Support for shared arguments?" (tl;dr - not gonna do it)
 * https://github.com/pallets/click/issues/295 "Can't access help of subcommands without going through parent's prompts"

Possible solutions:
 * Move top level args to the subcommands (`detect_spots -i X BlobDetector` becomes `detect_spots BlobDetector -i X`)
 * Mark top level args `required=False` and check for their value at run-time
 * Make `--help` "[eager](https://click.palletsprojects.com/en/3.x/options/#callbacks-and-eager-options)" (not yet sure how to do this)
 * Add own group subclass ([SO](https://stackoverflow.com/questions/47972638/how-can-i-define-the-order-of-click-sub-commands-in-help))
 * Add own argument subclass ([SO](https://stackoverflow.com/questions/47437472/in-python-click-how-do-i-see-help-for-subcommands-whose-parents-have-required)) -- fix in progress

**Comment by ttung** [comment]
Is this done?

**Comment by joshmoore** [comment]
Yup.
