### ISSUE TITLE
Finalize provenance logging format

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#820]
#813 Will incorporate the idea of provenance logging to starfish. It adds a 'log' attribute to the Imagestack object that is a list of Pipeline steps that have been run on the data as well as their corresponding runtime parameters. The log is a list of dicts {'method': PipelineComponenetName, 'arguments': runtime params). For example this is wha't is stored in Imagestack.log at the end of the dartfish pipeline:

```
<class 'list'>: [
{'method': 'ScaleByPercentile', 'arguments': {'p': 100, 'is_volume': False}},
{'method': 'ZeroByChannelMagnitude', 'arguments': {'thresh': 0.05, 'normalize': False}},
{'method': 'PixelSpotDetector', 'arguments': {'codebook': <xarray.Codebook (target: 96, c: 3, r: 6)>
array([[[0, 1, ..., 0, 0],
        [0, 0, ..., 1, 0],
        [1, 0, ..., 0, 0]],

       [[0, 1, ..., 1, 0],
        [1, 0, ..., 0, 0],
        [0, 0, ..., 0, 0]],

       ...,

       [[0, 0, ..., 0, 0],
        [0, 1, ..., 1, 0],
        [1, 0, ..., 0, 0]],

       [[0, 0, ..., 0, 0],
        [0, 0, ..., 0, 1],
        [1, 1, ..., 0, 0]]], dtype=uint8)
Coordinates:
  * target   (target) object 'MYH11' 'RELN' 'NR4A2' 'COL20A1' 'IGFBP5' ...
  * c        (c) int64 0 1 2
  * r        (r) int64 0 1 2 3 4 5, 'metric': 'euclidean', 'distance_threshold': 3, 'magnitude_threshold': 0.5, 'min_area': 5, 'max_area': 30, 'norm_order': 2, 'crop_x': 0, 'crop_y': 0, 'crop_z': 0}},
{'method': 'PixelSpotDetector', 'arguments': {'codebook': <xarray.Codebook (target: 96, c: 3, r: 6)>
array([[[0, 1, ..., 0, 0],
        [0, 0, ..., 1, 0],
        [1, 0, ..., 0, 0]],

       [[0, 1, ..., 1, 0],
        [1, 0, ..., 0, 0],
        [0, 0, ..., 0, 0]],

       ...,

       [[0, 0, ..., 0, 0],
        [0, 1, ..., 1, 0],
        [1, 0, ..., 0, 0]],

       [[0, 0, ..., 0, 0],
        [0, 0, ..., 0, 1],
        [1, 1, ..., 0, 0]]], dtype=uint8)
Coordinates:
  * target   (target) object 'MYH11' 'RELN' 'NR4A2' 'COL20A1' 'IGFBP5' ...
  * c        (c) int64 0 1 2
  * r        (r) int64 0 1 2 3 4 5, 'metric': 'euclidean', 'distance_threshold': 0.6, 'magnitude_threshold': 0.5, 'min_area': 5, 'max_area': 30, 'norm_order': 2, 'crop_x': 0, 'crop_y': 0, 'crop_z': 0}}
  ]
```

Another PR is coming to transfer this info the InetensityTable object as well. Is there more info we'd like to incorporate here? Does the format of the info make sense? Feel free to comment with you're questions/comments/concerns or ideas.

**Comment by ambrosejcarr** [comment]
Might be better to store the executed algorithms as a dict, to be a bit more expressive: 
`('ZeroByChannelMagnitude', {'thresh': 0.05, 'normalize': False})`, could become:

```python
[
  {
    "method": "ZeroByChannelMagnitude",
    "arguments": {'thresh': 0.05, 'normalize': False}
  }, 
  ...
]
```
Gives us room to someday have something like `"comments"` that could be inserted to provenance block for the running of an algorithm component, if we wanted to. (do we want to support adding comments about why we chose parameters, for example?)

**Comment by shanaxel42** [comment]
Format updated to list of dicts!  #813

**Comment by ambrosejcarr** [comment]
cc @joshmoore @hewgreen @kevinyamauchi @berl. Is there anything else you would like to see logged here? I can think of "starfish version".

**Comment by joshmoore** [comment]
Though it doesn't hurt to have the starfish version, I'm a skeptic when it comes to whether or not one will be able to reliably reproduce a pipeline based on that one version. (i.e. what version of other tools were installed, etc, etc.) It's a hard problem. More immediately I'd be most interested in whether or not the state of the python interpreter that @berl was talking about could, or needs to be captured, to disk. Still mulling that one over, because to do it, I'd think you'd want to incorporate it into the on-disk format, which requires its own layer of versioning.

**Comment by ambrosejcarr** [comment]
> I'm a skeptic when it comes to whether or not one will be able to reliably reproduce a pipeline based on that one version. (i.e. what version of other tools were installed, etc, etc.) It's a hard problem.

Although we will probably move away from it, right now starfish pins the versions of all of its dependencies. Given that, do you still hold this concern? If so I'm interested in the other concerns you have. 

(we should probably _also_ include the _python_ version, I guess).

**Comment by joshmoore** [comment]
> right now starfish pins the versions of all of its dependencies....

But that assumes one particular form of installation. Users can and will violate that.

> we should probably also include the python version, I guess..

That's part of it, too. Again, definitely no reason not to capture it, but having a full representation to reproduce the state of the interpreter _inside_ of that interpreter just inherently sounds tricky. But for a given (range of) software version(s), the responsibility of getting the state of the _data_ to disk and back seems more tractable.

**Comment by hewgreen** [comment]
Often reproducibility is only guaranteed given some specific assumptions. Total reproducibility is a noble goal. A good way to test this would be to write up some run instructions ensuring details therein are logged and provide configurations as logged above. Then see if an external party reliably gets the same results. Sounds like you're already doing this as a thought experiment.

**Comment by kevinyamauchi** [comment]
>> right now starfish pins the versions of all of its dependencies....

> But that assumes one particular form of installation. Users can and will violate that.

I can and do (on occasion) :/

I think this logging is a great step towards reproducibility. For me the primary need for logging is an ordered list of pipeline components and parameters used (it looks like the PR implements this). The starfish and Python versions would also be great to have. It would also be nice to have versions for the dependencies, etc.. However, I think starfish codebase probably has a shorter timescale for change than its dependencies, so if it's too complex/bloated to record everything about the state of the dependencies, it's probably great to start with the starfish version.

I'm not sure if this has already been discussed, but I think it's worth mentioning that even with a perfect record of the state of the Python environment, some pipeline components would have to be specifically designed for reproducibility. One example would be any operations that involve optimization or some sort of seed value (e.g., some deconvolution implementations). If that initial state (e.g., seeds for random number generator or initial guesses) isn't recorded, the final result may vary even if the environment is completely reproduced.

**Comment by ambrosejcarr** [comment]
From a conversation with @kevinyamauchi we discussed how users will often make corrections for nuances in their experimental set up (e.g. translate a color channel 3 pixels left to account for filter mis-alignment). The rationale for doing this wouldn't be clear in our logging regime. 

@shanaxel42 @ttung would it be possible optional free text field of fixed length that can be saved per component that could store this kind of information if the user elected to provide it?

**Comment by shanaxel42** [comment]
Definitely possible! When would the user be adding this information though? When they run a pipeline step? As another optional parameter to the pipeline step?

**Comment by ttung** [comment]
Also, as mentioned above, we still lack the logging of the version of starfish.

It may also be worth logging:
1. the git commit hash if it's a git checkout of starfish.
2. versions of core dependencies.
3. os type and os version.

**Comment by shanaxel42** [comment]
sweet I create #966 for all these things. feel free to edit if I forgot anything
