### ISSUE TITLE
Research: Propose a segmentation format & object implementation for Starfish

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#838]
Research potential segmentation results format implementations. 
#725 describes a use case for polygons
#724 describes a use case for array masks

There is likely a lot of good thought on this topic by those working on Instance Segmentation in deep learning, e.g. https://github.com/matterport/Mask_RCNN

**Comment by shanaxel42** [comment]
closing in favor of #842

**Comment by shanaxel42** [comment]
closing in favor of #842
