### ISSUE TITLE
Propose a format for segmentation results

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#875]
# Cell Segmentation and format specification

We require a 3-d instance segmentation format, which should be possible to use to annotate IntensityTables. There are an adequate number of already-existing formats from the instance segmentation literature that can be grouped into two categories:

1. Instance masks, either binary or probabilistic, which can be compressed
2. polygons or meshes

Both types have robust library implementations in python (see examples below). Compressed binary masks and polygons appear possible to interconvert (see e.g. https://github.com/facebookresearch/Detectron/issues/100). It seems like either approach might be adequate for our purposes, as both are nicely supported by existing libraries. 

**Use cases**:
1. Geometric intersection of segmented objects with identified spots. 
2. Geometric intersection of segmented objects with other objects

## Examples of instance masks: 
https://github.com/matterport/Mask_RCNN/issues/297
http://scikit-image.org/docs/dev/api/skimage.measure.html?highlight=profile#skimage.measure.label

## Examples of polygons in 2d
https://pypi.org/project/Shapely/
https://pythonhosted.org/planar/overview.html
https://github.com/freeman-lab/regional
http://scikit-image.org/docs/dev/api/skimage.measure.html
http://geopandas.org/

## Examples of polygons in 3d
https://pymesh.readthedocs.io/en/latest/

## Formats for serialization
The formats for serialization appear to be driven by either annotated datasets or software for annotation. 
http://cocodataset.org/#format-results and https://github.com/cocodataset/cocoapi
http://www.robots.ox.ac.uk/~vgg/software/via/, which saves data in a json or csv format that looks like the following: 
```
#filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes
swan_in_geneve.jpg,62201,"{""caption"":""Swan in a lake""}",1,0,"{""name"":""polygon"",""all_points_x"":[119,102,196,406,395,433,413,336,332,247,164,119],""all_points_y"":[175,218,285,288,232,227,140,138,210,182,195,175]}","{""name"":""Swan"",""color"":""white""}"
```

## User requirements: 
@ambrosejcarr is actively doing research to determine whether we have additional requirements. 

**Watershed**: 
- Each pixel is hard-assigned to at most one cell and is stored in memory as a label image where each cell is assigned a numerical value, and each pixels is assigned the value corresponding to the cell, or 0 if it is not part of a cell. 

**Voronoi Tessellation**:
- Each pixel is hard-assigned to exactly one cell. 

**Kenneth Harris' method**: 
- Each pixel is hard-assigned to at most one cell, in initial segmentation, and is stored in memory as a label image where each cell is assigned a numerical value, and each pixels is assigned the value corresponding to the cell, or 0 if it is not part of a cell. 
- Spots are assigned probabilistically, using a sparse array containing probabilities for the top few cells

## Suggested Direction: 
Binary segmentation masks support most use cases and can be easily converted into polygons as necessary, although the converse is not true. Based on discussions with experts, it seems like masks are a better choice for computationally generated masks, and are closer to the image, and therefore easier to apply and visualize. As a result, I suggest we start with an implementation that focuses on using masks. 

## Implementation requirements: 
1. SpaceTx specification for a binary segmentation mask. Need not enable probabilistic or overlapping representations, but the implementation should be aware of a potential future need (suggest 1 sparse mask per object, not 1 mask per image that contains all objects). 
2. Starfish object to represent a set of segmented cells that meets the requirements of the specification. This object should be usable either with a single field of view, or on a stitched (very large) composite image. 
3. On-disk storage format for the segmentation mask
4. Update starfish watershed implementation to emit the format (see also #998 for a suggested improvement)

**Comment by ambrosejcarr** [comment]
Next steps: check with Nick, Simone, Brian, and Jeremy miller.

**Comment by ambrosejcarr** [comment]
@sofroniewn I did a bit of research into segmentation options for starfish. My studies (see above) suggest that both polygons and masks represent feasible approaches, and that there are decent serialization formats for both. Our main use case is being able to use the mask/polygon to efficiently annotate the IntensityTable with cell (or other region) information. It should also have a reasonably compact serialization. We'd like to have the flexibility to enable probabilistic segmentation (maybe easier with masks?) and to have overlapping regions. 

I think of our internal group, you have the most experience with this. Do you have suggestions about which way to go here? 

@berl @simone-codeluppi and @kevinyamauchi, we're also interesting in your opinions here, or if you'd like to tag anyone you know who works a lot with segmentation. 

Thanks!

**Comment by sofroniewn** [comment]
Great - will check this out. In the mean time, here's a google doc with some notes on an annotation tool I specked out a while ago

https://docs.google.com/document/d/1TZuh-Psa7NVEOE2JUPCWcX2pyv-qZhrae-NTP6oHsIE/edit?usp=sharing

**Comment by sofroniewn** [comment]
Gave this issue a review, you do a nice job of calling out to a lot of the existing work in this space. At a very high level I think aligning with projects like Detectron and COCO makes the most sense.

Going back and forth between polygons and binary masks sounds great, but you should make sure that the round trip is idempotent. Also not clear that this is as straight forward in 3D.

If you want to support overlapping regions and probabilistic masks that also constrains you pretty severely.  You can have converters from the other efficient representations, but it might get tricky!!

**Comment by joshmoore** [comment]
Added myself after discussing with @ambrosejcarr how this should/could be taken into account in the future zarr format.

**Comment by ambrosejcarr** [comment]
@berl could you provide me a member list for SpaceTx working group 5? I'd like to ask them some questions about their methods to get a better sense of the requirements they will have for a segmentation format. I don't feel I have enough intuition to make a top-down decision on the format.

**Comment by berl** [comment]
@ambrosejcarr it's in progress... I'll be meeting with Jeremy Miller on Wednesday and can report to the sync call on Thursday. I agree with @sofroniewn that probabilistic assignment of spots to cells and overlapping cells can be a pretty big wrinkle- that may be a place to separate a v1.0 from v2.0, depending on asks from WG5.
Just FYI regarding output formats, I still use GeoJSON geometry collections for 2D polygons. 😃

**Comment by ambrosejcarr** [comment]
@kne42 This issue contains my research thus far on segmentation. Let's chat next week about this!

**Comment by ttung** [comment]
@ambrosejcarr do you have a notion of how many pixels each ROI will have?  Order of magnitude should be sufficient.

**Comment by ambrosejcarr** [comment]
For our current experiments, the lower bound should be approximately (100 x 100), and the upper bound (1000 x 1000). 

@berl and @kevinyamauchi would have more experience to bring to bear on this question.

**Comment by ttung** [comment]
I'm guessing that a flat representation of pixel coordinates will not be efficient.

I would start with just a set of images to represent the masks.

Crazy idea (probably worth only a few minutes of googling): find a union of ellipsoids that approximates the boundary.  This is almost certainly a more compact representation if you have a nonzero error tolerance.

**Comment by berl** [comment]
@sofroniewn has also advocated for mask images.  

I don't think the flat representation would be all pixels, it would be boundary pixels (could be pretty sparse if you're containing a lot of pixels), or in my case, boundary spot locations (even sparser). The main qualitative deficiency of a mask image is that you can't do overlapping regions without a lot of additional data and weirdness.   If users are ok with this restriction and we provide (or point to) tooling to swap between the two, maybe it's ok?   remember that this will necessarily be at the scale of the entire experiment (possibly hundreds of FOVs)

**Comment by ttung** [comment]
Ah, boundary would definitely be a lot more sparse.  I'm wondering if there are any geometries that would not be expressible with just boundaries, but even things like donuts could probably work okay.
