### ISSUE TITLE
TrackpyLocalMaxPeakFinder creates intenisty table with pixel values as floats instead of ints.

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#890]
this is the cause of #825

**Comment by dganguli** [comment]
pixel values are supposed to be floats? or do you mean some 'index' is being set as floats instead of ints?

**Comment by shanaxel42** [comment]
Yea the second! It produces the x/y/z pixel values as floats so then when we try and index on them later everything's sad

**Comment by dganguli** [comment]
ooohhh. yeah i get it. ok the pixel _indices_ need to be set to ints then. that makes a ton of sense.
