### ISSUE TITLE
Formalize the ability for spot detection to return extra data

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#908]
This should be done in the form of a class for returning data from spot detection.  Normally, that encompasses the IntensityTable, but it can hold additional payload.

**Comment by ambrosejcarr** [comment]
Will address #708

**Comment by ambrosejcarr** [comment]
I think this may need to be expanded to:

 "formalize the ability for _Pipeline Components_ to return extra data". 

The pixel decoder will need to emit a second imagestack that, instead of labels, contains the confidence in those labels.

**Comment by ttung** [comment]
> I think this may need to be expanded to:

> "formalize the ability for Pipeline Components to return extra data".

> The pixel decoder will need to emit, in addition to the probability maps for each gene, a label image that contains the ML estimate for the gene corresponding to each pixel.

If pixel decoding moves to image space (i.e., a filter), we should rethink what exactly the remaining spot detection algorithms truly need.

**Comment by ambrosejcarr** [comment]
It could be good to determine if this is still needed while you're deep into spot finding @shanaxel42 

It might be that the elimination of the CLI mitigates this problem.
