### ISSUE TITLE
Formalize PipelineComponent Contracts

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#910]
@ttung @shanaxel42 and @ambrosejcarr discussed how to handle algorithms like the PixelSpotDetector and potential future deep learning approaches that bridge multiple discrete pipeline stages. 

We settled on creating new `PipelineComponents` for any algorithm that has a different _contract_, where a contract is defined as the set of inputs it requires, and the set of output it emits. 

I think the basic primitives that we have right now can be defined as having the following contracts: 
```
Filter(ImageStack, *params) -> ImageStack

SpotDetector(ImageStack, *params) -> IntensityTable, DetectorResult

Decoder(IntensityTable, Codebook, *params) -> IntensityTable[decoded]

Segmenter(ImageStack, *params) -> #838 

AssignCells(IntensityTable, #838, *params) -> IntensityTable[with cells]

Registration(ImageStack, Optional[ImageStack], *params) -> ImageStack
```

The implication for the existing codebase is that the PixelSpotDetector would become its own PipelineComponent: 
```
PixelSpotDetector(ImageStack, *params) -> IntensityTable[decoded]
```

@dganguli @freeman-lab what do you think about this? We didn't find a satisfying solution in our discussion that felt future proof without increasing the complexity around pipeline stages in this way. The only other thing that makes sense would be to use [mixins](https://stackoverflow.com/questions/533631/what-is-a-mixin-and-why-are-they-useful), but python support for those is only OK.

**Comment by ttung** [comment]
Not relevant any more.
