### ISSUE TITLE
SeqFISH Experiment loads slowly (large codebook, many tiles)

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#912]
See `ajc-seqfish-tilefetcher` branch for example notebook. Codebook is 10,000 entires. Field of view has 1740 tiles. It's not clear what's making it slow, but it takes 2 minutes to load by my measurements. 

Related question: experiments can never be loaded from starfish.data locally. We always pull down the json files. Do we want users to be able to cache those so they can be used offline (by request)?

**Comment by joshmoore** [comment]
> It's not clear what's making it slow

Almost all of the time seemed to be the [fill the codebook](https://github.com/spacetx/starfish/blob/7720594380a8e980e8547191dd83ec8e6675a2fa/starfish/codebook/codebook.py#L246) block:

```
        for code_dict in code_array:
            codeword = code_dict[Features.CODEWORD]
            target = code_dict[Features.TARGET]
            for entry in codeword:
                code_data.loc[target, entry[Indices.CH], entry[Indices.ROUND]] = entry[
                    Features.CODE_VALUE]
```

<img width="1105" alt="screen shot 2018-12-20 at 22 36 15" src="https://user-images.githubusercontent.com/88113/50328319-f1647480-04f2-11e9-91e4-385de2f376ec.png">

> experiments can never be loaded from starfish.data locally. We always pull down the json files. Do we want users to be able to cache those so they can be used offline (by request)?

This code block:

```
        backend, name, baseurl = resolve_path_or_url(json_url, allow_caching)
        with backend.read_contextmanager(name) as fh:
            experiment_document = json.load(fh)
```

(with "allow_caching" now being `StarfishConfig().backend`) is used in several places but doesn't actually do caching. :+1: for `load_json_from_path_or_url` (or similar)

**Comment by ambrosejcarr** [comment]
I rebased the osmFISH branch and it too now loads very slowly. That experiment has a _very small_ `Codebook.`

**Comment by ambrosejcarr** [comment]
Looks like building the `xarray.DataArray` is the majority (99.9%) of the time consumption, not loading the json object. Even a partially thought-out preallocation is able to build it at least 3.5x faster. 

![image](https://user-images.githubusercontent.com/5239152/50386410-c412f480-06b3-11e9-8617-9ad777548185.png)

Pre-sizing the targets as a `np.array` didn't make it faster, for me.

**Comment by joshmoore** [comment]
It's surprising that a small codebook would also be _very_ slow, but testing your changes above:

```
        # fill the codebook
        targets = []
        code_data = cls._empty_codebook(target_names, n_ch, n_round)
        for i, code_dict in enumerate(code_array):
            for bit in code_dict[Features.CODEWORD]:
                code_data[i, int(bit[Indices.CH]), int(bit[Indices.ROUND])] = int(bit[Features.CODE_VALUE])
            targets.append(code_dict[Features.TARGET])
        code_data[Indices.TARGET] = (Indices.TARGET, targets)
        return code_data
```

`from_code_array` on the large codebook dropped from 91s to 31s:

![screen shot 2019-01-02 at 12 16 44](https://user-images.githubusercontent.com/88113/50589837-80c13e80-0e88-11e9-826d-dcca4ac42a28.png)

with most of the time in `__setitem__`.

Dropping the use of `_empty_codebook`

```
        # Copied from _empty_codebook
        codes_index = pd.Index(target_names, name=Features.TARGET)
        data = np.zeros((codes_index.shape[0], n_ch, n_round), dtype=np.uint8)
        # fill the codebook
        for i, code_dict in enumerate(code_array):
            for bit in code_dict[Features.CODEWORD]:
                ch = int(bit[Indices.CH])
                r = int(bit[Indices.ROUND])
                data[i, ch, r] = int(bit[Features.CODE_VALUE])
        return cls(
            data=data,
            coords=(
                codes_index,
                pd.Index(np.arange(n_ch), name=Indices.CH.value),
                pd.Index(np.arange(n_round), name=Indices.ROUND.value),
            )
        )
```

`sd.SeqFISH(use_test_data=True)` runs in about 3 seconds since dataarray.isel is no longer needed. (I'm having trouble getting profiler output, perhaps due to the direct use of numpy.)

cF. https://github.com/pydata/xarray/issues/2452

**Comment by ambrosejcarr** [comment]
>                 `data[i, ch, r] = int(bit[Features.CODE_VALUE])`

This is the line triggering `isel` ?

**Comment by joshmoore** [comment]
No, that's in numpy land so no `xarray.DataArray.isel` is involved. The culprit in the 30s variant is:

```
code_data[Indices.TARGET] = (Indices.TARGET, targets)
```
