### ISSUE TITLE
SeqFISH ImageStack loads slowly

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#916]
My notebook hangs on the bottom call of the code block below. When I control + c it, it's doing something with the cache. The python process sits with around 2-10% CPU utilization. 

Reproduce checkout ajc-seqfish-ntoebook (based off of current master : 122a8ae)

```
experiment = starfish.data.SeqFISH(use_test_data=True)

fov = experiment['fov_000']

# this is where it hangs
stack = fov['primary']
```

**Comment by ttung** [comment]
Does this happen with a warmed cache?

**Comment by joshmoore** [comment]
Perhaps the same as gh-912?

**Comment by ttung** [comment]
@ambrosejcarr can you verify that this is still an issue?

**Comment by neuromusic** [comment]
assuming this is no longer an issue. feel free to re-open @ambrosejcarr if that's not the case
