### ISSUE TITLE
Tile Fetchers expect array futures

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#918]
I believe the tile fetchers are broken due to changes in slicedimage in `Tile` or `write_partition_document` which now expect `tile_data` to return a future instead of a `np.ndarray`. 

The following fix works, but I think we should expand our testing to avoid these problems in the future: 

```diff
    @property
    def tile_data(self) -> np.ndarray:
+         def future():
+             return imread(self.file_path)
+         return future
-         return imread(self.file_path)
```

Reproduction: run any TileFetcher on master.

**Comment by ttung** [comment]
I just ran the `get_iss_breast_data.py` script and it works.  I believe the issue is that you're declaring the `tile_data` as a `@property`, but the rest of the codebase no longer does it.
