### ISSUE TITLE
BaristaSeq, Allen data are saved as NPY with TIFF suffixes

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#967]
The following datasets are the most recent versions, to my knowledge, are named `.tif` but are `.npy`. 

`s3://spacetx.starfish.data.public/browse/formatted/20181028/BaristaSeq/cropped_formatted/`
`s3://spacetx.starfish.data.public/browse/20190111/allen_mouse_panel_1/`

I would like for us to test this when we test starfish.data: 
1. Test: fail if data and prefix don't match
2. Library: warn if data and prefix don't match, but starfish is able to decode the data anyway.

**Comment by ambrosejcarr** [comment]
@neuromusic This is blocking @zperova from ingesting the example BaristaSeq dataset.

**Comment by neuromusic** [comment]
re: point 2, does starfish infer the file format from the extension?

**Comment by ttung** [comment]
> re: point 2, does starfish currently infer the file format from the extension?

Only if the format is not specified in the manifest file.

**Comment by zperova** [comment]
@ambrosejcarr  the files are named `.tiff` the primary and nissl images are original and `.tif` and open normally

**Comment by joshmoore** [comment]
Thanks for the rename, @ttung, but @zperova and I would appreciate having TIFF in the first test.

**Comment by neuromusic** [comment]
won't that require soliciting new data from these two groups? or for us to do a batch conversion of the data?

**Comment by neuromusic** [comment]
```
import glob
import numpy as np
from libtiff import TIFF
for fname in glob('*.npy'):
    tiff = TIFF.open(fname.replace('.npy','.tiff'), mode='w')
    im = np.read(fname)
    tiff.write_image(im)
    tiff.close()
```

**Comment by joshmoore** [comment]
@neuromusic : the latter but with the related updates to the primary images json for new file names and new checksums.

**Comment by ambrosejcarr** [comment]
`s3://spacetx.starfish.data.public/browse/formatted/20190207/BaristaSeq/` contains corrected data.
