### ISSUE TITLE
ModuleNotFoundError: No module named 'starfish.display'

### ISSUE THREAD

**Issue by rojinsafavi** [spacetx/starfish#971]
Hello,

I installed starfish with pip.
I am trying to follow the jupyter notebook for MERFISH, but some of the modules are missed, for example, display and Axes

ModuleNotFoundError: No module named 'starfish.display'

Should I use another version of the starfish?

**Comment by rojinsafavi** [comment]
Thanks for your quick response!
I have created a python3.6 virtual env with conda. Then I pip installed as you mentioned. and then I opened the Jupiter notebook, but I am still getting the same error

**Comment by ambrosejcarr** [comment]
Ok, we'll be happy to look into this. Could you please list the commands you used to install and run the notebook, so we can attempt to reproduce the error?

**Comment by rojinsafavi** [comment]
when I install napari version it says that starfish 0.0.30 does not provide the extra 'napari'

Here are the details:

1. conda create -n env_starfish python=3.6
2. source activate env_starfish
3. pip install starfish[napari]

Collecting starfish[napari]
  starfish 0.0.30 does not provide the extra 'napari'
Collecting scikit-learn==0.19.2 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/f9/c8/8db4108aba5e2166cd2ea4eafa1a4b82f89240a1fa85733029cc2358ad1f/scikit_learn-0.19.2-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: trackpy==0.4.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.4.1)
Collecting nbformat==4.4.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: tqdm==4.26.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (4.26.0)
Requirement already satisfied: mpmath==1.0.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.0.0)
Requirement already satisfied: m2r==0.2.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.2.1)
Collecting flake8==3.6.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/34/a6/49e2849a0e5464e1b5d621f63bc8453066f0f367bb3b744a33fca0bc1ddd/flake8-3.6.0-py2.py3-none-any.whl
Requirement already satisfied: pandas==0.23.4 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.23.4)
Collecting Pygments==2.2.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting prometheus-client==0.4.2 (from starfish[napari])
Collecting traitlets==4.3.2 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting pyzmq==17.1.2 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/48/93/59592cb294761aaa40589b544eaa5175446d687ff95beeeb666de60f3274/pyzmq-17.1.2-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: networkx==2.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (2.1)
Collecting six==1.11.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: ipywidgets==7.4.2 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (7.4.2)
Requirement already satisfied: widgetsnbextension==3.4.2 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (3.4.2)
Collecting typed-ast==1.1.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/35/69/94dd92985792df90cf3b544d33315e60a95cc1c7ce0518f73b4cc11f106e/typed_ast-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting nbconvert==5.4.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/b5/bb/94c493051d60e5b9c0f7f9a368b324201818c1b1c4cae85d1e49a41846c7/nbconvert-5.4.0-py2.py3-none-any.whl
Collecting prompt-toolkit==2.0.7 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/d1/e6/adb3be5576f5d27c6faa33f1e9fea8fe5dbd9351db12148de948507e352c/prompt_toolkit-2.0.7-py3-none-any.whl
Requirement already satisfied: sphinxcontrib-websupport==1.1.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.1.0)
Collecting testpath==0.4.2 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/be/a4/162f9ebb6489421fe46dcca2ae420369edfee4b563c668d93cb4605d12ba/testpath-0.4.2-py2.py3-none-any.whl
Collecting mistune==0.8.4 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl
Requirement already satisfied: sympy==1.3 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.3)
Requirement already satisfied: pytest-xdist==1.24.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.24.0)
Collecting jedi==0.13.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/7a/1a/9bd24a185873b998611c2d8d4fb15cd5e8a879ead36355df7ee53e9111bf/jedi-0.13.1-py2.py3-none-any.whl
Collecting pytz==2018.5 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting showit==1.1.4 (from starfish[napari])
Requirement already satisfied: scikit-image==0.14.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.14.0)
Collecting execnet==1.5.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/f9/76/3343e69a2a1602052f587898934e5fea395d22310d39c07955596597227c/execnet-1.5.0-py2.py3-none-any.whl
Collecting notebook==5.7.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/44/16/9f108b675828c4117cfe72d8d0f97094163c40584e40c46ec48a1e862693/notebook-5.7.0-py2.py3-none-any.whl
Requirement already satisfied: cloudpickle==0.5.6 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.5.6)
Collecting chardet==3.0.4 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting pytest==3.8.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/dd/e5/1ce7de3e87ec499a056800fa0d7a689d6502d791c44eb1315a6ecadcb333/pytest-3.8.0-py2.py3-none-any.whl
Requirement already satisfied: pytest-forked==0.2 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.2)
Collecting mccabe==0.6.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting cycler==0.10.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: semantic-version==2.6.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (2.6.0)
Collecting ipython==7.1.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/1b/e2/ffb8c1b574f972cf4183b0aac8f16b57f1e3bbe876b31555b107ea3fd009/ipython-7.1.1-py3-none-any.whl
Collecting imagesize==1.1.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Collecting Babel==2.6.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Requirement already satisfied: Pillow==5.2.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (5.2.0)
Requirement already satisfied: coverage==4.5.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (4.5.1)
Requirement already satisfied: PyWavelets==1.0.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.0.0)
Collecting pandocfilters==1.4.2 (from starfish[napari])
Requirement already satisfied: regional==1.1.2 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.1.2)
Collecting py==1.6.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/c8/47/d179b80ab1dc1bfd46a0c87e391be47e6c7ef5831a9c138c5c49d1756288/py-1.6.0-py2.py3-none-any.whl
Requirement already satisfied: mypy-extensions==0.4.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.4.1)
Requirement already satisfied: requests==2.20.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (2.20.0)
Collecting Send2Trash==1.5.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/49/46/c3dc27481d1cc57b9385aff41c474ceb7714f7935b1247194adae45db714/Send2Trash-1.5.0-py3-none-any.whl
Requirement already satisfied: appnope==0.1.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.1.0)
Requirement already satisfied: ply==3.11 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (3.11)
Collecting jupyter-core==4.4.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from starfish[napari])
Collecting docutils==0.14 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting apipkg==1.5 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/67/08/4815a09603fc800209431bec5b8bd2acf2f95abdfb558a44a42507fb94da/apipkg-1.5-py2.py3-none-any.whl
Collecting nbencdec==0.0.7 (from starfish[napari])
Requirement already satisfied: toolz==0.9.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.9.0)
Collecting more-itertools==4.3.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/79/b1/eace304ef66bd7d3d8b2f78cc374b73ca03bc53664d78151e9df3b3996cc/more_itertools-4.3.0-py3-none-any.whl
Collecting jsonschema==2.6.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pluggy==0.7.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/f5/f1/5a93c118663896d83f7bcbfb7f657ce1d0c0d617e6b4a443a53abcc658ca/pluggy-0.7.1-py2.py3-none-any.whl
Collecting defusedxml==0.5.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting wcwidth==0.1.7 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Requirement already satisfied: slicedimage==1.0.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.0.1)
Requirement already satisfied: packaging==17.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (17.1)
Collecting matplotlib==2.2.3 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/9e/59/f235ab21bbe7b7c6570c4abf17ffb893071f4fa3b9cf557b09b60359ad9a/matplotlib-2.2.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting pickleshare==0.7.5 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting ipykernel==5.1.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/d8/b0/f0be5c5ab335196f5cce96e5b889a4fcf5bfe462eb0acc05cd7e2caf65eb/ipykernel-5.1.0-py3-none-any.whl
Collecting urllib3==1.23 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting entrypoints==0.2.3 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/cc/8b/4eefa9b47f1910b3d2081da67726b066e379b04ca897acfe9f92bac56147/entrypoints-0.2.3-py2.py3-none-any.whl
Requirement already satisfied: seaborn==0.9.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.9.0)
Collecting ipython-genutils==0.2.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting decorator==4.3.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting snowballstemmer==1.2.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting bleach==3.0.2 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/d4/0d/4696373c3b714f6022d668fbab619690a42050dbeacede6d10ed97fbd3e2/bleach-3.0.2-py2.py3-none-any.whl
Collecting idna==2.7 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting numpy==1.15.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/fe/94/7049fed8373c52839c8cde619acaf2c9b83082b935e5aa8c0fa27a4a8bcc/numpy-1.15.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting backcall==0.1.0 (from starfish[napari])
Requirement already satisfied: jsonpath-rw==1.4.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.4.0)
Collecting dask==0.19.2 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/63/cc/d8b279ad3512e682069263de0494eeb9907ebe6b98bef01424be36421e13/dask-0.19.2-py2.py3-none-any.whl
Requirement already satisfied: xarray==0.10.8 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.10.8)
Collecting alabaster==0.7.12 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Requirement already satisfied: mypy==0.641 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.641)
Collecting pyflakes==2.0.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/44/98/af7a72c9a543b1487d92813c648cb9b9adfbc96faef5455d60f4439aa99b/pyflakes-2.0.0-py2.py3-none-any.whl
Collecting python-dateutil==2.7.3 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting kiwisolver==1.0.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/69/a7/88719d132b18300b4369fbffa741841cfd36d1e637e1990f27929945b538/kiwisolver-1.0.1-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: CommonMark==0.5.4 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.5.4)
Requirement already satisfied: diskcache==3.0.6 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (3.0.6)
Requirement already satisfied: Sphinx==1.8.1 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.8.1)
Requirement already satisfied: click==6.7 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (6.7)
Collecting atomicwrites==1.2.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/3a/9a/9d878f8d885706e2530402de6417141129a943802c084238914fa6798d97/atomicwrites-1.2.1-py2.py3-none-any.whl
Collecting pyparsing==2.2.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/42/47/e6d51aef3d0393f7d343592d63a73beee2a8d3d69c22b053e252c6cfacd5/pyparsing-2.2.1-py2.py3-none-any.whl
Collecting terminado==0.8.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/2e/20/a26211a24425923d46e1213b376a6ee60dc30bcdf1b0c345e2c3769deb1c/terminado-0.8.1-py2.py3-none-any.whl
Requirement already satisfied: validators==0.12.2 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.12.2)
Requirement already satisfied: certifi==2018.8.24 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (2018.8.24)
Collecting Jinja2==2.10 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting pycodestyle==2.4.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/e5/c6/ce130213489969aa58610042dff1d908c25c731c9575af6935c2dfad03aa/pycodestyle-2.4.0-py2.py3-none-any.whl
Requirement already satisfied: scipy==1.1.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (1.1.0)
Requirement already satisfied: flake8-import-order==0.18 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.18)
Requirement already satisfied: PyYAML==3.13 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (3.13)
Collecting jupyter-client==5.2.3 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/94/dd/fe6c4d683b09eb05342bd2816b7779663f71762b4fa9c2d5203d35d17354/jupyter_client-5.2.3-py2.py3-none-any.whl
Collecting tornado==5.1.1 (from starfish[napari])
Requirement already satisfied: sphinx-rtd-theme==0.4.2 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.4.2)
Requirement already satisfied: pytest-cov==2.6.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (2.6.0)
Collecting attrs==18.2.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Requirement already satisfied: recommonmark==0.4.0 in /soe/rojinsafavi/.local/lib/python3.6/site-packages (from starfish[napari]) (0.4.0)
Collecting webencodings==0.5.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting ptyprocess==0.6.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting parso==0.3.1 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/09/51/9c48a46334be50c13d25a3afe55fa05c445699304c5ad32619de953a2305/parso-0.3.1-py2.py3-none-any.whl
Collecting pexpect==4.6.0 (from starfish[napari])
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=30 in ./immune/anaconda2/envs/env_starfish/lib/python3.6/site-packages (from flake8==3.6.0->starfish[napari]) (40.6.3)
Installing collected packages: scikit-learn, decorator, ipython-genutils, six, traitlets, jupyter-core, jsonschema, nbformat, pyflakes, pycodestyle, mccabe, flake8, Pygments, prometheus-client, pyzmq, typed-ast, entrypoints, pandocfilters, webencodings, bleach, defusedxml, testpath, mistune, MarkupSafe, Jinja2, nbconvert, wcwidth, prompt-toolkit, parso, jedi, pytz, python-dateutil, numpy, pyparsing, cycler, kiwisolver, matplotlib, showit, apipkg, execnet, tornado, ptyprocess, terminado, jupyter-client, pexpect, pickleshare, backcall, ipython, ipykernel, Send2Trash, notebook, chardet, py, pluggy, attrs, atomicwrites, more-itertools, pytest, imagesize, Babel, docutils, nbencdec, urllib3, snowballstemmer, idna, dask, alabaster, starfish
Successfully installed Babel-2.6.0 Jinja2-2.10 MarkupSafe-1.0 Pygments-2.2.0 Send2Trash-1.5.0 alabaster-0.7.12 apipkg-1.5 atomicwrites-1.2.1 attrs-18.2.0 backcall-0.1.0 bleach-3.0.2 chardet-3.0.4 cycler-0.10.0 dask-0.19.2 decorator-4.3.0 defusedxml-0.5.0 docutils-0.14 entrypoints-0.2.3 execnet-1.5.0 flake8-3.6.0 idna-2.7 imagesize-1.1.0 ipykernel-5.1.0 ipython-7.1.1 ipython-genutils-0.2.0 jedi-0.13.1 jsonschema-2.6.0 jupyter-client-5.2.3 jupyter-core-4.4.0 kiwisolver-1.0.1 matplotlib-2.2.3 mccabe-0.6.1 mistune-0.8.4 more-itertools-4.3.0 nbconvert-5.4.0 nbencdec-0.0.7 nbformat-4.4.0 notebook-5.7.0 numpy-1.15.1 pandocfilters-1.4.2 parso-0.3.1 pexpect-4.6.0 pickleshare-0.7.5 pluggy-0.7.1 prometheus-client-0.4.2 prompt-toolkit-2.0.7 ptyprocess-0.6.0 py-1.6.0 pycodestyle-2.4.0 pyflakes-2.0.0 pyparsing-2.2.1 pytest-3.8.0 python-dateutil-2.7.3 pytz-2018.5 pyzmq-17.1.2 scikit-learn-0.19.2 showit-1.1.4 six-1.11.0 snowballstemmer-1.2.1 starfish-0.0.30 terminado-0.8.1 testpath-0.4.2 tornado-5.1.1 traitlets-4.3.2 typed-ast-1.1.0 urllib3-1.23 wcwidth-0.1.7 webencodings-0.5.1
(env_starfish) -bash-4.2$ 
(env_starfish) -bash-4.2$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> %matplotlib inline
  File "<stdin>", line 1
    %matplotlib inline
    ^
SyntaxError: invalid syntax
>>> 
>>> import pprint
>>> import os
>>> 
>>> import numpy as np
>>> import pandas as pd
>>> import matplotlib.pyplot as plt
>>> from showit import image as show_image
>>> 
>>> import starfish.display
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'starfish.display'
>>> from starfish import data, FieldOfView
>>> from starfish.types import Features, Axes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Axes'

**Comment by ambrosejcarr** [comment]
I'm glad you found a solution -- would you be willing to re-post that tracelog? What you tried did not seem at all like a crazy way to install `starfish`, so we'd like to make sure that users who try your first path in the future are able to install our package.

**Comment by rojinsafavi** [comment]
I am very sorry but I did not save the terminal, I will try to reproduce the error again and post it here :-)
