### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by sofroniewn** [spacetx/starfish#977]
From Tim Wang - 
1) I am having a hard time installing starfish on windows. If I just pip install it, it finds that some libraries (like xarray) are slightly different in version version and produces an error. If I try making a venv/virtualenv I end up with a pip-related error: "Error: Command '['C:\\Users\\JRCLUST\\starfish\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1." which others seem to have complained about with venv. Do you know of a workaround for this?

**Comment by sofroniewn** [comment]
Note also, Napari has been having some windows install problems that I don't think have been addressed yet, but are on our radar - see https://github.com/Napari/napari-gui/issues/75

**Comment by ttung** [comment]
I couldn't reproduce this error that you guys were seeing.  I got further before things broke down.

I installed python3.6, set up a virtualenv (`python -m venv .venv` followed by `.venv\scripts\activate.bat`, ran `pip install starfish`, and was able to launch the starfish command.  A bunch of tests did fail and fixing those will probably take time.  I'm not sure how you set up a virtualenv, but can you try using the standard python virtualenv tool?

**Comment by joshmoore** [comment]
Separately, @ttung, are you interested in trading some travis time for [Windows builds](https://blog.travis-ci.com/2018-10-11-windows-early-release)?
