### ISSUE TITLE
MERFISH

### ISSUE THREAD

**Issue by rojinsafavi** [spacetx/starfish#982]
Hello again :)

I used the  format_merfish_U2OS_data.py to reformat merfish images. Then I passed one of jsons to the following line:
`experiment=starfish.data.Experiment.from_json('/projects/sysbio/projects/czi/u2os_prepro/primary_images-fov_000.json')`

and I got the following error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-13-fa8af58f1bec> in <module>
      1 # load the data from cloudfront
----> 2 experiment=starfish.data.Experiment.from_json('/projects/sysbio/projects/czi/u2os_prepro/primary_images-fov_000.json')

/projects/sysbio/projects/czi/starfish/starfish/starfish/experiment/experiment.py in from_json(cls, json_url)
    184             experiment_document = json.load(fh)
    185 
--> 186         version = cls.verify_version(experiment_document['version'])
    187 
    188         _, codebook_name, codebook_baseurl = resolve_url(experiment_document['codebook'],

/projects/sysbio/projects/czi/starfish/starfish/starfish/experiment/experiment.py in verify_version(cls, semantic_version_str)
    239         if not (MIN_SUPPORTED_VERSION <= version <= MAX_SUPPORTED_VERSION):
    240             raise ValueError(
--> 241                 f"version {version} not supported.  This version of the starfish library only "
    242                 f"supports formats from {MIN_SUPPORTED_VERSION} to "
    243                 f"{MAX_SUPPORTED_VERSION}")

ValueError: version 0.0.0 not supported.  This version of the starfish library only supports formats from 4.0.0 to 5.0.0
```

**Comment by ttung** [comment]
Did you format your data using the same version of starfish that you are processing with?

**Comment by rojinsafavi** [comment]
So I cloned the github, and ran:
` pip install -e .[napari]`

**Comment by rojinsafavi** [comment]
and this is the json example:
`{
    "default_tile_format": "TIFF",
    "default_tile_shape": [
        2048,
        2048
    ],
    "dimensions": [
        "zc",
        "r",
        "x",
        "xc",
        "yc",
        "y",
        "z",
        "c"
    ],
    "extras": {},
    "shape": {
        "c": 2,
        "r": 8,
        "z": 1
    },
    "tiles": [
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H0-C0.tiff",
            "indices": {
                "c": 0,
                "r": 0,
                "z": 0
            },
            "sha256": "ce4e05bb3e201f1b7ea076d361ac010dad7137b7d9fe4b126ef6990964a22973",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H0-C1.tiff",
            "indices": {
                "c": 1,
                "r": 0,
                "z": 0
            },
            "sha256": "7ebb94dac257280956fb7690025b2513822892cba9506f2abe129a2087de73d4",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H1-C0.tiff",
            "indices": {
                "c": 0,
                "r": 1,
                "z": 0
            },
            "sha256": "692b73dd1e83b355a615b31128c4bc466585fea7a56d080109d685074a31f357",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H1-C1.tiff",
            "indices": {
                "c": 1,
                "r": 1,
                "z": 0
            },
            "sha256": "1ff467e184f1e8eeb07ae7b48915725f4e3a8aa3a79d0b987356fbc25c746c9c",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H2-C0.tiff",
            "indices": {
                "c": 0,
                "r": 2,
                "z": 0
            },
            "sha256": "9e7781de1fe0bdbc91af4d5a88f4baf0ba5403f85a068fb9410572e4f606c176",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H2-C1.tiff",
            "indices": {
                "c": 1,
                "r": 2,
                "z": 0
            },
            "sha256": "c0811061b0056d35823e56d91204c3f1cffa0b2500d9b2e6f0d74ad71d7aa71f",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H3-C0.tiff",
            "indices": {
                "c": 0,
                "r": 3,
                "z": 0
            },
            "sha256": "4ba835d7e0b982f7d3fb8311fdbc409c3b64a52296865172aee1a46be0d39acb",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H3-C1.tiff",
            "indices": {
                "c": 1,
                "r": 3,
                "z": 0
            },
            "sha256": "dec56c1a4927cfc0aae47ec4df5dbef6dfc31765e1c7ba5d4dec0150dcf294b5",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H4-C0.tiff",
            "indices": {
                "c": 0,
                "r": 4,
                "z": 0
            },
            "sha256": "cdc9a148486ace8540a24533c89ccbd75931891dabaed69c3f0accd2c1e69304",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H4-C1.tiff",
            "indices": {
                "c": 1,
                "r": 4,
                "z": 0
            },
            "sha256": "f10909d80eedfcb475fc9f5d79904b079e38ee5a3b740ded4b413717eb12e9d5",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H5-C0.tiff",
            "indices": {
                "c": 0,
                "r": 5,
                "z": 0
            },
            "sha256": "0543345e0a97cdd7957a9a5ef3dbfe65b386bf81db2a195f7f847d77f368c0eb",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H5-C1.tiff",
            "indices": {
                "c": 1,
                "r": 5,
                "z": 0
            },
            "sha256": "901ac0f7a139ba98824b0b7d5891d66f4503ea21803b08437da05f814a082a4d",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H6-C0.tiff",
            "indices": {
                "c": 0,
                "r": 6,
                "z": 0
            },
            "sha256": "a02519bf8095fa12a27de1f8d7a8f08e20567cc5f19dad9c2f37a7d9bc514cbd",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H6-C1.tiff",
            "indices": {
                "c": 1,
                "r": 6,
                "z": 0
            },
            "sha256": "58ffdd28e681205d32e0c5342a1ebfa34cce5e286fafa7e8991fdc10cf8a96d4",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H7-C0.tiff",
            "indices": {
                "c": 0,
                "r": 7,
                "z": 0
            },
            "sha256": "cb5152b9475f4368cfd96bd5c704b3cac7620e913a53e8cb81466fe422452a0d",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        },
        {
            "coordinates": {
                "xc": [
                    0.0,
                    0.0001
                ],
                "yc": [
                    0.0,
                    0.0001
                ],
                "zc": [
                    0.0,
                    0.0001
                ]
            },
            "file": "primary_images-fov_126-Z0-H7-C1.tiff",
            "indices": {
                "c": 1,
                "r": 7,
                "z": 0
            },
            "sha256": "193eb3b86a40c26b37e60fd7d1504f064764c6ae565e46aa0aeab79662c97e88",
            "tile_format": "TIFF",
            "tile_shape": [
                2048,
                2048
            ]
        }
    ],
    "version": "0.0.0"`

**Comment by ttung** [comment]
Apologies, this problem is simpler than I thought.  You're using the experiment loader to load the primary_image.  Try:

experiment=starfish.data.Experiment.from_json('/projects/sysbio/projects/czi/u2os_prepro/experiment.json')

**Comment by rojinsafavi** [comment]
here is the experiment.json

{
    "version": "5.0.0",
    "images": {
        "primary": "primary_images.json",
        "nuclei": "nuclei.json"
    },
    "extras": {},
    "codebook": "codebook.json"
}

and when I ran this:
`experiment=starfish.data.Experiment.from_json('/projects/sysbio/projects/czi/u2os_prepro/experiment.json')`

I got the following error:

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/projects/sysbio/projects/czi/immune/anaconda2/envs/env_starfish/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/projects/sysbio/projects/czi/immune/anaconda2/envs/env_starfish/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403 
    404             return _default_pprint(obj, self, cycle)

/projects/sysbio/projects/czi/immune/anaconda2/envs/env_starfish/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

/projects/sysbio/projects/czi/starfish/starfish/starfish/experiment/experiment.py in __repr__(self)
    142         n_fields_of_view = list(self.items())[:print_n_fov]
    143         fields_of_view_str = "\n".join(
--> 144             f'{k}: {v}' for k, v in n_fields_of_view
    145         )
    146 

/projects/sysbio/projects/czi/starfish/starfish/starfish/experiment/experiment.py in <genexpr>(.0)
    142         n_fields_of_view = list(self.items())[:print_n_fov]
    143         fields_of_view_str = "\n".join(
--> 144             f'{k}: {v}' for k, v in n_fields_of_view
    145         )
    146 

/projects/sysbio/projects/czi/starfish/starfish/starfish/experiment/experiment.py in __repr__(self)
     72         images = '\n    '.join(
     73             f'{k}: {v}'
---> 74             for k, v in self._images.items()
     75             if k != FieldOfView.PRIMARY_IMAGES
     76         )

/projects/sysbio/projects/czi/starfish/starfish/starfish/experiment/experiment.py in <genexpr>(.0)
     73             f'{k}: {v}'
     74             for k, v in self._images.items()
---> 75             if k != FieldOfView.PRIMARY_IMAGES
     76         )
     77         return (

/projects/sysbio/projects/czi/immune/anaconda2/envs/env_starfish/lib/python3.6/site-packages/slicedimage/_tileset.py in __repr__(self)
     25         attributes = [
     26             "{k}: {v}".format(k=k, v=self.shape[k])
---> 27             for k in self.dimensions - {'y', 'x'}
     28         ]
     29         xmin, xmax, ymin, ymax = float("inf"), float("-inf"), float("inf"), float("-inf")

/projects/sysbio/projects/czi/immune/anaconda2/envs/env_starfish/lib/python3.6/site-packages/slicedimage/_tileset.py in <listcomp>(.0)
     25         attributes = [
     26             "{k}: {v}".format(k=k, v=self.shape[k])
---> 27             for k in self.dimensions - {'y', 'x'}
     28         ]
     29         xmin, xmax, ymin, ymax = float("inf"), float("-inf"), float("inf"), float("-inf")

KeyError: 'xc'`

**Comment by rojinsafavi** [comment]
Any updates on this?

**Comment by ttung** [comment]
Sorry for the delay.  https://github.com/spacetx/slicedimage/pull/79 is the fix for this.  I should have released this earlier.  As soon as we resolve some build issues on starfish, we'll push this.

**Comment by berl** [comment]
just ran into this too, but I don't get the error if there's no output- I can run some processing on the experiment, but most other methods on the experiment instance return the error @rojinsafavi referenced above.
looking forward to the update!

**Comment by ttung** [comment]
@rojinsafavi @berl This should work (better) now.  Please let me know if you have issues after updating.
