### ISSUE TITLE
Stale travis status requires settings change

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#999]
see: https://github.com/travis-ci/travis-ci/issues/10204
see: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

> To fix this issue, update your repositories using protected branches to require GitHub Checks as follows:

1. Go to the repository’s Branch Settings page (https://github.com/OWNER/REPO/settings/branches).
2. In the "Branch Protection Settings" section, click "Edit" for a protected branch
3. Scroll down to the second box, "Require status checks to pass before merging." Select either "Travis CI - Pull Request" or "Travis CI - Branch" or both. (Note: "continuous-integration/travis-ci" is the Status API event which is deprecated)
4. Save your changes

![screen shot 2019-02-12 at 11 32 44](https://user-images.githubusercontent.com/88113/52629435-f114a400-2eb9-11e9-8f99-9bd13e531e33.png)

**Comment by ttung** [comment]
Did this change recently?  I fixed it for travis-ci.org but this appears to be something different.

**Comment by joshmoore** [comment]
I don't know, but my PRs are all now green :+1:
